### ISSUE TITLE
Advance to next page of results on fire tv?

### ISSUE THREAD

**Issue by dogbowl** [DxCx/plugin.video.9anime#10]
Hi!  This is a great addon.  I just have one issue.  I have it installed to fire tv, and I'm only seeing 30 results when browsing genres.  Is this just one page of results, and if so, is there a way to advance to the next page?  I tried every button on the remote and I can't find a way.

Thanks!

**Comment by DxCx** [comment]
Thanks for the support :), Last item on the list should be 'Next Page'

**Comment by dogbowl** [comment]
Thanks for the reply!  I see 'next page' at the bottom of Latest and Newest, but not inside individual genres. They just show 30 results without 'next page' at the bottom.  Thanks again!

**Comment by DxCx** [comment]
Oh, because Generes does not have next page, all the geners are there, or you mean the anime list inside a genere?
can you take a screenshot..? (Drag it to GitHub reply box will upload it)

**Comment by dogbowl** [comment]
I mean the anime list inside of a genre.  For example, only 30 results show up in Action, and there's no 'next page' at the bottom.  I assume there should be more than 30 Action anime?

I will get a screenshot after work.  :)

**Comment by DxCx** [comment]
well, no i am home and i was actually able to see it, so yeah it will be fixed (Not today, but i'll take care of it)
Thanks alot for the bug report @dogbowl , will update here.

**Comment by DxCx** [comment]
Hey @dogbowl ,
that was pretty easy fix eventually, you can redownload zip from master and it should work.
please reopen if it does not :)

**Comment by dogbowl** [comment]
Thank you so much!
