### ISSUE TITLE
Getting search results. No sources are found

### ISSUE THREAD

**Issue by acidmanifesto** [DxCx/plugin.video.9anime#102]
Get searching results but when i click on the links there are no sources showing. 9anime site works fine.

**Comment by DxCx** [comment]
hey @acidmanifesto are you using latest version?
i've just checked and the addon is working as expected...

**Comment by acidmanifesto** [comment]
@DxCx i am, but apparently it is no longer happening when i checked again a hour later. maybe it was a issue with the site and not the addon. so since it is no longer a issue i will close the issue.
