### ISSUE TITLE
Getting stuck Fetching sources

### ISSUE THREAD

**Issue by gooksta** [DxCx/plugin.video.9anime#103]
I don't know if it's just me, however on some episodes it will get stuck on "fetching sources" "Processing RapidVideo". After it fails I need to force stop kodi and restart otherwise it doesn't work again :(

Example i can use is one piece episode 651 and a few others i don't honestly remember. It only seems to happen with a few episodes. 

Is there anyway i can remove Rapidvideo as a source? (I usually use F4/F2) anyways, I've never used RapidVideo or Opensource before :X

version: 0.0.16
on Firestick

**Comment by icpryde** [comment]
Yup I'm having the same issue, I just tried watching hunterxhunter episode 116 and it gets stuck on finding sources for rapid video

**Comment by gooksta** [comment]
yeah, we'll just have to wait till @dxCx can get back to us. Kind of annoying but considering how great this addon is i can't really complain atm.

**Comment by DxCx** [comment]
hey,

i never had that issue but if i recall correctly at the moment in the settings you can request for one specific source if i remember correctly, can you see if that helps you?
if not, maybe we will need to make that the opposite? some checkbox list of what to use and what not..?

**Comment by gooksta** [comment]
@DxCx you cannot specify a single source. You can specify Openload(opensource)? don't remember the name, and rapidvideo as the two choices(I believe). I do not have it in front of me atm. You cannot specify F2/F4 sources which pretty much always work and are the nicest quality/speed.

If you could somehow make it allow me to only show "F2/F4" that would be amazing, since i could literally just press play and it'll only play F4 source :D

**Comment by DxCx** [comment]
Ok, so we will need to replace this functionality with filter list, so people can just ignore sources..

**Comment by hoppler** [comment]
id suggest a list in the settings which says, those sources shall be fetched immediately and the other sources shall be visible but only fetched if the user explicitly clicks on it. so we always have a fallback if the preferred sources are not available.

As a result youd see oin the sourcelist of an episode with F1, F2 enabled as "immediately fetching":
F1 720p
F1 1080p
F2 1080p
OpenLoad (will be fetched on click)
RapidLoad (will be fetched on click)

**Comment by gooksta** [comment]
What hoppler said would be absolutely amazing. IT would allow us the choice of using openload or rapidshare if we really wanted to otherwise just completely ignore it

**Comment by p1wookie** [comment]
I hit this for the first time today on my Fire Stick trying to load up episode 98 of Dragon Ball Super

**Comment by LordCorellon** [comment]
That's one of the reason I forked my path out to show all sources and allow selecting source by quality too (I've noticed DxCx's branch will drop some 1080p sources if another server is more favorable) it allow addresses the issue with only 1/2 the genre's showing.    However I don't know python so only barely manage to stay somewhat current with DxCx and really never figured Github out and the whole push/pull thing so can't say my fork is anywhere reliable

**Comment by DxCx** [comment]
@LordCorellon can you sum your changes?
I've seen there is some fix/change to genere's RE..
but because the forks are already too far from each other i cannot see anything else..

**Comment by LordCorellon** [comment]
NineAnimeBrowser.py
` _GENRE_LIST_RE = \
    re.compile("<li><a\shref=\"/genre\/(.+?)\"\stitle=\"(.+?)\">",
               re.DOTALL)`
Fixes every other Genre from being skipped
`def get_episode_sources(self, anime_url, episode):
	servers = self._get_anime_info(anime_url)
        sources = map(lambda x: (x[0],
            filter(lambda y: y['id'] == episode, x[1])), servers.iteritems())
        sources = filter(lambda x: len(x[1]) != 0, sources)
        sources = map(lambda x: (x[0], x[1][0]['source']), sources)
        sources = [item[1] for item in sources]
        items = []
        for url in sources:
            try:
                reqObj = http.send_request(url)
                page_content = reqObj.text
                episode_id = url.rsplit('/', 1)[1]
                ts_value = NineAnimeUrlExtender.get_ts_value(page_content)
                extra_param = NineAnimeUrlExtender.get_extra_url_parameter(episode_id, 0, ts_value)
                vid_info = simplejson.loads(self._get_request("https://9anime.to/ajax/episode/info?ts=%s&_=%d&id=%s&update=0" % (ts_value, extra_param, episode_id)))
               vid_id = vid_info['params']['id']
               token = vid_info['params']['token']
                options = vid_info['params']['options']
                base_grabber = 'https://9anime.to/grabber-api/?id='+vid_id+'&token='+token+'&options='+options
                video_links = simplejson.loads(self._get_request(base_grabber))
                for i in video_links['data']:
                    items.append({'name' : 'Play '+i['label'],
                                  'url' : 'playlink&url=/'+urllib.quote_plus(i['file'])})
            except:
                pass
        return map(lambda x: utils.allocate_item(x['name'], x['url'], False, ''), items)`
Adds the sources as directory items (Since I browse from a tablet I always preferred viewing sources as a page rather then on screen (this way I could queue up the next episode to be ready to start)   Also presents all the source options from the servers so I can select, ultimately I'll like to have the server name as part of the label but haven't gotten to that yet.

default.py
`@route('playlink*')
def PLAY_SOURCE(payload):
    return control.play_source(urlparse.unquote(payload))`
Handler for the new source selection function

I'm sure there are much better ways to accomplish what I've done but I've never worked with Python before and have collectively maybe a weeks experience, most of that was learning curve in trying to trace your code and understand the token and ajax api from the site.

Again I apologize for my lack of GIT, I really have to learn how to use it properly one day but it's another thing on my list of things I need to learn.

**Comment by LordCorellon** [comment]
I think I screwed up the rebase so there are more commits showing then there actually are changes but I have redid the code to make it possible to merge into your fork if desired, submitted a pull request to do so.  I'm sure some of the code you could clean up to be cleaner, I'm not that fluent in python to match your level and style

**Comment by gooksta** [comment]
@DxCx Any chance you'll have sometime to figure this issue out for us? <3 dying with some of them lol

**Comment by LordCorellon** [comment]
If anyone is interested I built a basic source filter into my fork, replaced the generic sever select with multiple toggle switches for F2, F4, RapidVideo, MyCloud and OpenLoad.   You can turn each source on or off as desired.   

Works both with the classic "list" style source selection as well as my "directory" style source selection which I prefer as I use a tablet to control the Kodi
