### ISSUE TITLE
How to install on libreelec

### ISSUE THREAD

**Issue by AtsuiPanda** [DxCx/plugin.video.9anime#113]
I've been wanting a raspberry pi3 and wanted to also use libreelec ( kodi ) but the way I install this addon with my firestick probably won't work ( downloader app )

**Comment by DxCx** [comment]
Hi @AtsuiPanda

I dont own rpi myself, but i was helping a friend few month ago,
Ive downloaded the repo zip into sd card and then installed it in the rpi.
If you resolved it in a different manner, please share with others :)
