### ISSUE TITLE
Add-on is broken as of today

### ISSUE THREAD

**Issue by pjcanales** [DxCx/plugin.video.9anime#114]
Hello last nite the add-ons was working perfectly. However when I tried it at 2:15pm central it doesn't seem to work.  The latest,newest,recent subbed,popular subbed,recent dubbed,popular dubbed,genres,search . What could have caused this issue.  On website says they are maintaining the server. F3 server Wil be back up in few days. Could this have cause the Add-on to break?

**Comment by JinKudo** [comment]
same here. been watching anime until 5am. but suddenly stopped working in the afternoon.

**Comment by JavierZ667** [comment]
It's not working for me either, tried reinstalling Kodi and 9anime and nothing worked.

**Comment by DxCx** [comment]
hey guys thanks for the report,
i've confirm it's not working,
will take care of that and release a version asap

**Comment by DxCx** [comment]
Closed By #116 
Enjoy
