### ISSUE TITLE
not working as of yesterday 

### ISSUE THREAD

**Issue by Milkshake9999** [DxCx/plugin.video.9anime#120]
Hi the addon has been working for me for the last 3 months first of all i was on 0.0.17 when the issue first started whenever i clicked a show icon i would get " 9anime error check the logs for more info " after trying countless times of uninstalling and reinstalling and even reinstalling my os I checked your page and i saw that the last update was from 23 hours ago I downloaded as a zip transferred it to my pi and now when i click the show icon i can see the episodes count but when trying to click on a episode i get the same error my current setup is
Device: Raspberry pi 3 
os: Libreelec 8.0.2
Addons: The youtube addon and 9anime

**Comment by DxCx** [comment]
hey @Milkshake9999 there was an issue with the website itself yesterday
it didnt work for me either, i've confirmed now it is back to be functional (both site & plugin)
can you give it another try?

**Comment by Milkshake9999** [comment]
It's working now thanks for the help and thanks for making this wonderful Addon ;)
