### ISSUE TITLE
plugin crashes  kodi   95% of the time when playing a  video  (update Xenial issue)

### ISSUE THREAD

**Issue by pghnismo** [DxCx/plugin.video.9anime#121]
i've had this  plugin working fine on  my  rpi  as well as windows,  the  issue i'm having is  running it on  linux  the moment i select a video  95% of the time  it causes a  segfault and closes  kodi  leaving a  crash log. i'm running  kodi  17.4  on  linux mint  18.1  any help  or direction  would  be greatly appreciated  i've attached the log that kodi  produces on  segfault

[kodi_crashlog-20170903_140522.txt](https://github.com/DxCx/plugin.video.9anime/files/1273117/kodi_crashlog-20170903_140522.txt)

**Comment by DxCx** [comment]
hey @pghnismo 
from the log the only error is related to indigo thingy: "/home/fr0th/.kodi/addons/plugin.program.indigo/service.py"
not sure what is that.

but please reply this with logging enabled: go to settings (Gear icon) => System Settings => Logging => enable first.
then repeat the process and send a detailed log.
also, the crash happens as soon as you play like when selecting sources? or just right after the source was selected?

**Comment by pghnismo** [comment]
the crash happens both when  selecting something like  latest or when selecting the video , it does not make it to the source page the moment the video is selected kodi  force closes .

as for indigo it was an old installer program for a repo.   i uninstalled it just  because it no longer works

 here is the log requested as well as current crash log 
[kodi.txt](https://github.com/DxCx/plugin.video.9anime/files/1275150/kodi.txt)
[kodi_crashlog-20170904_120001.txt](https://github.com/DxCx/plugin.video.9anime/files/1275155/kodi_crashlog-20170904_120001.txt)

**Comment by DxCx** [comment]
looks like to me that the python interpeter causes the crash,
but i cannot find anything that can indicate reason..
did you try it on other linux computer/distro? i originally developed the addon over linux and later on moved to mac but it was working..

**Comment by pghnismo** [comment]
i'm thinking this is due to kodi updating  possibly. 

also,  what version of python was this written for ? i'm  using  version 2.7.12

i'll try  removing  my kodi folder  and reinstalling everything  after i get home and reply the results.

**Comment by DxCx** [comment]
no sure which python version but it is 2.x,
it is bound to kodi version as kodi comes with the interpreter.

**Comment by pghnismo** [comment]
not sure whats causing it, i  ran "apt-get remove kodi"  "apt-get purge kodi"  deleted all userdata in my home folder , reinstalled a fresh copy  and only installed the plugin with the same result 
[kodi_crashlog-20170906_085717.txt](https://github.com/DxCx/plugin.video.9anime/files/1281117/kodi_crashlog-20170906_085717.txt)
[kodi.txt](https://github.com/DxCx/plugin.video.9anime/files/1281123/kodi.txt)

**Comment by DxCx** [comment]
which distro are you using? i'll try to run it under a VM..

**Comment by pghnismo** [comment]
i think i have figured out the issue,  i'm running mint 18.2  which is  ubuntu  xenial,  when  kodi went to krypton  it changed the version of  python-cryptography and python-openssl    and that's what makes  kodi segfault .  i have to find a way to update  those items without breaking the system dependencies  for it to function

**Comment by DxCx** [comment]
hmm, Im happy you've found the root cause.
im not a big fan of mint myself, but aren't there repo that gives you kodi out-of-the-box?

**Comment by pghnismo** [comment]
https://forums.linuxmint.com/viewtopic.php?t=241948&start=20#p1299763

i found a solution that didn't break anything and seems to have resolved my issue. 

it does  have kodi  from a repo but the  python-openssl and python-cryptography versions  on the OS were  too old which caused the segfault, this is also an issue for ubuntu 16.04 LTS  as well. 

thank you for pointing me into the direction with the  python interpreter

**Comment by DxCx** [comment]
sure thanks @pghnismo for sharing your solution incase someone in the future will tackle it. =)
