### ISSUE TITLE
Addon dependency not met python 2.25.0

### ISSUE THREAD

**Issue by gaining** [DxCx/plugin.video.9anime#122]
Hi, I tried to update to the newest version to ftmc kodi, a version of kodi with https that runs on android kitkat but I'm having this dependency error. However, when installing it (v0.0.19) from a backup, using the backup addon, it installs and works fine. Is there a way to fix this without needing to use a backup? It seems that dependency check isn't really needed.

**Comment by DxCx** [comment]
hmm,
the idea behind this was to allow only kodi 17+.
below that it won't work, and then there are issues flooding here about that..

that sounds to me like an issue with ftmc, if its based on kodi 17 it should be able to allow python 2.25.0

**Comment by gaining** [comment]
it's based on Kodi 16 but has https. When installed via backup add-on everything works. Could maybe the dependency check be an https check instead of the python version?

**Comment by DxCx** [comment]
im sorry @gaining but i dont feel i can help much as i said before..
unless you will let me know which other capability will work there and on kodi 17 and not on kodi 16, i don't know one myself...

**Comment by gaining** [comment]
Never mind, I modified you addons.xml file so that it could install on my kodi.

**Comment by vader913** [comment]
@gaining how did you install it on ftmc? I've been trying also...could you let me know? Thanks!!!

**Comment by gaining** [comment]
It's more of a small hack than anything. Download the addon in the form of a zip, extract it, locate and open the addon.xml file, fine line:   `<import addon="xbmc.python" version="2.25.0" />` replace it with `    <import addon="xbmc.python" version="2.1.0"/>` save the file than rezip the addon. You'll be then able to install it in ftmc and everything works as it should.

**Comment by vader913** [comment]
@gaining Awesome Thank you buddy!!!! It worked!!!! Cheers!!!!

**Comment by writetome1** [comment]
Thank you buddy!!!! It worked also for me !!!! Cheers!!!! Very simple, most effective !!!
