### ISSUE TITLE
kodi crashing on using server F4

### ISSUE THREAD

**Issue by giftedx29** [DxCx/plugin.video.9anime#123]
everytime i use source F4 it crashes, works on rapidvideo and mycloud, openload

**Comment by DxCx** [comment]
crashes? whole kodi? or just returns error?
F4 sources are tended to be deleted unfortunately..

**Comment by giftedx29** [comment]
Whole kodi and no codes when crashing that I am aware of. I can try and
double check system log but not sure how to do it on nvidia shield normally
I always SSH into my boxes

**Comment by DxCx** [comment]
this is probably issue with kodi itself rather then the plugin,
but can you share your debug log please?

**Comment by giftedx29** [comment]
[kodi.log](https://github.com/DxCx/plugin.video.9anime/files/1376376/kodi.log)

**Comment by DxCx** [comment]
not sure what's going on in there, but your log is full of IO errors,
can you try and reset kodi's data? (remove the whole data directory, then reinstall the plugin and try)

**Comment by DxCx** [comment]
no response for long time :\ reopen if still relevant...
