### ISSUE TITLE
Add-on not found in repository

### ISSUE THREAD

**Issue by Tryouthub** [DxCx/plugin.video.9anime#124]
Hi, I can't pull the add-on from the zip using Kodi on x96. The repository is there, but not the actual add-on. Thanks.

**Comment by Tryouthub** [comment]
I fixed the issue. I had factory reset my Kodi box and it was not up to date. I tried to update from google play, but it said I had the most recent version, but I obviously didn't because it didn't say Krypton at start up. The confluence or whatever skin was default and very bothersome compared to the simple layout of v17 krypton. So I uninstalled Kodi completely and reinstalled it. I re-added all my repos and add-ons. 9anime works just fine. Thanks

**Comment by DxCx** [comment]
Cool, Thanks for the update! might be helpful for someone in the future 👍
