### ISSUE TITLE
rapidvideo taking for ever

### ISSUE THREAD

**Issue by Theangelofspace15** [DxCx/plugin.video.9anime#126]
it started yesterday. but when I activate rapidvideo as 1 of tge server it takes forever in the fletching sources screen. amd noother server works. f4 doesnt work anymore, cloud always give a error, and openload need catch.

**Comment by DxCx** [comment]
hey @Theangelofspace15 
i was on a vacation with limited connecitiviy so sorry for the delay,
i've used the addon lastnight watching rapidvideo source and it was working fine,
do you still have an issue with that?

**Comment by DxCx** [comment]
Closed due to inactivity.
