### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by pjcanales** [DxCx/plugin.video.9anime#127]
Any chance of putting a way to log in and save our shows to get them faster to keep up with latest?

**Comment by DxCx** [comment]
Duplication of #23.

This feature requires time that i dont have much anymore,
im trying to maintain the plugin and make sure it works, but i cannot effort more bandwidth then that..

i've tried to raise donations so i can take some time off and do some enhancements (login was one of them), but noone donated even one cent...

**Comment by JaeFr0st** [comment]
How much money do you need? I’m willing to put up the money if you can also make watchcartoononline work as well since dandymedia is no longer around.

**Comment by JaeFr0st** [comment]
How much money do you need to get this started?
