### ISSUE TITLE
can't find eliable sources

### ISSUE THREAD

**Issue by Dranzera** [DxCx/plugin.video.9anime#129]
Hi I'm trying to play Foodwars 3rd season, dragon ball super and Yugioh GX and they don't work in Kodi. I have the latest version of Kodi. These anime do play on your website.

**Comment by miasmaejuices** [comment]
These are available on the G2 server. I just tested them, and they function properly.

The G2 server is not yet available in the current version of the plugin.

**Comment by DxCx** [comment]
hey @Dranzera just checked it and it is working on both rapidvideo and openload
are you still having this issue?

**Comment by miasmaejuices** [comment]
Just tested the new code with the G2 server, and all of those shows are working.

**Comment by Dranzera** [comment]
I have put the latest update (version 0.0.19) in Kodi.
Dragon Ball Super doesn't work in Kodi, Foodwars 3rd season doesn't work, Yugioh GX doesn't work either. I don't know why it doesn't work for me.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DxCx** [comment]
on what HW your Kodi is working?

**Comment by miasmaejuices** [comment]
In the settings, make sure to enable G1 and G2, I don't know if they're enabled by default.

**Comment by Dranzera** [comment]
I don't know what an HW is but it's on a PC and it's the newest version of Kodi.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by miasmaejuices** [comment]
@DxCx updated the repository and plugin but the G1 and G2 servers aren't listed. Doesn't look like the changes are being picked up. Still version 0.0.19. could that be the issue?

**Comment by DxCx** [comment]
0.0.20 was released few minutes ago, it contians support for G1/G2.
However, all sources should work now (Working here at least)
Dranzera, can you please enable debug logging and upload the kodi.log after it fails?
i want to see why it fails

**Comment by Dranzera** [comment]
I tried that but I don't know where the log iself ìs it's not where it tells me to look. How do I find this log?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DxCx** [comment]
Which operation system?

**Comment by Dranzera** [comment]
I have a Windows 8.1

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by miasmaejuices** [comment]
@Dranzera - Ok, did some testing, here's what I found:

- For some reason, on 17.3 and 18.0 ALPHA1, the only versions available are those cached in the downloaded addons
 - Kodi doesn't want to refresh the repo for this plugin, and states it's still 0.0.19
 - Uninstalling the repo addon, then reinstalling it, may solve the issue
 - Uninstalling and reinstalling the 9anime addon may also solve the issue
 - Downloading the addon manually, then installing from zip, definitely solves the issue

Can you perhaps walk through these steps and see if any of them help?

**Comment by Dranzera** [comment]
Thanks a lot now they work! I guess sometimes the most simple thing is a solution.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DxCx** [comment]
Thanks @miasmaejuices 👍
