### ISSUE TITLE
[REQ] Open up the Wiki for editing

### ISSUE THREAD

**Issue by miasmaejuices** [DxCx/plugin.video.9anime#139]
As there are multiple platforms, and varying versions of Kodi in the wild, it might be a good idea to open up the Wiki, so we/I can contribute by way of tutorials and workarounds.

I feel these things shouldn't be in the code repo, otherwise it just bloats.

Would be a good place to add things like FAQ's etc.

**Comment by DxCx** [comment]
Ofcourse! Thanks alot! :)
Ive just created the first page, is that enough for you to edit?
Do i need to do more stuff to make it happen?

**Comment by miasmaejuices** [comment]
@DxCx - Hmmm, looks like there may be permissions involved, as I don't have access.  It's ok.  There's no rush. It might need some testing at some point to see how it can be done.  I usually use gitlab or self host, so not sure how github handles permissions.  I assumed it would be similar to code, you know: fork => edit => pull => merge.  If you need a little help, just let me know.  Maybe we can figure it out.  You may get a notification from my fork as I test out permissions etc.  :)

**Comment by miasmaejuices** [comment]
Ok, so it looks like there is indeed permissions. [https://imgur.com/SIxMdy2](url)

It seems that if you want it publicly editable, you need to remove check for restrictions in:

Settings => Options => Restrict editing to collaborators only

Either that, or add the people you want access to editing to:

Settings => Collaborators => Add collaborators

Like this: [https://imgur.com/tpsYj0T](url)

Hope that helps :)

**Comment by DxCx** [comment]
just added you as collaborator.. 👍
