### ISSUE TITLE
9anime blank again

### ISSUE THREAD

**Issue by IceFireDude** [DxCx/plugin.video.9anime#14]
it is doing what it did before and being blank again. when you click anything it is blank but if you click genre it lets you pick one but then no anime shows up just blank with a next page at the bottom. was working a few mins ago

**Comment by kilozz** [comment]
came here to say this, unfortunately. might be the site's structure that updated.

**Comment by IceFireDude** [comment]
@kilozz hopefully the fix is the same as last time. Maybe there should be two versions of the 9anime addon one for each domain so if one goes down or changes the other will still be strong. but idk I do not make kodi addons wish i did though lol

**Comment by DxCx** [comment]
Hey,
so yeah, there was a site update, i've fixed the indexing so anime is showing,
but looks like only Server 1 is being parsed as source, so i want to fix them all togather.

**Comment by DxCx** [comment]
I've Merged the patch for indexing so we can use the plugin in the meanwhile,
you can test it, i'll take care of sources parsing over the weekend probably.

**Comment by DxCx** [comment]
@IceFireDude - `Maybe there should be two versions of the 9anime addon one for each domain so if one goes down or changes the other will still be strong`
the website html slightly changed, 2 plugins won't help you here .. :)

**Comment by rahafuf** [comment]
Seems like the add on is showing blank again. Any idea when it might be fixed?

**Comment by DxCx** [comment]
Well, thats not domain change, next domain change ill just add option to
change url..
However they did reconsturct the site so ill need to rebuild some parts to
make it work again..
Probably over the weekend ill release a new version
