### ISSUE TITLE
G2 link not working for me

### ISSUE THREAD

**Issue by XxkingkrowxX** [DxCx/plugin.video.9anime#140]
Like the tittle says g2 links will not start I just get the log thing. Turned g2 links off and streaming just fine now. Thought I should let you know. Thanks for the great work

**Comment by miasmaejuices** [comment]
Thanks.  This isn't an issue with the addon.  9anime have removed the G1 and G2 servers.  Unfortunately, all thats left (mostly) is RapidVideo; MyCloud and OpenLoad.

Downloads have also been disabled.

Unfortunately, it seems they have hosting issues.

**Comment by XxkingkrowxX** [comment]
Ok not to big of an issue other than the others being a lot slower sometimes. Thank you for the hard work

**Comment by miasmaejuices** [comment]
Just a short note to tell you that the G2 servers are running again.  Looks like they sorted out their issue.
