### ISSUE TITLE
Exception in NineAnimeBrowser.py

### ISSUE THREAD

**Issue by Miwer** [DxCx/plugin.video.9anime#144]
Hi, 
Just want to let you know of this exception I came across, while using this plugin. If somehow the site is unresponsive, or give an empty list of sources, I get this in the log:

```
22:55:51.150 T:1476   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
  Error Type: <type 'exceptions.ValueError'>
  Error Contents: max() arg is an empty sequence
  Traceback (most recent call last):
    File "C:\Users\mediauser\AppData\Roaming\Kodi\addons\plugin.video.9anime\default.py", line 165, in <module>
      router_process(control.get_plugin_url())
    File "C:\Users\mediauser\AppData\Roaming\Kodi\addons\plugin.video.9anime\resources\lib\ui\router.py", line 39, in router_process
      return route_obj.func(payload)
    File "C:\Users\mediauser\AppData\Roaming\Kodi\addons\plugin.video.9anime\default.py", line 54, in ANIMES_PAGE
      episodes = _BROWSER.get_anime_episodes(animeurl, isDirectoryStyle())
    File "C:\Users\mediauser\AppData\Roaming\Kodi\addons\plugin.video.9anime\resources\lib\NineAnimeBrowser.py", line 145, in get_anime_episodes
      mostSources = max(servers.iteritems(), key=lambda x: len(x[1]))[0]
  ValueError: max() arg is an empty sequence
  -->End of Python script error report<--
```

I think an empty check is needed after assigning the `servers` variable in line 144, before running the max() on it in line 145.

**Comment by DxCx** [comment]
hey @Miwer 
8 hours ago 9anime website was down,
when website is down, addon won't work.
please give it a try now as it is working again

Thanks for the report though

**Comment by Miwer** [comment]
Hi @DxCx 
Yeah I noticed the website had problems, after seeing this error. Still I think it'd be worth reporting this, in case you wanted to clean up some bugs along the way. Crashes like these should be avoided, when possible. I also didn't like the message about possible memory leaks - that's always a bad thing :D 

Anyway, I can't reproduce the error now that the site is working again, so this is just a low priority issue.

**Comment by DxCx** [comment]
the memory leak thingy in this case can be ignored
and yeah it will probably be better to test for this case ahead and give proper message to the user.
that's the reason i kept the issue open
