### ISSUE TITLE
Add G3 Server

### ISSUE THREAD

**Issue by ipanggabean** [DxCx/plugin.video.9anime#145]
I don't know since when, but they have added another server which is G3 Server. Can you add this server as source?

Example link can be found here: https://9anime.is/watch/one-piece.ov8/w8kppk

**Comment by miasmaejuices** [comment]
Thanks.  Investigating.

**Comment by miasmaejuices** [comment]
Latest patch applied, Added and tested G3 server.
Waiting for release v0.0.22

If you cant wait for the release, you can grab the [master.zip](https://github.com/DxCx/plugin.video.9anime/archive/master.zip) directly.

**Comment by DxCx** [comment]
Thanks @miasmaejuices 👍

**Comment by DxCx** [comment]
v0.0.22 is released. 👍
