### ISSUE TITLE
9anime slow loading

### ISSUE THREAD

**Issue by ebby84** [DxCx/plugin.video.9anime#147]
addon seems to load very slow..is it only me??anyway great addon as always..thank you

**Comment by DxCx** [comment]
hey @ebby84

do you mean in general?
or it was working good before and then just started to happen and then you've opened the issue?
it happened to me couple of times before,
this happens when there is alot of pressure on 9anime servers.
the latency you are feeling comes from there.

**Comment by miasmaejuices** [comment]
I've personally found that it takes 5-10 seconds to load each page, as it has to scrape 9anime for data.

Other than that, it's fine here.

**Comment by ebby84** [comment]
thanks for the reply bro..i guess it was the server..working great now..tq so much
