### ISSUE TITLE
Server F2 never plays

### ISSUE THREAD

**Issue by Chup123** [DxCx/plugin.video.9anime#150]
It is the only 1080p server for me, is this an issue on their site or a bug in the addon?

**Comment by miasmaejuices** [comment]
@Chup123 - F2 is mostly no longer available on 9anime.  Have you got an example link I can test with?

**Comment by Chup123** [comment]
It still shows up on HunterXHunter (2011) episode 101. But many episodes before did also show server F2

**Comment by miasmaejuices** [comment]
Log snippets:

`
NOTICE: VideoPlayer::OpenFile: https://<gdrive url>
`
`
ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for https://<gdrive url>
`
`
ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
`
`
ERROR: CCurlFile::Open failed with code 403 for https://<gdrive url>
`
`
ERROR: XFILE::CFileCache::Open - failed to open source <https://<gdrive url>
`
`
ERROR: CVideoPlayer::OpenInputStream - error opening [https://<gdrive url>
`

@DxCx - This may be something you will need to look at, it's a little out of my league.  I've posted the relevant errors from the Kodi logs, but that's about all I can find on the subject.

**Comment by DxCx** [comment]
I'll try to take a look over the weekend,
the thing is every time F2 is fixed and working and it is removed 1 week after.. :\

**Comment by marctilalis** [comment]
It would be really nice if you could actually fix the link since it's the only 1080p. Just one question since i'm new. Can't you add like 1 or 2 more 1080p sources?

**Comment by miasmaejuices** [comment]
@marctilalis - the sources are provided by 9anime, not the plugin.  If the sources are available on the 9anime site, then they can be added to the plugin.

@DxCx is not responsible for what sources are available on the 9anime site.

**Comment by marctilalis** [comment]
Oh! Can he fix though the F2 problem?

**Comment by miasmaejuices** [comment]
Hopefully, yes.  But troubleshooting needs to take place first.  Use the
other sources like G2 for now.  Yes it's limited to 720p, but at least it
works. :)
