### ISSUE TITLE
Can't find eligible sources

### ISSUE THREAD

**Issue by JavierZ667** [DxCx/plugin.video.9anime#151]
The app was working fine this afternoon a few hours ago, took a nap and it no longer works. I get an error that states "couldn't find any eligible sources", I've attached an image of the log 

![img_20171124_223721893](https://user-images.githubusercontent.com/28639105/33228120-6a72a636-d168-11e7-896c-48f67cfbe0b3.jpg)

**Comment by JavierZ667** [comment]
According to Reddit the 9anime site itself might be having some issues.

**Comment by lap00zza** [comment]
Similar issue: https://github.com/lap00zza/9anime-Companion/issues/106

If I am able to fix it, I will let you guys know.

**Comment by JoshToshiro** [comment]
Been having the same issue since yesterday. Can’t find eligible sources. Tried different animes and different episodes and got the same response. Also uninstalled and reinstalled again but no luck.

**Comment by JoshToshiro** [comment]
![6847d785-4471-43a9-92a5-bb663889e8c8](https://user-images.githubusercontent.com/33974559/33236961-76f052f8-d232-11e7-976f-05de82e3e902.jpeg)

**Comment by grabberboy** [comment]
@DxCx 
@hoppler 
can i ask the encryption method used in ts variable?

Thanks

**Comment by lap00zza** [comment]
@grabberboy https://github.com/lap00zza/9anime-Companion/issues/106#issuecomment-346991551

**Comment by DxCx** [comment]
hey @lap00zza not sure if `ts` has rot8 or not,
rot8 is used inside the info you get back ("target" for example)

i'll need to debug further to get more info about `ts` but looks like it's not raw as it used to be,
it is now encoded using something that looks like base64 but not base64 (Maybe base64 with custom table?)
also, keep in mind that it might be also just a rotated base64..

**Comment by DxCx** [comment]
So eventually `ts` was base64 as i suspected with a small encoding before it.

version 0.0.23 was released, enjoy.

**Comment by JoshToshiro** [comment]
When I went to update the add-on, it says there aren’t any updates currently available and I still have version 0.0.21 . Should I just uninstall and reinstall again?

**Comment by DxCx** [comment]
You should go to repo and force refresh it..
Right now you get cached results

**Comment by JoshToshiro** [comment]
No luck. I’m not even sure if I did what you said correctly because the only option I saw was “check for updates” . I clicked that option for the repos but I didn’t get an update notification for 9anime. Is there anything else I can do?

**Comment by JoshToshiro** [comment]
Sorry for being a bother.

**Comment by DxCx** [comment]
that might help you
https://www.youtube.com/watch?v=cJtaNyWj5uE

**Comment by JoshToshiro** [comment]
I followed the tips from the video but still haven’t received the update, sorry.

**Comment by JoshToshiro** [comment]
Still having no success. I’ve cleared cache, forced add-on updates, force refresh repo , and force Kodi to close and reopened again and repeated the same process several times. Is anyone else struggling with this? If not, I would appreciate tips or any type of help to get 9anime add-on working for me again.

**Comment by tinymovingparts** [comment]
This rarely happens to me but it does. It should auto update tomorrow if all else fails. For right now go to
1. add ons
2. click the package icon on top right (addons/addon browser)
3. install from repository
4.scroll down to 9anime kodi repository and right click (list button for fire stick remote) 
5. click information -> update
These steps should update it do the latest version.

**Comment by JoshToshiro** [comment]
![4d7e4621-5ee9-4bcf-bca7-2ce1ff62d5b6](https://user-images.githubusercontent.com/33974559/33244950-ed3ee0e0-d2ce-11e7-8228-6b2517b74b11.jpeg)
![Uploading 85F9843D-D83D-41F5-BB97-49497DB60BF4.jpeg…]()

**Comment by JoshToshiro** [comment]
Not sure if those images would help solve the problem.

**Comment by tinymovingparts** [comment]
did the steps not work?

**Comment by JavierZ667** [comment]
Mine updated automatically, didn't have an issues on my end. If all else fails you can try reinstalling both Kodi and 9anime

**Comment by miasmaejuices** [comment]
I'm seeing a lot of 404 errors.  If I didn't know better, I'd say you're not connected to the internet...

**Comment by JoshToshiro** [comment]
I’m connected, I just checked.

**Comment by JoshToshiro** [comment]
And I’m trying those steps you sent up there now.

**Comment by miasmaejuices** [comment]
@JoshToshiro - Those messages you posted have no dates on them, and are not related to the 9anime plugin.  Can you scroll up or down to find more relevant messages?

**Comment by JoshToshiro** [comment]
@miasmaejuices ok.

**Comment by JoshToshiro** [comment]
@tinymovingparts what confuses me is that I don’t have a repository that is specifically named after 9anime. I only see Kodi Add-on repository. I don’t know if downloading 9anime from the .zip file had anything to do with that though.

**Comment by tinymovingparts** [comment]
Yes it does. These steps will only work if you installed the addon from the repository. If you only download the zipfile then your getting the addon alone and will not have auto updates.

**Comment by JoshToshiro** [comment]
@tinymovingparts ohhh ok. So if I uninstall and reinstall from repository, it could work?

**Comment by JoshToshiro** [comment]
Anyone mind telling me how to go about installing 9anime from the repository? 😅 sorry for being a bother.

**Comment by tinymovingparts** [comment]
yes it should. installing the repository will give you the latest addon version and have auto updates. it should be in the instructions area if im not mistaken this page has been heavily revamped since i last saw it.

**Comment by miasmaejuices** [comment]
I have updated the wiki section with the instructions.

**Comment by JoshToshiro** [comment]
@tinymovingparts @miasmaejuices - I will go look for the instructions now.

**Comment by tinymovingparts** [comment]
ok make sure you click the standard option. What kind of device are you using?

**Comment by JoshToshiro** [comment]
@tinymovingparts - ok. And I’m using the Amazon Firestick

**Comment by tinymovingparts** [comment]
let me know if you have any issues following the fire stick steps as they are not up todate for repo and follow the steps of using the master zip file on step 7

**Comment by miasmaejuices** [comment]
@tinymovingparts - would you be willing to help me fix up those steps? I
don't have access to a firestick, so any information would be awesome :)

**Comment by tinymovingparts** [comment]
sure I will clear out my kodi and do a quick run through and journal the steps. do you need it in a pull request?

**Comment by miasmaejuices** [comment]
It would be easier, but if you want to just post the edited steps here, I
can paste them straight into the wiki. I don't mind either way :)

**Comment by JoshToshiro** [comment]
@tinymovingparts @miasmaejuices @JavierZ667 @DxCx - 9anime works fine for me now! Thanks so much for your help guys!! And I followed the steps of the standard installation and it’s working for my Firestick. But I did have to use the downloader app to get the .zip file of he repository for the first step but everything flowed pretty well afterwards. Thanks again guys!

**Comment by JoshToshiro** [comment]
*the

**Comment by tinymovingparts** [comment]
@JoshToshiro awesome to hear you should also have auto updates for the addon so this shouldnt happen again.

@miasmaejuices I will put them on this thread for you to just throw in the wiki.

**Comment by tinymovingparts** [comment]
@miasmaejuices 
	1.	Once opened, enter in the URL https://goo.gl/p9Lde0 then click go
	2.	After the app has finished downloading, close out the app
	3.	Open up Kodi and click on add ons
	4.	Scroll up to the icon of the package and click on it
	5.	Scroll to “install from zip file”
	6.	Scroll down to External Storage and open folder, then open the downloader folder
	7.	Inside the downloader folder find the repo.plugin.video.9anime-0.0.3 file
	8.	Click on the zip file and the repo will install.
	9.	Once installed go to install from repository
	10.	Select '9Anime Kodi Repository'
	11.	Select 'Video add-ons'
	12.	Select '9Anime'

**Comment by miasmaejuices** [comment]
@JoshToshiro - Excellent, great to hear.

@tinymovingparts - No problems.  As soon as you post them, I'll fix it up.  Thanks 👍

**Comment by tinymovingparts** [comment]
@miasmaejuices I have it up also on the android box section you can add

11.	Click on the zip file and the repo will install.
12.	Once installed go to install from repository
13.	Select '9Anime Kodi Repository'
14.	Select 'Video add-ons'
15.	Select '9Anime'

there little steps but details are important for those who arn't familiar with the ins and outs of kodi and addon/ repos

**Comment by miasmaejuices** [comment]
@tinymovingparts - Wiki is updated. Thanks mate, that's awesome.  If ever you're resetting your Fire Stick, screenshots would be really handy as well.  But only if you ever get round to it, no pressure 🥇

**Comment by tinymovingparts** [comment]
@miasmaejuices steps for android box updated steps now that each instruction has its own sections

	1.	On the side tool bar of ES Explorer, scroll down to the newly added dxcx and click it
	2.	scroll down and click the standard installation link
	3.	Click the "here" link on step one
	4.	After it downloads exit out of ES File Explorer
	5.	Open Kodi.
	6.	In Kodi click on addons
	7.	Click the icon that looks like an open package on the top left
	8.	Click install from zip
	9.	Click external storage folder
	10.	Click download folder
	11.	Click repo.plugin.video.9anime-0.0.3 zip file
	12.	Click on the zip file and the repo will install.
	13.	Once installed go to install from repository
	14.	Select '9Anime Kodi Repository'
	15.	Select 'Video add-ons'
	16.	Select '9Anime'

I will try to take some screen shots some time during the week

**Comment by W94545** [comment]
I tried uninstalling then reinstalled with 0.0.3 zip and even force update. Although 9anime app open just fine in Firestick, it still gives me "couldn't find eligible sources" notification.
