### ISSUE TITLE
9anime on Kodi for firestick "cannot find eligible sources" issue

### ISSUE THREAD

**Issue by W94545** [DxCx/plugin.video.9anime#153]
Last night, 9anime worked just fine on firestick but when I woke up this morning, I kept getting "couldn't find eligible sources" messages every time I play a video. So far I've tried everything to troubleshoot, even this method https://github.com/DxCx/plugin.video.9anime/issues/31 and nothing works. May I ask, is the site down?

**Comment by DxCx** [comment]
duplicate of #152
