### ISSUE TITLE
9anime isnt downloading in kodi on raspberry pi

### ISSUE THREAD

**Issue by DjDarkAssassin** [DxCx/plugin.video.9anime#163]
I wanted to download the 9anime plugin on kodi, which I have on my raspberry pi. Since I couldn't use file manager, I just downloaded it on my PC and transfer the zip file to a flash drive and downloaded it from there. Once I go to "Install from repository", there's the 9anime respository, and whenever I try to install it, it says ,"failed to install a dependency". Any help on this or other ways I can download it on my raspberry pi?

**Comment by tinymovingparts** [comment]
Not to familiar with raspberry pi, are you downloading the repository zip file or the master zip file for the addon?

**Comment by DjDarkAssassin** [comment]
Im downloading it from the repository zip file

**Comment by tinymovingparts** [comment]
where do you paste the zip file when you transfer it to the Pi? you dont open the file at all, right?

**Comment by DjDarkAssassin** [comment]
I paste it in a USB flash drive, and yes, I don't open it at all.

**Comment by tinymovingparts** [comment]
If anything I would suggest starting from scratch. Clear your flash drive, re-download the repo zip file on to the flash drive plug it in to the pi (but dont paste it anywhere leave it on flashdrive). Open Kodi, go to install from zip. Navigate through the storages to get to your flash drive storage and find the repo.plugin.video.9anime-0.0.3 zip file. click on it and it should install the repo. after that close out Kodi again just to be on the sure side, remove flash drive, re open kodi. go to install from repository and find the 9anime kodi repo

**Comment by tinymovingparts** [comment]
I failed to mention this re reading the original post, are you using Kodi Krypton?

**Comment by DjDarkAssassin** [comment]
I will test that out right now. Yes, I am using Kodi Krypton.

**Comment by DjDarkAssassin** [comment]
It still fails. Since I have a dual boot which can go from linux (Raspbian) to Kodi, do you think it is better to just download it on raspbian then switch back to Kodi and downloading it using the one I downloaded from Raspbian?

**Comment by tinymovingparts** [comment]
Kinda lost in what you want to try and do. Would it be possible to explain step by step what you are doing and indicate where it fails?

**Comment by DjDarkAssassin** [comment]
First, I download the zip file and paste it in my flash drive, without doing anything. Second, I put the flash drive in my raspberry pi. Third, I go to Add-on browser then go to install from zip file, and click repo.plugin.video.9anime-0.0.3. Third, I go to install from repository, and go to the 9anime repository. Fourth, I go to Video Add-ons in the repository, and click on 9anime, and click install. When I click install, it says download failed, and following that it says failed to install a dependency. It fails when I click install. On the information screen, it says version 0.0.24, if you needed that infomation.

**Comment by tinymovingparts** [comment]
thank you, most useful. the error is when you go into the repo. so after you have installed the zip go...
1. to install from repository
2. 9 anime kodi repository
3. add on repository
4. 9 anime kodi repoistory
once that is all installed and set up the addon you keep installing should work as it has everything it needs from this step that was over looked.

**Comment by miasmaejuices** [comment]
One of the addons had issues installing.  I seem to recall having a similar issue on my RasPI.  If I remember correctly, it was the URLResolver.

The latest version is available here: 

- https://github.com/tvaddonsco/script.module.urlresolver

or here

- https://github.com/kodil/kodil/tree/master/repo/script.module.urlresolver

**Comment by DjDarkAssassin** [comment]
I went on 9anime kodi repoistory, and the only options I had was to update, unistall, and disable. It said enabled so I thought I try to reinstall the addon again, it failed.

**Comment by DjDarkAssassin** [comment]
Ima try to use the links from miasmaejuices to see if those work.

**Comment by tinymovingparts** [comment]
That would probably be best. I don't have a Pi so I can't really get hands on or know any of the exclusive issues such as the one @miasmaejuices mentioned. The best I can do is guess fix along side you.

**Comment by miasmaejuices** [comment]
@DjDarkAssassin - This has been sitting open for a while.  I'll close it down for now, we can re open or start a new bug if the issue arises again.
