### ISSUE TITLE
Amazon Fire / Kodi 9anime addon Autoplay every episode

### ISSUE THREAD

**Issue by musicskypirate** [DxCx/plugin.video.9anime#166]
Currently running the latest builds of Krypton, Supreme Builds Titanium and 9anime but it doesn't autoplay to the next episode nor can I find any options to Queue each episode.

Unsure whether this is already embedded somewhere to do it but I cannot find any option to continuously play a season of anime. The episode just simply ends and I have to manually select the next one. This is from using the Search option and have no tested another way... Although doing my best to give my exact issue. 

Perhaps I'm doing something wrong? Any help is appreciated. I've had a look at previous Closed Issues but none have seemed to resolve.

@DxCx HALP! :)

**Comment by miasmaejuices** [comment]
@musicskypirate - Im pretty certain that this feature is not currently available.

I've added the 'enhancement' label, as it is a function that will need too be added.

@DxCx will have a look and let you know either way.

If you're able to code, you can contribute your own fix for it :)

**Comment by DxCx** [comment]
as far as i remember someone already spoke about auto play and he made it work using kodi functionally only.

I think that if you will change ordering (so latetst episode will be last) and then right click the episode you want to watch and click "Play from here" it will play this episode and auto continue to next one. (You will only need to select source if autoplay is not enabled in options)

Please confirm, if this is working we need to add that to wiki.

**Comment by musicskypirate** [comment]
Heya

Figured out the issue.

If you have "Automatically play video" in the Main Menu Playback Settings it won't ever ask you for "Play from here" in any app.

Turned it off, low and behold the option reappeared.

Case closed!

**Comment by DxCx** [comment]
@miasmaejuices can you please update the wiki to reflect this issue?
I'll reopen the issue and you will close it when it's in the wiki.

**Comment by miasmaejuices** [comment]
No problems @DxCx - I'll do that tonight.

**Comment by DxCx** [comment]
yo @miasmaejuices did you update it ? can we close this?

**Comment by miasmaejuices** [comment]
Sorry, been away over Xmas/New Year.  Will do this ASAP.  Just catching up on work.

**Comment by DxCx** [comment]
No problem at all, thanks :)
Just wanted to make sure this will not just gone

**Comment by miasmaejuices** [comment]
@DxCx - Please forgive my absence.  I took on a 3rd job a little while after Xmas, and have not been able to make it back to continue maintenance of the Wiki.

I would love to, but bills have to be paid, family has to be looked after.

If someone else could help with this, I would be forever grateful.  I'll come back and help the moment I have more free time.
