### ISSUE TITLE
No listings are showing?

### ISSUE THREAD

**Issue by icpryde** [DxCx/plugin.video.9anime#167]
I downloaded the latest version and also cleared the cache and when I click on “latest sub” or “popular sub” or any category for that matter the lists show up empty?

**Comment by XxkingkrowxX** [comment]
I just looked on the 9anime site and their servers are down for maintenance

**Comment by icpryde** [comment]
Ya just noticed that, damn it’s been an hour oh well:(

**Comment by JoshToshiro** [comment]
I was about comment on the same issue until I saw this .

**Comment by JoshToshiro** [comment]
The listings are back up, but I don’t see Server G2 or Server G3 like I was before the listings weren’t showing up.

**Comment by miasmaejuices** [comment]
This may be related to #168 

Working on a patch now.

**Comment by DxCx** [comment]
website was down, now it's working again.
