### ISSUE TITLE
Server G2 and Server G3 Not Showing as Options to Play Episode From

### ISSUE THREAD

**Issue by JoshToshiro** [DxCx/plugin.video.9anime#168]
Before the listings went down, I was able to use both servers and play episodes off each easily. After the maintenance though, I don’t see any of the servers. I’ve tried to see if they appear when I try to watch different animes and different episodes but they’re not available. Are those servers gone ?

**Comment by miasmaejuices** [comment]
Servers G1; G2; and G3 are no longer available via 9anime.

Looks like they scrapped them, and replaced them with G4.

I'm working on a patch for the plugin now.

**Comment by JoshToshiro** [comment]
Alright, cool.

**Comment by miasmaejuices** [comment]
@DxCx - Pull request added to patch Servers.
