### ISSUE TITLE
No shows, only .. showing under any menu

### ISSUE THREAD

**Issue by Royster-77** [DxCx/plugin.video.9anime#172]
I've tried from my phone and on my fire TV stick, checked shortcuts to shows I've put in favourites, tried a search, tried popular and recent dubs and subs but can't find anything listed. On krypton 17.6 and 9anime plugin 0.0.26. the site seems to be running fine

**Comment by tinymovingparts** [comment]
It looks like the site has had a redesign. The new way the site runs is probably what is effecting the addon from pulling the information it needs to get the video links and page directories. Until DxCx or others can find a work around the new site, the add on is pretty much broken.

**Comment by Royster-77** [comment]
At least there's a browser for fire TV now so I can watch videos direct on the site

**Comment by tinymovingparts** [comment]
Which browser did you use? I tried Firefox and it didn’t work.

**Comment by Royster-77** [comment]
Using silk as you can ignore the popups, works fine

**Comment by tinymovingparts** [comment]
It’ll have to do till the add on gets back up and running. Everything works on silk but I think the side adds slow down loading the 1080 videos for me.

**Comment by DxCx** [comment]
the site was reconstructed so ill need to rebuild some parts to
make it work again..
Probably over the weekend ill release a new version

**Comment by Dranzera** [comment]
I have the samw issue in Kodi I can see my favorites but when I click on them it comes up empty. I can watch it on the PS4 website though.

**Comment by EasyFireTV** [comment]
DxCx Awesome! Looking forward to it, and  Thank you for your great add on!

**Comment by DxCx** [comment]
version 0.0.27 just released, enjoy. =)

**Comment by Dranzera** [comment]
Thanks so much it works happy new year ??.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Royster-77** [comment]
Awesome, thanks so much

**Comment by EasyFireTV** [comment]
Awesome thank you! Can't wait to check it out when I get home

**Comment by geedydog** [comment]
Do you have a method of getting it onto the Xbox one?

**Comment by DxCx** [comment]
i don't own an xbox one so i cannot support that, sorry.
if someone has xbox one and willing to provide help, please do and we will add it to wiki
