### ISSUE TITLE
Video add-ons folder empty

### ISSUE THREAD

**Issue by Bitcross** [DxCx/plugin.video.9anime#175]
Trying to install the add-on and the repo installs just fine, but the video add-on folder in the repo is empty.

**Comment by DxCx** [comment]
Which version are you getting?

**Comment by Bitcross** [comment]
0.0.3 for the repo, that's what the instructions show for firestick

**Comment by tinymovingparts** [comment]
I’ll check this out in a bit I just used the repo on a fire stick Wednesday and it all worked fine.

**Comment by tinymovingparts** [comment]
Video add on was in video folder

**Comment by AFriendlyEmo** [comment]
the Current repo is reading 0.0.3 but the add on still reads at 0.26 not 27

**Comment by tinymovingparts** [comment]
Right click to manual update the repo this will update the video add on if auto update hasn’t already

**Comment by ThienJP** [comment]
yes had to update repo as well. after that 9anime auto updated itself.
but still not working for me. error upon scannin mirrors.

**Comment by DxCx** [comment]
hey @ThienJP, is that version 0.0.27?

**Comment by ThienJP** [comment]
@DxCx hey there, yes it is.

**Comment by agrusa927** [comment]
having same issue just downloaded today says version 0.0.1

**Comment by tinymovingparts** [comment]
You’ll have to manual update the repo. The current version is 0.0.3. If your using firestick auto update usually happens the day after you download.

**Comment by agrusa927** [comment]
i am using an android box,  only gives me the option of 1.0.2 nothing newer

**Comment by tinymovingparts** [comment]
There isn’t a version 1.0.2?
What page did you download the repo from? And are you using a current version of kodi( 17.1-17.6)

**Comment by agrusa927** [comment]
I downloaded it from Cypher,   I am running Kodi 17.6

**Comment by tinymovingparts** [comment]
Cypher is a duplicate/ripoff of this add on please refer to the bottom of the readme page. It’s best you uninstall that repo and proceed with the instructions for what ever platform you are using under the readme page.

**Comment by agrusa927** [comment]
I did not realize that I have deleted it and trying to download from github but it only comes up blank  or..

**Comment by tinymovingparts** [comment]
Ok after uninstalling the cypher repo Follow the instructions for Android box. The link is found on the readme page. Once the page is opened in es file explorer use the standard installation page “here” link found on the read me page to download the repo.

**Comment by agrusa927** [comment]
that is what I am attempting to do when I choose install from zip file it opens the window with no files to choose from
![pzut9485 1](https://user-images.githubusercontent.com/35203417/34655565-97e0694c-f403-11e7-883a-0b37b63082b2.JPG)

**Comment by tinymovingparts** [comment]
Would it be possible for you to write out what your doing step by step? This would allow me to get the best idea of where things are going wrong.

**Comment by agrusa927** [comment]
I am running Supremebuilds Titanium version 3.07    Kodi 17.6 on a generic Android Box

under Tab FILE MANAGER: I go to "ADD SOURCE"
that brings up a window I type in the Path https://github.com/dxcx/plugin.video.9anime
I Leave the "NAME" as it is autopopulated as " PLUGIN.VIDEO.9ANIME"
I then click "OK"
I then back out to the "HOME SCREEN" and Click on "SETTINGS"
this brings up the "SETTINGS WINDOW"
I Scroll down to "ADD ONS" and click
this brings up the "ADD ON BROWSER" window and I choose "INSTALL FROM ZIP FILE"
this opens the directory where I choose " PLUGIN.VIDEO.9ANIME" 
this opens "INSTALL FROM ZIP FILE"  and there are no files to select in this folder

**Comment by tinymovingparts** [comment]
Your main issue is that you are not following any of the instructions. Please follow the instructions found on the readme from the readme page under android box instructions. You do not use file manager at all for this plugin. It’s important that you use es file manger from play store then downloads the repo onto your device.

**Comment by agrusa927** [comment]
still no luck, I do all of the steps until I open "dxcx"  and I get a blank  window, Nothing to open or execute on, I have done this three times with the same results, I guess its just not meant to be

**Comment by tinymovingparts** [comment]
I’m sure we can figure this out. Can you tell me what you are using as the dxcx path in es file explorer?

**Comment by agrusa927** [comment]
https;//github.com/dxcx/plugin.video.9anime

**Comment by agrusa927** [comment]
I truly appreciate your time and patience with me in helping on this matter

**Comment by tinymovingparts** [comment]
Your using ; 
When it should be :

https://github.com/DxCx/plugin.video.9anime

**Comment by tinymovingparts** [comment]
Try that out and let me know how it goes. It will take you to the home page from there go to readme, then standard install instructions then click the here link the repo will download once downloaded exit out of es file explorer and follow the step when your in kodi

**Comment by tinymovingparts** [comment]
@DxCx  or @miasmaejuices 
now that instructions are in the wiki can we please make a slight change in the android box instructions?
In the install on Android box under requirements section now that wiki pages are implmented the path for es file explorer should be " https://github.com/DxCx/plugin.video.9anime/wiki/Standard-Installation "

there for can it be change to say...

Requirements:
ES File Explorer available on the Google Play Store
In ES File Explorer scroll on the sidetool bar to favorites click to open dropdown menu. choose ADD, In the two options enter in; Path: https://github.com/DxCx/plugin.video.9anime/wiki/Standard-Installation Name: dxcx

this change will allow for smother navigation. currently the path will take the user to the home page where they would have to figure out that they have to go to readme page then standard instructions page to get the repo link. This will make the process alot smother for android users.

**Comment by DxCx** [comment]
@miasmaejuices can you please take care of wiki update & close this issue after?
