### ISSUE TITLE
9anime 0.0.27 add-on for Kodi on Firestick

### ISSUE THREAD

**Issue by W94545** [DxCx/plugin.video.9anime#177]
Heard 9anime had a update recently. I tried manually updating it but still defaults 0.0.26 version. Is there any way I could acquire the new 0.0.27 version on my firestick?

**Comment by DxCx** [comment]
Well kodi has cacheing on repos, and im not sure how much time it takes to
refresh it, repo has versiob 0.0.27 already, you can try manually update
the repo to get the update..

**Comment by W94545** [comment]
Sorry for late reply. Just got home and refreshed repo and everything works. Thanks!
