### ISSUE TITLE
[REQ] Adding a switch to change viewtype "globally"

### ISSUE THREAD

**Issue by GuiltyCrowDx** [DxCx/plugin.video.9anime#178]
If I open the video-add-on and go for example into the "recent subbed"-folder the dafault viewtype is list. Maybe someone can add a switch in the configuration so we can change the default viewtype into wall or infowall and so on. I know there is a way to change the viewtype for each page but for an overall better experience this would be very nice.

**Comment by ypawar159** [comment]
I would also like to know how to do this in code, need the same for other addon I am working on.

**Comment by DxCx** [comment]
Ive researched this a year or two back,
What ive found back then is thats a kodi selection and nothing i can really change in code,
If someone can provide more info about this ill be glad

**Comment by L2501** [comment]
you can set it like this
```
    xbmcplugin.addDirectoryItems()
    xbmc.executebuiltin('Container.SetViewMode({0})'.format(id))
    xbmcplugin.endOfDirectory()
```

but the problem is that every skin has their own viewtype ids, for example viewtype 500 can mean different views on other skins

**Comment by DxCx** [comment]
So that will have to be a settings of (numerical) default viewtype i guess
