### ISSUE TITLE
9Anime, No Shows!!!

### ISSUE THREAD

**Issue by player7000000** [DxCx/plugin.video.9anime#179]
It started Yesterday 1/16/18, rapid video was not loading anymore, but when I went to sleep it started to work again. When I woke up today 1/17/18 , I tried to play an anime and nothing popped up on the episode list. I went to the Recent SUBS and DUBS no show popped up. I tried over and over again, but no shows! I think 9anime went under another redesign and it needs a new path to the servers? Please help. I'm on Firestick.

**Comment by KaSp3r1** [comment]
Yea same here it suxs. Cause a lot of the anime sites have been shut down on kodi and I finally found this one a few days ago and was happy that it worked. Now it's down too. I hope it doesn't stay down.

**Comment by KaSp3r1** [comment]
Actually sorry player I just checked and it's back up and running. Maybe it was just down for a while give it a check now.

**Comment by player7000000** [comment]
Just started running again. Maybe it was just down?!? I'm going to leave it open for DxCx to see the issue, if it was just down the cool but not sure if it might have other problems too.

**Comment by DxCx** [comment]
Yep, probably was down.. it happens from time to time..
Since there are no logs i also cannot verify but jext time you can just open browser for 9anime website and check if its up
