### ISSUE TITLE
9anime not working on 16.1

### ISSUE THREAD

**Issue by L4MI4** [DxCx/plugin.video.9anime#18]
Sorry if this has been addressed before, but me and a friend on reddit have been experiencing the same problem. The plugin stopped working on 16.1 4-5 days ago. Just before it was updated. Also, installing the newer version nets the same error. Choosing any option like Latest or Genres or  Newest anime generates a 9anime error. Seems to be a python related issue. Im posting the relevant log details. Here-
https://pastebin.com/DrJiFn6e

**Comment by DxCx** [comment]
Hey @L4MI4
Are you using latest code at master?

**Comment by L4MI4** [comment]
Hi. Kind of a noob so not sure what you mean. If you mean using the latest zip, then yes, I am.

**Comment by L4MI4** [comment]
Also, would like to share that it is working fine in Krypton which i have in my other device but not on jarvis. I can't update that 16.1 to 17.1 due to it only having kitkat. And the other friend has a similar situation, but his 17.1 is unstable as hell. So only stuck on 16.1. Was working perfectly fine till the day I think the openload problem resurfaced. When the newest zip was released, still didn't work.

**Comment by DxCx** [comment]
well,
"An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS"
that's a pure kodi issue,
Kodi started to support SNI (SSL Extension which 9anime uses) only since kodi 17..
ref: http://trac.kodi.tv/ticket/15883

**Comment by L4MI4** [comment]
Ah. Thanks for clearing that up. So I guess I have to watch it on another device. Will share it to the other redditor too. Thanks:) Should I close it now?

**Comment by L4MI4** [comment]
One more thing. The other redditor has I think some other problem now. His log says error:inputstream: error opening plugin instead like mine. One thing is very weird though, why did it stop working just a few days ago? Did 9anime started using SNI just now?

**Comment by DxCx** [comment]
Nope, but they started force ssl (through the link they are referring to) On the watch page..

**Comment by L4MI4** [comment]
Ughh.. Well then I guess I'm closing the issue. Thanks for looking into the issue.
