### ISSUE TITLE
9Anime on iOS

### ISSUE THREAD

**Issue by Alteridin** [DxCx/plugin.video.9anime#180]
So, I can download the zip file just fine. But on Kodi for iOS there is no way to find it. Am I missing another way to do this? I will say my iPad is not jailbroken. I have developer access so I can use the app without that problem. Is there a link to use through Kodi that will allow me to install the zip that way?

**Comment by DxCx** [comment]
Never tried it on jailbroken iOS device since i dont own one.. cant help much but will leave it open for others to share thier wisdom

**Comment by JaeFr0st** [comment]
Try using iFunBox or iFile. iFile if you’re jailbroken or iFunBox if you’re not. Those will give you riot access to your phone and you can find the zip file. Not sure if that’s what you’re looking for.

**Comment by JaeFr0st** [comment]
Try using iFunBox or iFile. iFile if you’re jailbroken or iFunBox if you’re not. Those will give you root access to your phone and you can find the zip file. Not sure if that’s what you’re looking for.

**Comment by Logey** [comment]
The way that I installed it on my iPhone was using the Indigo addon and pasting the link to the repo zip in the menu that says "install from zip file".

The Git Browser in the Indigo addon would be easier but it never works for me for some reason.

**Comment by Alteridin** [comment]
Thanks guys! I appreciate the input! I ended up moving to another addon. I understand the developers issue with not having access to iOS so I don’t fault anyone there. Hopefully this will spark some work for anyone else who might want to try this out on an iOS device! Kupos for the addon though!
