### ISSUE TITLE
9anime not working? 

### ISSUE THREAD

**Issue by hax0122** [DxCx/plugin.video.9anime#182]
Checked the site and it does load, albeit it is rather slow. But on Kodi it gets as far as the main menu but finds nothing when you search or even just view popular shows.

**Comment by JaeFr0st** [comment]
I am having the same issue. I was just watching a show and after it was done, I went to watch another and all I keep getting is Anime9 Error check logs. I check logs nothing is showing in my logs though.

**Comment by player7000000** [comment]
This happens every once in a while I posted the same issue a while ago it gets fixed on and off. I don't have any anime's right now either :(

**Comment by JaeFr0st** [comment]
This sucks because I was really getting into this anime that looks hella good. Hopefully it will be fixed.

**Comment by player7000000** [comment]
I'm trying to catch up on Dragon Ball Super

**Comment by JaeFr0st** [comment]
Nice. I caught up this past Sunday. Just an update. The add on is not the issue. It’s the server itself. I was able to get on the home page of 9Anime but when I searched for a show it said Error 502 Bad Gateway. Now you can’t access the site at all. Hopefully it will be fixed. Nothing DxCx can do at this point. It has to be fixed by 9Anime themselves.

**Comment by JaeFr0st** [comment]
So you might want to close this issue out and actually wait for 9Anime to fix it on their end. Once it’s fixed and if there’s still an issue with the add on, then resubmit issue.

**Comment by player7000000** [comment]
Nice, thanks for the heads up!

**Comment by RillonDodgers** [comment]
Just to confirm what @JaeFr0st was saying, I went to the 9anime website and it says that they're down for maintenance. I was thinking maybe the ip changed again.

**Comment by player7000000** [comment]
Cool cool! I've been using crunchyroll for now.... Hate the ads and quality sometime but it works. I suggest GoGo Anime for anyone using the silk browser on Firestick. Also just the Crunchy roll app

**Comment by hax0122** [comment]
Guess they were just in the process of shitting the bed when I checked originally. As long as it's the server that's screwed up, no point in keeping this issue open for now. Thanks all!

**Comment by JaeFr0st** [comment]
Thanks @player7000000. I’ll definitely give those a try. Personally I wish DxCx could make Watch Cartoon Online work. I like that so much because you just click and it plays right away. No need to select anything. Well take care everyone.
