### ISSUE TITLE
TLD option

### ISSUE THREAD

**Issue by disconsented** [DxCx/plugin.video.9anime#184]
With how often the site rotates through TLD's being able to set it ourselves would really help in minimising the downtime.

**Comment by DxCx** [comment]
TLD?

**Comment by disconsented** [comment]
Being able to swap through 9anime.ch/.is etc

**Comment by DxCx** [comment]
yeah, that's something i wanted to add (Option to replace url under settings)
but didn't had a time to get into.
probably next time domain is broken i'll do that (if anyone else didn't contribute it until then)

**Comment by ypawar159** [comment]
Created pull request for this #206 .
Ignore the aria2c changes for now. Still newbie with git and development so that change got into the branch.
