### ISSUE TITLE
Integration with Metalliq

### ISSUE THREAD

**Issue by Sol-Illadan** [DxCx/plugin.video.9anime#186]
Hi,

I want to add anime series to Kodi library using Metallic (or normal). How can I do so ?

**Comment by DxCx** [comment]
hey @Sol-Illadan 

this is first time i'm hearing about MetalliQ but just found a quick video that shows what it is.
looks like MetalliQ needs to add support for 9anime addon and not the opposite,
if any changes here needed to support it i don't mind evaluate and edit,
but looks like initial support needs to come from MetalliQ side.
