### ISSUE TITLE
Request fix for watchcartoononline addon

### ISSUE THREAD

**Issue by daniel-ntl** [DxCx/plugin.video.9anime#188]
hello sir, fyi the watchcartoononline addon is dead since des 2017, and nobody would fix the play error, if you could take alook and fix this addon, it would be great, because before it works in jarvis 16.1, thx again man.

**Comment by JaeFr0st** [comment]
I would love to see this add-on brought back to life. This add-on is amazing. I love the fact there are no sources to pick from. You just hit play and it plays right away. I really would like DxCx to take a look at this and perhaps make this work. 9anime is amazing but there are too many frequent issues with it lately.

**Comment by player7000000** [comment]
Watch Cartoons is amazing and I would also love to see it back. I would use it for anime and regular cartoons!

**Comment by JaeFr0st** [comment]
Agreed player7000000

**Comment by JaeFr0st** [comment]
I’m willing to donate some money to DxCx to make this happen. You need a PayPal though. Especially since a lot of people don’t have bitcoins or ethereum. Also some banks are now blocking purchases bitcoins and any other digital currency. My bank won’t allow me to buy any digital currency.

**Comment by ypawar159** [comment]
Hey guys,
I would like to try to revive that addon.
Can anyone point me to it's source code?

**Comment by ypawar159** [comment]
Guys Good News,
Just out of curiosity I got some code for that plugin from the Internet.
Guess what, I am able to get the video link with available quality as well manually.
Just need to code it in python.
May make new addon from scratch also.
Let me know what you all think.

**Comment by JaeFr0st** [comment]
Holy shit I must be dreaming. I hope this is a reality. I’m stoked as hell now 😂

**Comment by daniel-ntl** [comment]
ypawar159, wow thats great, so could you make patch for the WCO or where i could download the zip file?

**Comment by daniel-ntl** [comment]
to all here is the working WCO, works in kodi frodo and jarvis, thx to kodibear,
 https://github.com/kodibear/plugin.video.watchcartoononline,
case closed

**Comment by JaeFr0st** [comment]
@ypawar159  how’s it going? Have you finished it yet?

**Comment by ypawar159** [comment]
@JaeFr0st,
As the issue was closed I thought there isn't any need to do so.
But I will give it a try this weekend if get enough time. Will post github link to the project here.

**Comment by JaeFr0st** [comment]
The owner of this thread closed the issue but just because it’s closed doesn’t mean it’s been resolved because it’s not. That info he sent does not work for Krypton at all.

**Comment by ypawar159** [comment]
Wait till weekend. Will do at least basic add-on for it.

**Comment by JaeFr0st** [comment]
Ok no problem. Thanks

**Comment by ypawar159** [comment]
Would you like to have download functionality in it? I could add support for aria2. Or any other if API available.

**Comment by JaeFr0st** [comment]
Yea that sounds cool. I wouldn’t mind having that feature at all.

**Comment by tehandeh** [comment]
My only gripe has always been it's lack of images for grid or icon views.
If someone could address that I'd love them forever haha

**Comment by ypawar159** [comment]
@tehandeh
The lack of images is due to the way the WCO website is designed. There are no thumbnails for anime lists in website. There could be the possibility two fetch the thumbnails from scraping site or any other website from internet.

**Comment by ypawar159** [comment]
Hi All,
Checkout my new addon : https://github.com/ypawar159/plugin.video.wco

**Comment by JaeFr0st** [comment]
Hmmm. Not working after I installed it. In fact when I installed it, it doesn’t show up. I hope this is not some Trojan horse.

**Comment by ypawar159** [comment]
@JaeFr0st 
Please open an issue in that repo.
I wonder how you installed it. It worked fine at my setup.
