### ISSUE TITLE
add myanimelist intergration

### ISSUE THREAD

**Issue by Chup123** [DxCx/plugin.video.9anime#192]
Could you add the feature that we can login to myanimelist to sync my anime with that. I watch on multiple devices and this will make things so much easier

**Comment by ypawar159** [comment]
Can we get more info on this.

**Comment by Chup123** [comment]
I use trakt to track my watched movies and tv shows and myanimelist to track anime. It is much simpler to keep track of anime in myanimelist than it is in trakt.

**Comment by ypawar159** [comment]
Have you tried this addon:
https://kodi.wiki/view/Add-on:XBMAL
