### ISSUE TITLE
Adaption from urlresolver to resolveurl

### ISSUE THREAD

**Issue by pjcanales** [DxCx/plugin.video.9anime#193]
Hello was wondering if your add-on had been change from how it gathers link since last week about all add-ons has switch from  urlresolver to resolveurl.

**Comment by pjcanales** [comment]
Ok i just tested it from authorizing first the new resolveurl and it didn't work with your addon. However when I tried the urlresolver it worked. Can you please take the appropriate actions when you have time for it to work with resolveurl  from jsergio

**Comment by pjcanales** [comment]
Here link to his github for more information.
https://github.com/jsergio123

**Comment by pjcanales** [comment]
This is an issue that may be reported alot here since all the popular add-ons has moved over to it. Hopefully you are able to read this and it doesn't get buried under other complaints that are basically the same issue repeated.

**Comment by DxCx** [comment]
hey @pjcanales let's start over,
right now, urlresolver, is used only when actually plaing openload link,
and is installed from 9anime repo itself,
so im really not sure what other addons has to do with that,
also, i don't think i understand your problem, so now, how can i help?

**Comment by pjcanales** [comment]
Ok other add-ons are using the popular, more updated version of resolveurl which is a fork of urlresolver which gets way more update changes. It being maintain by jsergio. So to clarify a majority of users ain't using urlresolver  but are now using "resolverurl". This could be why a majority of recent issues are being opened. Again here the site of jsergio new resolveurl github to make the necessary changes for your add-on to use "resolveurl' instead of urlresolver. https://github.com/jsergio123

**Comment by pjcanales** [comment]
I ask a friend the same question about dofference and he went into more detail. Here is his reponse.  1.  resolveurl is maintained by jsergio.  2. urlresolver was not maintained at all for a while but is now maintained by tvaddons.  Some  in the community don't have a lot of confidence right now in TVA staying around given its legal position.  3.  development/maintenance of resoveurl is more active, though I haven't visited the git repository or looked at the change log to verify myself. 4.  Many addons have already changed.  In practice this means that depending on your installed addons you will need both for at least a while.

**Comment by DxCx** [comment]
well, as long as urlresolver works as it is now, i don't see any real reason to replace it..
if it will stop working, or i'll see a real benfit from moveing from it, i'll do it.
we don't need any active maintaince as it is used just for openload, and it just works.
