### ISSUE TITLE
two issue!!!

### ISSUE THREAD

**Issue by zenakuadevent** [DxCx/plugin.video.9anime#194]
the first one is that i updated to 0.0.28 on my fire stick tv
and some video do load, while some say couldn't find the source.

the second issue is that my cousin fire stick TV doesn't give update to the newest version it always says .27

**Comment by DxCx** [comment]
Hey, please provide a video that does not load so i can test it.

Regarding your cousin, kodi had repo cacheig, waiting will timeout eventually and he will get the update, or he can force refresh the repo to get 0.0.28 update

**Comment by markyirish40** [comment]
When loading video says cant find sources has it been fixed

**Comment by markyirish40** [comment]
I unstall 9anime and refresh repo

**Comment by pjcanales** [comment]
Markyirish40 are you a real debrid subscriber?

**Comment by markyirish40** [comment]
Yes i am

**Comment by pjcanales** [comment]
Ok your having the same issue with me. Pretty sure your using the new resolveurl from jsergio instead of urlresolver from tvaddons. We are using the new link resolver but 9anime add-on hasn't been updated for new resolver. I opened the issue but if you want you can add to my open ticket issue so he see others are facing same issue as I am.

**Comment by DxCx** [comment]
I am providing a good working urlresolver plugin within my repo, also, if
thats broken, only openload shouldnt work...
Did you verify your are getting version 0.0.28?

**Comment by pjcanales** [comment]
I'm on version .28 and none of my links are working with resolveurl. I only use openload and now that seems to be broken with using your add-on with urlresolver. I'm guessing either everyone using the pairing method which offer free 4 hours streaming but for us who use realdebrid with the latest resolveurl it it's going to be broken. Even tvaddons says they were going to use resolveurl but nobody trust them since they appear to be shady. Hopefully you do decide to make the change to resolveurl.

**Comment by tinymovingparts** [comment]
@pjcanales all the links appear to be working fine right now as far as I know. I also tend to use Rapid more then openload links. If you don't mind me asking did you download just the addon or did you dl the repo file and get the addon from there?

**Comment by pjcanales** [comment]
@tinymovingparts. I downloaded the repo from github.  I'm on version .28 and my resolver is resolverurl which is the fork of urlresolver but with way more changes and improvement thanks to jsergio amazing talent.

**Comment by tinymovingparts** [comment]
@pjcanales and the links are still broken? that is interesting. Have you tried the website to see if their links are in working order. I know some of the newer stuff that comes out weekly are limited right now and there are no working links outside of mycloud which dosn't seem to load. But that would be on their end not the addon's. do you have another device that you could test using urlresolver?

**Comment by pjcanales** [comment]
@tinymovingparts  i think you are misunderstanding me. On the website they are working. But  the add-on  is using a different resolver than the popular one.

**Comment by zenakuadevent** [comment]
like the new episode of seven deadly sin episode 5 wont load. i know the recent one piece works but i havnt tried other ones

**Comment by Antiriver13** [comment]
Try a clean install

**Comment by zenakuadevent** [comment]
@Antiriver13 whats a clean install?

**Comment by Antiriver13** [comment]
Uninstall the addon and install the fresh updated version

**Comment by wienergunz** [comment]
#197 @
I've tried a fresh install, manual update to .28. I can now get the source to verify but all the sources come up with the dreaded pair message.
- 

- [ ] [1. ](`

> _url_

`)

**Comment by wienergunz** [comment]
Got it. Nm. Thank you

**Comment by DxCx** [comment]
do you have all servers enabled under settings?
it will autoplay only if there is just 1 option to choose from..

**Comment by wienergunz** [comment]
All sources are turned on and auto play is turned off. Does this on every play request on every episode over multiple series.i tried Dragon ball super, fairy tail, bleach, naruto

**Comment by DxCx** [comment]
Can you enable debug logging, try to play an epsisode and uplod logs here?

**Comment by wienergunz** [comment]
Think I solved it on the credit thread. It finally updated but had that pair message. I figured out you can pair your fire stick with the es explorer app. Works great. Had a few glint hey episodes. Episodes out of order. But no big deal stuff. For as vast and smooth as it is it could kick my dog and I wouldn't be upset.
