### ISSUE TITLE
No sources loading

### ISSUE THREAD

**Issue by ratchetchan** [DxCx/plugin.video.9anime#197]
Tried the addon today and nothing plays. Search works perfectly, but not one episode even returns sources, not even Dragon Ball Super, the most popular series on there right now. What's going on? I've reinstalled Kodi, and uninstalled and reinstalled the addon.

**Comment by ypawar159** [comment]
Try different settings:
General->Display episodes as->List
When I put it to Directory I get no sources.

**Comment by ypawar159** [comment]
@ratchetchan ,
Have you tried that settings change?.
Is your issue resolved?

**Comment by ypawar159** [comment]
@ratchetchan ,
Let us know if issue is resolved. 
And please close this issue if yes.

**Comment by DxCx** [comment]
Closed due to inactivity.
