### ISSUE TITLE
The sources are not working

### ISSUE THREAD

**Issue by mattjoker3** [DxCx/plugin.video.9anime#198]
Ok so i when i get to the show I'm about to watch i click it and it gives me only openload and it says i have to pair it with my device, it doesnt even give me the option to use rapidvideo or mycloud, but when i took out openload as a source choice it says i have no eligible sources at all

**Comment by chrissyt29** [comment]
Same thing is happening with me

**Comment by DxCx** [comment]
please try version 0.0.29 and report :)

**Comment by LiquidR1987** [comment]
I updated to the new version. All the source files are visible, BUT, when I select RapidVideo kodi gives the error that there are not any eligible sources. So in conclusion: it works, but it doesn't work at the same time.

**Comment by DxCx** [comment]
@LiquidR1987 can you please open a different issue?
also, repeat the process with kodi log turned on, and attach kodi.log file please
