### ISSUE TITLE
working for older versions of kodi?

### ISSUE THREAD

**Issue by ISSUES999** [DxCx/plugin.video.9anime#20]
can it work for kodi 14/15/16 ?????
can you make this changes ??
thanks , have a nice day.!!

**Comment by DxCx** [comment]
Hey

Kodi < 17 doesnt support SSL SNI extention which is required for accessing anime9 servers.

The only 'real' solution is to create a proxy server which the plugin will work with, however this will require monthly donations and i really dont want to charge people for using the plugin.. :/

**Comment by DxCx** [comment]
No response for 2 weeks.
