### ISSUE TITLE
It doesnt work for me 

### ISSUE THREAD

**Issue by tugkan98** [DxCx/plugin.video.9anime#21]
Hello. When I click lates, genres , newest or search it says error.
I got the log. Maybe you can help.
https://ares-project.uk/logupload/log.php?id=1544886

**Comment by DxCx** [comment]
Hey, 
this is the issue:
`SNIMissingWarning: An HTTPS request has been made, but the SNI`

for more info, look at the duplicate #20,
I'm gonna close this as this is duplicate but feel free to response =)
