### ISSUE TITLE
Url resolver broken

### ISSUE THREAD

**Issue by pjcanales** [DxCx/plugin.video.9anime#214]
Hello just to let you know urlresolver got updated yesterday and now everything is broken in other add-ons including this on. I suggest moving over to resolveurl since it got update and all other add-ons work.

**Comment by pjcanales** [comment]
I could be wrong though. I'm trying to watch dragon ball super dubbed latest episode openload link

**Comment by Apex90** [comment]
Hi, I can also confirm this problem, when I click on an episode to watch in the app, the app goes to retrieve the links and then freezes.

**Comment by pjcanales** [comment]
Nevermind they push an update which is working now.
