### ISSUE TITLE
Add Real-Debrid Functionality

### ISSUE THREAD

**Issue by MenaceFtV** [DxCx/plugin.video.9anime#219]
Can we get RD functionality?

**Comment by pjcanales** [comment]
I think that person means to have the function to download it. For example. On the episode when you bring up the option to either save it to favorite some other add-ons have th option in there to download the show or movie.

**Comment by FighterBoyZ** [comment]
Real debrid is  service that provides high quality links. Whether you are streaming or downloading.

**Comment by ruegnueg** [comment]
well it already works with the 9anime addon if you configured rd in the urlresolver. no pairing or captcha on sources from 9anime like streamango openload rapidvideo....
