### ISSUE TITLE
9 anime kodi not working. 

### ISSUE THREAD

**Issue by xanergy** [DxCx/plugin.video.9anime#22]
Whenever I try to load an anime it says too check the log for error or issues. Please help all my other kodi add-ons work perfectly. Thanks for the help.

**Comment by DxCx** [comment]
which kodi version are you using?
can you provide some logs?
i've watched an episode and it worked totally fine...
also, was it working there before?

**Comment by xanergy** [comment]
Im using krypton on fire tv kodi17. 0. I have no idea how to find the logs but I would provide them if I can. And yes it was working before perfectly fine.

**Comment by blunttedsmurf** [comment]
Xanergy check the version 9anime you are using. I was using the first version and got the same message. After installing version 2, everything works.

**Comment by xanergy** [comment]
How do I install version 2? I have updated the most i can. Do I have to reinstall and if i do can u provide the download link?

**Comment by DxCx** [comment]
hi @xanergy ,
can you try completely remove the addon from your kodi and reinstall the latest zip:
https://github.com/DxCx/plugin.video.9anime/archive/master.zip?

**Comment by xanergy** [comment]
Thank you guys for the help will try when I get home.

**Comment by DxCx** [comment]
thanks, please let me know how it goes :)

**Comment by xanergy** [comment]
Ok I did not change a single thing and it started working again. Thanks for the help and sorry for the trouble I still have no idea what the problem was, again sorry for the inconvenience. The problem was probably just do to my ignorance or something.

**Comment by xanergy** [comment]
Ok well it just decides when it wants to work right after watching am episode it gave me am error again on kodi fire tv fml.

**Comment by DxCx** [comment]
well, sometimes when 9anime servers are flooded they take down sources..
then you might have no sources errors at some times of the day.

**Comment by xanergy** [comment]
For most of the day those sources are down :(

**Comment by DxCx** [comment]
not here, at least not on my timezone when i watch..

anyway, there are some things i need to fix to make it be able to reach more sources
but it will take me some time to get to it.. at the moment only 1 source out of the 3 possible is reachable until i have time for it unfortunately..

if it cheers you up i really want to fix it since i want better sources too you know

**Comment by kaleo19** [comment]
9anime isn’t working it won’t show a list or anything just the to dots

**Comment by tinymovingparts** [comment]
There was some site restructure. DxCx will be looking into this when he gets the chance.
