### ISSUE TITLE
9anime

### ISSUE THREAD

**Issue by joshlsmith** [DxCx/plugin.video.9anime#225]
When i click recent subbed or any of them no anime is popping up at all i have it where it updates automatically been like this for a few days

**Comment by cbizzle14** [comment]
So there was an issue over the past few days and a fix just came out. You can install it yourself or wait for the update to hit. My issue is on the new kodi Leia, 9anime automatically updated but on my other kodi which is Krypton, there is no update available

**Comment by cbizzle14** [comment]
Scratch that. I had to manually press check for updates on the repo and it found the update. I usually never have to do that. Try that and 9anime should be working for you

**Comment by DxCx** [comment]
Thanks @cbizzle14 yeah a fix is already out and you should get it with kodi  updater.

**Comment by dgaubatz313** [comment]
Updating didn't work for me. When i tried to update the repository always said version 0.0.3 but when i went into the repository it said 0.0.29 and never found the update.

What did work for me is i went to downloader on my Fire TV and entered this url: https://github.com/SwagOtaku/plugin.video.9anime/archive/SwagOtaku-Plot.zip  It is case sensitive, if you don't have the parts capitalized that are supposed to be capitalized then it will return a error. Once you download this on downloader click done and open kodi then go to addons and click the box icon on the top then click install from zip file then click external storage and click the one that you downloaded from Swag Otaku and 9anime should work after that.

**Comment by DxCx** [comment]
@dgaubatz313 sometimes kodi has cacheing issues..
you should see version 0.0.30, if you don't right-click, check for updates should work (Restart kodi first)
in case you want to update manually, you can download the following zip: https://github.com/DxCx/repo.plugin.video.9anime/raw/master/plugin.video.9anime/plugin.video.9anime-0.0.30.zip

**Comment by dgaubatz313** [comment]
@DxCx I don't know what it was. On my firetv i would go to 9anime then click update and it would only show 0.0.29. I completely reinstalled kodi to see if that would work and it didn't. Then i reinstalled the original zip file and that didn't work. I'm sure if i used your manual link it would work, but what i mentioned above already worked.

Thanks for this addon.

**Comment by DxCx** [comment]
you can do what you want :)
but im not sure you will get future updates, this is up to you ;)

**Comment by khaosx123** [comment]
thx for the fix. sorry for the noob question i was wondering why the 'play from here' episode option only shows on kodi pc and not fire tv. also is there a way to permanently set all view as wall instead of list so it doesn't reset back to list if browsing by page? was just wondering not really requesting. thx again!

**Comment by DxCx** [comment]
see #178
