### ISSUE TITLE
Rapidvideo not working

### ISSUE THREAD

**Issue by Randomdude707** [DxCx/plugin.video.9anime#226]
Earlier this morning rapidvideo was working perfectly but now it's not I went back to other episodes that I did watch it in and it wouldn't work either how do I fix this

**Comment by z89x23** [comment]
on my end, when i click on the episode i cant see the Rapidvideo option.. below is what i see..

01 | MyCloud (720)
02 | MyCloud (360)
03 | OpenLoad

**Comment by Randomdude707** [comment]
Someone please help me with this issue

**Comment by DxCx** [comment]
Im on poor cellular connection right now, and can't enter 9anime myself,
can someone please check if the source is working properly on the website?

**Comment by z89x23** [comment]
i just checked again.. i can confirm that Rapidvideo option is available and working.. watching now..

**Comment by Randomdude707** [comment]
Thanks
