### ISSUE TITLE
Brightness

### ISSUE THREAD

**Issue by j2theosh** [DxCx/plugin.video.9anime#227]
The colours when watching a video seem super bright. When changing the brightness and contrast settings it does nothing. This most likely is user error as this is my first time using kodi here is examples of what it looks like compared to 9anime site.
![screenshot 3](https://user-images.githubusercontent.com/37984025/39336142-de24a45e-49ad-11e8-82d5-1c0ea64d447f.png)
![screenshot 4](https://user-images.githubusercontent.com/37984025/39336144-e2ef59d4-49ad-11e8-9c87-0f83c0c8d085.png)

**Comment by DxCx** [comment]
Attack on titan!! hell yeah! :smiley: 
anyway, this is the first time i'm hearing any complian about brightness,
my guessing is that it is something in your device..
i'll leave that open in case someone can help since i havn't had any issue like this before

**Comment by DxCx** [comment]
@j2theosh is this still relevant? did you manage to fix this?

**Comment by FireWolf74** [comment]
Here is a question,

What are your video setting within Kodi?  Also have you changed any setting since then?

**Comment by FireWolf74** [comment]
Here is mine.
In Kodi you can change the Brightness. Video feed is changed by the renderer 
![screenshot from 2018-07-02 12-13-33](https://user-images.githubusercontent.com/33334258/42174644-11d01460-7df1-11e8-84ed-4c85a6808789.png)
![screenshot from 2018-07-02 12-13-03](https://user-images.githubusercontent.com/33334258/42174645-11e8217c-7df1-11e8-9ce4-0157a6000832.png)
