### ISSUE TITLE
[REQ] Login to 9anime

### ISSUE THREAD

**Issue by imeri** [DxCx/plugin.video.9anime#23]
Is it possible for the next release to be able to login to 9anime and get the watchlist bookmarks?
Thanks..

**Comment by DxCx** [comment]
hey @imeri 
i don't have much time to work on the addon those days, but that's sounds like a cool suggestion,
i'll keep it open and hopefuly someone can pick this up or i'll do it eventually when i have the time :)

**Comment by giftedx29** [comment]
any change on this?

**Comment by DxCx** [comment]
nope, still need time :)
