### ISSUE TITLE
search function not working

### ISSUE THREAD

**Issue by jtipt** [DxCx/plugin.video.9anime#24]
I tried searching several animes, the search function returns nothing. I am using kodi 17, and it was working perfectly fine till yesterday.

**Comment by Dranzera** [comment]
For me the anime episoded say that there's no source so they can't open.

**Comment by DxCx** [comment]
hi @jtipt is it still not working?
i think the site was temporarly down..

**Comment by xXFearTheGuestX** [comment]
I can confirm also being unable to use the search function. I know this was working two days ago, but now it won't search anything

**Comment by devilex94** [comment]
Getting "Couldn't find eliable sources" while playing
Attached log file for you 
[kodi.log.txt](https://github.com/DxCx/plugin.video.9anime/files/999425/kodi.log.txt)

**Comment by JinKudo** [comment]
^pretty much this. happens a lot btw. usually works again if you restart kodi but today it seems to be completely broken. tried several reboots but not working

**Comment by hoppler** [comment]
Hi,

the issue is, that 9anime wants a cookie for the api request containing a "reqkey=e416ee206e6f4f21797ae9a65f11234". otherwise we wont get the source urls for the videos. but i havent found a way to get this cookie

**Comment by jtipt** [comment]
@DxCx I checked again today, and no the search is still not working. I don't think the site was temporarily down as I checked right now its up.

**Comment by DxCx** [comment]
@hoppler and @devilex94  i was aware of this cookie, but not all sources requests it (only F2)
anyway, thanks to @githubus11 looks like the fix for F2 sources is closer :)

about the search itself, i tried to check it now again, but the site is not responding even through the browser, I'm not sure what's happening there, which URI are you trying to reach 9anime trough?
i'm trying both 9anime.to & 9anime.is

**Comment by DxCx** [comment]
ok site is back, and i can finally see the search broken issue..
will try to see what's going on..

**Comment by DxCx** [comment]
ok, so the site responds with `please make sure your browser supports cookie then try again`
which means that the same known tokens issue 👍 
#27 should close that as well =)

**Comment by EremesGuile** [comment]
Good luck @DxCx . Will wait patiently for the fix. :+1:

**Comment by DxCx** [comment]
hey guys, please download latest .zip and retry with it,
should be working now thanks to @githubus11

**Comment by devilex94** [comment]
It's working now :D
Thanks @DxCx @githubus11

**Comment by jtipt** [comment]
Its working now.
Thanks, @githubs11 and @DxCx for fixing this fast.
