### ISSUE TITLE
Addon still working??

### ISSUE THREAD

**Issue by ebs111** [DxCx/plugin.video.9anime#243]
hi
i am getting no sources on every content, is the addon still working?

thanks

**Comment by chrissyt29** [comment]
Same getting error check

**Comment by DxCx** [comment]
yes it is..
which version do you have?
also, did it used to be working on the device? or thats a fresh install?

**Comment by chrissyt29** [comment]
Running version 0.0.34 and was working on the device before

**Comment by DxCx** [comment]
which error do you get?
can you give any log?

**Comment by ebs111** [comment]
as far as i can see they changed the get sources method this is the new one:
for example:
https://www5.9anime.is/ajax/episode/info?ts=1528650000&_=1476&id=n0k66l&server=33
the problem is getting the "_=" its a token that's sits deeply in the js.

**Comment by chrissyt29** [comment]
I deleted and reinstalled works fine now

**Comment by ebs111** [comment]
me too i just reinstalled and it works!!!
thanks.

**Comment by ebs111** [comment]
Do you have a telegram group?

**Comment by DxCx** [comment]
not really.. hehe..
anyway im happy to see its resolved :)
