### ISSUE TITLE
Playback issue. 

### ISSUE THREAD

**Issue by roworit** [DxCx/plugin.video.9anime#249]
Hi, like in the title the addon has a playback issue, it can't find any eligible sources (that's what it says), even the episodes I was watching not too long ago. I'm not good with these things so I doubt I'll solve the problem by myself.

**Comment by Hexoft** [comment]
Same here was working around 2am GMT and stopped working around 8am GMT. 
Nothing updated or obviously changed, probably due to how it connects to the website and gathers the sources but I couldn't say, hears hoping it get's fixed.

**Comment by DxCx** [comment]
yeah, its not working here either..
i'll need to debug this

**Comment by Prometheusx-git** [comment]
It's seems they have changed the api token...

**Comment by DxCx** [comment]
Nope, for me website playback works..
as i said need to debug, probably @Prometheusx-git is right..

**Comment by Hexoft** [comment]
Great when I use vpn it plays fine... I think my internet provider blocked the servers? Hope not, ergh this is annoying.

**Comment by roworit** [comment]
I don't have any problems with the site itself either

**Comment by zacharyselk** [comment]
They changed how the extra ajax parameter is calculated, so NineAnimeUrlExtender.py will need to be modified. Btw @DxCx, if you don't mind me asking, how did you figure out how to calculate that parameter in the first place? I am very curious, I tried for days and could not figure out what to do at all.

**Comment by Prometheusx-git** [comment]
Yes the have changed the "_" Parameter.
Here my analysis, sorry it's a little messy, but should be enough to build python code:

```
t=bVZX0bdD
for(i=0;i<t[lengh] ;i++)n+=t[Char""Code''At](i)+i;return n  #=704

function f(t, i) { t=bVZX0bdDid i=episodeid
            var n, e = 0;
            for (n = 0; n < Math[max](t[lengh], i[lengh]); n++)
                e += n < i[lengh] ? i[Char""Code''At](n) : 0,
                e += n < t[lengh] ? t[Char""Code''At](n) : 0;
            return Number(e)[to String](16)      # 1450 to hex 5aa
function l(t) {    #t=5aa
            var i, n = 0;
            for (i = 0; i < t[Gp]; i++)
                n += t[av + ni + wo + ni + Mg](i) + i;
            return n   #n=250

function f(t, i) {   #t=bVZX0bdDserver  i=33(server)
            var n, e = 0;
            for (n = 0; n < Math[Ny](t[Gp], i[Gp]); n++)
                e += n < i[Gp] ? i[av + ni + wo + ni + Mg](n) : 0,
                e += n < t[Gp] ? t[av + ni + wo + ni + Mg](n) : 0;
            return Number(e)[jl + ni + pl](16)   -> 1441 to hex 5a1
function l(t) { #5a1
            var i, n = 0;
            for (i = 0; i < t[Gp]; i++)
                n += t[av + ni + wo + ni + Mg](i) + i;
            return n  #202

 function f(t, i) { #t=bVZX0bdDts i=1529247600(ts)
            var n, e = 0;
            for (n = 0; n < Math[Ny](t[Gp], i[Gp]); n++)
                e += n < i[Gp] ? i[av + ni + wo + ni + Mg](n) : 0,
                e += n < t[Gp] ? t[av + ni + wo + ni + Mg](n) : 0;
            return Number(e)[jl + ni + pl](16)  #1423 to hex 58f
   function l(t) { #58f
            var i, n = 0;
            for (i = 0; i < t[Gp]; i++)
                n += t[av + ni + wo + ni + Mg](i) + i;
            return n  #214

704+250+202+214 =1370   -> _=1370
```

**Comment by Prometheusx-git** [comment]
Ok, it's the still the same. Just change the DD Parameter to "bVZX0bdD".

**Comment by Peingod300** [comment]
So I am using this on a box and no not enough about the specifics of coding on these, who would I fix this issue.  In other words, is it possible I could get a step by step guide to how to do this?  I don't mind putting in the effort and learning, I just don't want to mess up the code when I work on it.  Thank you in advance :)

**Comment by roworit** [comment]
I changed the code like @Prometheusx-git said to do, this is my first time doing it and I can't check for now if it works but I'm pretty sure I didn't mess up.
Like I said I can't check right now but the problem seems to be resolved, thanks @Prometheusx-git for the fast fix.
[plugin.video.9anime-master updated latest.zip](https://github.com/DxCx/plugin.video.9anime/files/2109272/plugin.video.9anime-master.updated.latest.zip)

**Comment by Peingod300** [comment]
When I went to install it on my box, i get the error that it failed to install add-on because it was the incorrect structure...any ideas

**Comment by Peingod300** [comment]
When I went to unzip yours to check on it, I got an error message saying that "the archive is corrupted or the password is incorrect."  Any ideas??

**Comment by roworit** [comment]
I can't check it right now but I tried again, how's this one?
[plugin.video.9anime-master (1).zip](https://github.com/DxCx/plugin.video.9anime/files/2109317/plugin.video.9anime-master.1.zip)

**Comment by jimboisit** [comment]
same failed to install

**Comment by Peingod300** [comment]
Nope didn't work either

**Comment by jimboisit** [comment]
i got it working on pc

**Comment by Peingod300** [comment]
I also tried to add the script.module and got an error as well

**Comment by jimboisit** [comment]
all i did was extracted the plugin.video.9anime-master (1) then copyed and pasted the content in the 9anime addon directory

**Comment by Peingod300** [comment]
But I am not sure how to do that on a android box....I usually just download the zip file and install from zip inside of kodi and it works normally. So do I need to go into my addon data and copy the files from the new zip into that file instead (the original one that was working and is now broken)???

**Comment by Peingod300** [comment]
I got the file to install finally after using both scripts (Dat guy and anime metahandler) but still have the same issue of no eligible sources...suggestions?

**Comment by jimboisit** [comment]
try this on android
[plugin.video.9anime-master.zip](https://github.com/DxCx/plugin.video.9anime/files/2109332/plugin.video.9anime-master.zip)

**Comment by roworit** [comment]
It works on my android box @jimboisit , thanks, how did you do that? I couldn't get it to work even though I followed what another user said to do step by step.

**Comment by Peingod300** [comment]
After finally uninstalling the addon, reinstalling the original, the scripts, the swag-otaku fix and then this zip above, it worked perfectly!! I can't thank you all enough!!!

**Comment by DxCx** [comment]
Fixed in version 0.0.37 =) Just update..
Thanks to @Prometheusx-git for the fix ^_^

**Comment by jimboisit** [comment]
it was working but now no sources again

**Comment by Randomdude707** [comment]
Will this problem be fixed by tommrow ?
