### ISSUE TITLE
Anime episodes aren't working

### ISSUE THREAD

**Issue by Dranzera** [DxCx/plugin.video.9anime#25]
This morning when I click on any anime episodes it says that there are no sources so it can't open. It worked last night.

**Comment by hoppler** [comment]
i fixed it by editing def load_video_from_url(in_url): in resources/lib/ui/embed_extractor.py to

    def load_video_from_url(in_url):
        try:
            print "Probing source: %s" % in_url
            reqObj = http.send_request(in_url)
            page_content = reqObj.text
            url = reqObj.url
        except http.URLError:
            return None # Dead link, Skip result
        except:
            raise
        try:
            for extractor in _EMBED_EXTRACTORS.keys():
                if in_url.startswith(extractor):
                    extract_result =_EMBED_EXTRACTORS[extractor](url, page_content)
                    sorted_result = sorted(extract_result, key=__sort_extract_result, reverse=True)
                    return sorted_result
        except:
            pass
        print "[*E*] No extractor found for %s" % url
        return None

I added an extra try exept around the `for extractor in _EMBED_EXTRACTORS.keys():` for extractor loop

**Comment by DxCx** [comment]
@hoppler can you please open a PR?
just seen this issue but if you fixed it why not :)

**Comment by Dranzera** [comment]
Thank you very much it works now 😁.

**Comment by DxCx** [comment]
yeah i was trying to reproduce and saw it's working,
i think the site was temporarly down or something..

**Comment by Dranzera** [comment]
It says the same thing today again 😕.

**Comment by DxCx** [comment]
@Dranzera can you download latest zip and retry?

**Comment by Dranzera** [comment]
Thanks wil do once I get home, I'll let you know if it works.

**Comment by Dranzera** [comment]
It works now thanks!
