### ISSUE TITLE
Playback Issue unresolved

### ISSUE THREAD

**Issue by Peingod300** [DxCx/plugin.video.9anime#254]
Even with the 0.0.37 update the "couldn't find eligible sources" error has returned and am unable to watch anything.  It was working perfectly fine for a few hours after the update but now has returned to the same issue.  Any ideas??

**Comment by Nastydog1093** [comment]
Was working for a Minute on my end. Then went to play the next episode and error returned.

**Comment by Peingod300** [comment]
Same thing happened to me, any thoughts on why the update didn't fix this completely?

**Comment by darkbite** [comment]
Same here, im on android 7.1.2.

**Comment by zacharyselk** [comment]
It seems like 9anime changed their '_' parameter again. The problem was fixed but the site has been doing changes on their site for the past ~18 hours, causing things to break.

**Comment by Peingod300** [comment]
So should we just wait it out until the next update officially comes out on here?

**Comment by zacharyselk** [comment]
Ya, it will take one of the dev's modifying the NineAnimeUrlExtender.py file again for anything to work. Last time it took about 3 hours.

**Comment by acbaruso** [comment]
Same problem, was working fine then I was getting "can't find eligible sources"message

**Comment by Blood420** [comment]
nope not yet lol also sorry if i sound rude not meaning to but whats a good backup for when this goes down other then 9anime's site i have yet to be able to find one and DxCx you are the man for this addon

**Comment by jimboisit** [comment]
try animeram

**Comment by FireWolf74** [comment]
DxCx,
![screenshot from 2018-06-18 06-41-55](https://user-images.githubusercontent.com/33334258/41531822-ac97656e-72c2-11e8-9520-8a5be3c18830.png)
If you need more please let me know.

**Comment by ThePyrotechnic** [comment]
The new seed/salt is "8s5IB3Gt"

**Comment by Randomdude707** [comment]
So what's the new link to download it with a firestick

**Comment by Randomdude707** [comment]
Sorry if I sound rude I just really want to know

**Comment by darkbite** [comment]
Its already fixed but the fix its not merged yet.

**Comment by bigjosepi** [comment]
Im not trying to take people away from 9anime or anything, but whenever the 9anime kodi addon is down a nice alternative is the incursion anime addon only problem with that is they dont give the option to choose the resolution like 9 anime and auto streams at the highest resolution which is why I love 9anime but for the time being you all can try that out it work well enough to hold you off till 9anime gets fixed

**Comment by ThePyrotechnic** [comment]
If you want it to work ASAP you can `git clone https://github.com/ThePyrotechnic/plugin.video.9anime -b UpdateToken`, zip the directory, then follow the [manual installation](https://github.com/DxCx/plugin.video.9anime/wiki/Manual-Installation) instructions.

**Comment by nateclub** [comment]
Yo pyrotechnics I tried inputting the link into downloader on the firestick but was not able to pull zip. Is there another way to get this fix for the firestick? First time posting here

**Comment by ThePyrotechnic** [comment]
@nateclub I don't actually use the plugin myself, so I have no firsthand experience with the installation process. As far as getting it onto a Firestick, you will probably need to zip it up on your computer, transfer the zip to your Firestick, and then continue with the manual installation instructions.

**Comment by DxCx** [comment]
Fixed by #257 (Thanks @ThePyrotechnic )
