### ISSUE TITLE
Playback issues reappearing 

### ISSUE THREAD

**Issue by ghettowboy** [DxCx/plugin.video.9anime#259]
Just updated to 0.0.38 and tested an episode to see if it was fixed and it worked. I then went to continue a series I was watching and I'm getting the "unable to find eligible sources" message plus the playback failed message. Is 9anime using some sort of random generator now or something?

**Comment by JustAguyWhoLikesAnime** [comment]
I feel like they are trying to destory the kodi addon

**Comment by jeremyjpj0916** [comment]
Yeah I am using Placenta and Neptune rising currently but its just not the sameee

**Comment by ghettowboy** [comment]
Right now it may be better to wait a day or 2 before updating, it seems they are on the hunt for circumventing of their aggressive ads. I'm using AnimeGo at the moment until this passes. *sigh

**Comment by ghettowboy** [comment]
Fixed with release 0.0.39
