### ISSUE TITLE
No eligible sources

### ISSUE THREAD

**Issue by rbz205** [DxCx/plugin.video.9anime#260]
Hi, the add-on is currently having issues finding eligible sources. 

The videos work on the 9anime website. 

Thanks in advance! 

PS edit - I always check for addon updates, so I don't believe it is an update issue.

**Comment by xSLOWWx** [comment]
Having the same issue. Will work on 9anime website but not add-on. Saw other issues on matter and I have already tried to update. 
Plz fix as soon as possible miss my add free anime!!

**Comment by Prometheusx-git** [comment]
It seems that this time they changed the extra para again and also the codeing itself.
The new Para i see is 'X8uEFlj2'. But just changeing it, doesn't work...

**Comment by WonderfulSubs** [comment]
Prometheusx-git how do you manage to figure out the new Para code?

**Comment by WonderfulSubs** [comment]
@Prometheusx-git  how do you manage to figure out the new Para code everytime?

**Comment by pinkwolf6686** [comment]
Just updated to version 0.0.38 and still it is saying no eligible sources. What gives

**Comment by Peingod300** [comment]
Has the issue been resolved yet?

**Comment by WonderfulSubs** [comment]
@Peingod300 unfortunately no. Personally I'm working on a fix though

**Comment by Peingod300** [comment]
Okay. Just thought I would check.  Is it still the parameter issue?

**Comment by DxCx** [comment]
Just release version 0.0.39 to fix this. (By @Prometheusx-git )
hopefully they will stop mess around..

**Comment by FireWolf74** [comment]
Are you going to do an auto update?

**Comment by WonderfulSubs** [comment]
Ah changing the 0 to i fixed my code as well. Thank you.

**Comment by Osoreru9281** [comment]
How do fix this problem on firestick i check to see if there is any updates but only see .38 still

**Comment by tsaku56** [comment]
@Osoreru9281 how? Can't seem to find the update on firestick

**Comment by Randomdude707** [comment]
It's coming up again man this is driving me crazy

**Comment by Randomdude707** [comment]
Is just me I have the new update and was watching a episode but just now it says it can't find sources.

**Comment by mattjoker3** [comment]
Bruh the update isnt even poppin up

**Comment by Osoreru9281** [comment]
@tsaku56 im on iphone and i think the way i did it was a long and confusing method but i just typed “https://github.com/Prometheusx-git/plugin.video.unofficial9anime” that i got from the file above into downloader and just directed my self in downloader to the file for .39 and downloaded it then installed from zip file ( Zip file > External storage > Downloader > there you will find the file) then updated and tada magic

**Comment by tsaku56** [comment]
@Osoreru9281 thanks for letting me know! It helped to do the update on the firestick but still getting no eligible sources, guess there must be a seperate issue!
