### ISSUE TITLE
V 38 not working

### ISSUE THREAD

**Issue by MobileSuitSadBoi** [DxCx/plugin.video.9anime#266]
Downloaded lastest update to my firestick and the add-on isn't finding sources. Have been trying since yesterday

**Comment by cbizzle14** [comment]
Should be on v. 39

**Comment by MobileSuitSadBoi** [comment]
Bruh I just downloaded v38 yesterday and there's already a v39 lol alright I'll try it

**Comment by Hexoft** [comment]
V 39 now and that seems to have the same problem now too .
 9anime really going to town with the site changes z you'd have thought they were trying to sabotage this add-on the way its going.

**Comment by MobileSuitSadBoi** [comment]
Should I just wait to download v39?? I'm using squad control at the moment but it's just not the same as 9anime

**Comment by gkbq35** [comment]
Also updated to 0.39 earlier today, got one video to play and then back to “no eligible sources” town

**Comment by pinkwolf6686** [comment]
Just updated to 0.39 also and no eligible sources still popping up.

**Comment by ghettowboy** [comment]
These guys are relentless! It's gotta be just as much of a pain for them, more so even. They must really want that $$$$. It didn't take them long as I was able to watch a couple episodes, but .39 is no good now.

**Comment by acbaruso** [comment]
I updated to 0.39 and I still get the same message about no eligible sources. This has been going on since Saturday

**Comment by MobileSuitSadBoi** [comment]
Only half decent alternative I've found is squad control from blamo, if y'all have any other suggestions let me know

**Comment by acbaruso** [comment]
That's the one I've been using. I tried incursion anime ,but not enough
dubbed editions

**Comment by ghettowboy** [comment]
It's pretty much scattered sources for this genre. So sad......

**Comment by DxCx** [comment]
0.0.40 was just released
