### ISSUE TITLE
V 0.39 couldn't find eligible sources / token error

### ISSUE THREAD

**Issue by anubis-genix** [DxCx/plugin.video.9anime#272]
Did a reinstall of the latest release and the URL works fine in browser.

Here are some lines out of the debug log:
`19:55:56.547 T:1068   DEBUG: Probing source: https://9anime.is/watch/hinamatsuri.m7o7/zzqw0l
19:55:58.180 T:1068   DEBUG: [*E*] Skiping RapidVideo because Exception at parsing
19:55:58.180 T:1068   DEBUG: error while trying to fetch info: token
19:55:58.180 T:1068   DEBUG: Probing source: https://9anime.is/watch/hinamatsuri.m7o7/y697z0
19:55:59.379 T:1068   DEBUG: [*E*] Skiping MyCloud because Exception at parsing
19:55:59.379 T:1068   DEBUG: error while trying to fetch info: token
19:55:59.379 T:1068   DEBUG: Probing source: https://9anime.is/watch/hinamatsuri.m7o7/y6pwy1
19:56:00.327 T:1068   DEBUG: [*E*] Skiping OpenLoad because Exception at parsing
19:56:00.327 T:1068   DEBUG: error while trying to fetch info: token
19:56:00.327 T:1068   DEBUG: Probing source: https://9anime.is/watch/hinamatsuri.m7o7/zz2793
19:56:01.205 T:1068   DEBUG: [*E*] Skiping Streamango because Exception at parsing
19:56:01.205 T:1068   DEBUG: error while trying to fetch info: token
19:56:01.219 T:1068    INFO: CPythonInvoker(24, C:\Users\Administrator\AppData\Roaming\Kodi\addons\plugin.video.9anime\default.py): script successfully run
19:56:01.234 T:4156   DEBUG: Thread scriptobs 4156 terminating
19:56:01.234 T:5748   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.9anime/play/hinamatsuri.m7o7/9]
19:56:01.234 T:5748   DEBUG: Playlist Player: no more playable items... aborting playback
19:56:01.235 T:5748   DEBUG: Keyboard: scancode: 0x1c, sym: 0x000d, unicode: 0x0000, modifier: 0x0
19:56:01.235 T:6128   DEBUG: Thread BackgroundLoader start, auto delete: false
19:56:01.243 T:6128   DEBUG: Thread BackgroundLoader 6128 terminating`

Let me know if you need additional info.

**Comment by DxCx** [comment]
#267
