### ISSUE TITLE
Can’t log in

### ISSUE THREAD

**Issue by icpryde** [DxCx/plugin.video.9anime#277]
I noticed they added a log in feature to 9anime but when I type in my credentials it says “login error”.

I double checked my username and password logging into 9anime website and it works.

Is this feature work?

**Comment by ghettowboy** [comment]
That part might need a update. But right now it's been all hands on deck figuring out 9anime's new protection scheme.

**Comment by DxCx** [comment]
Fixed in 0.0.40 (Thanks @SwagOtaku)
enjoy. :D
