### ISSUE TITLE
[RIP] I believe I find a ripoff off your plugin

### ISSUE THREAD

**Issue by imeri** [DxCx/plugin.video.9anime#28]
As the title says..

http://whyingo.org/how-to-install-cypher-locker-repository-kodi-17-1-krypton/

I compared the files and it seems to be identical just the parts where it was ur name on it is changed to Cypher's..

Also, default.py files in his/hers version is encrypted with base64

![1](https://cloud.githubusercontent.com/assets/9384098/26048683/7fffc766-3958-11e7-9f53-a92dd9a62866.png)
![2](https://cloud.githubusercontent.com/assets/9384098/26048684/8003224e-3958-11e7-81c7-8675f7e6344b.png)

**Comment by hoppler** [comment]
those things will always happen. look at his font for his logo...^^

**Comment by imeri** [comment]
I'm aware of those things are happening, just wanted to inform DxCx..

**Comment by DxCx** [comment]
hmm thanks @imeri !
im just not sure what is Cypher and if this duplication is just a duplcation or they injected some malware inside :(

**Comment by DxCx** [comment]
oh my, now i got it, this guy is distributing his own flavor of Kodi and decided to showoff 9anime as his plugin instead of using the proper one..
so sad to see people ruining the opensource community..

**Comment by imeri** [comment]
@DxCx, that was exactly what I was trying to say.. :)

I'm unable to decode the python base64, cuz I'm at work, will try to later to see if there is anything else hidden inside.

**Comment by DxCx** [comment]
Thanks @imeri please let me know what you find.. :)

**Comment by imeri** [comment]
Nothing suspicious.. He just hide the code.

![untitled](https://cloud.githubusercontent.com/assets/9384098/26054837/7ad2214c-396e-11e7-9a91-459adc07d6f8.png)

**Comment by DxCx** [comment]
yep so that's just stealth, not as harmful as i thought but still that's not the way opensource should go.. i think the best way to tackle this at the moment is to add a warning on README.md or something..

**Comment by imeri** [comment]
Yea, I assume that will be the the best option for now.
