### ISSUE TITLE
Couldn’t find eligible sources

### ISSUE THREAD

**Issue by epicshot01** [DxCx/plugin.video.9anime#281]
Not able to find sources, Updated to 0.0.40 worked up until 5-10 minutes ago

**Comment by xSLOWWx** [comment]
Yes I experienced the samething. 
Updated it and it is still not working. 
What is going on?

**Comment by epicshot01** [comment]
I think the website may have changed somethjng

**Comment by xSLOWWx** [comment]
Not again 😭

**Comment by epicshot01** [comment]
[#281](https://github.com/DxCx/plugin.video.9anime/issues/281)

**Comment by Blood420** [comment]
i get and understand the website but its 2018 almost 2019 upgrade and understand that ppl prefer to watch things on their tv vs their pc like most do add a pairing feature if ur that worried about the shit damn

**Comment by acbaruso** [comment]
Updated to 0.40 and the no eligible sources problem still exists. Am I doing something wrong or is it still an issue?
Thank you

**Comment by Randomdude707** [comment]
Still an issue

**Comment by acbaruso** [comment]
Ok,thanks for replying

Sent from Yahoo Mail on Android 
 
  On Tue, Jun 26, 2018 at 7:28 PM, Randomdude707<notifications@github.com> wrote:   
Still an issue

**Comment by neir666** [comment]
how can i fix 9anime on kodi on the xbox one x haveing trouble with it keeps say couldn't find eligible sources

**Comment by DxCx** [comment]
Did you upsate to latest (0.0.41)?

**Comment by neir666** [comment]
i just go to the cypher 9anime addon on kodi

**Comment by neir666** [comment]
i tryed updateing it but it still dosen't work

**Comment by DxCx** [comment]
Yes..
Use the Original plugin and not some copy with modifications..

**Comment by neir666** [comment]
yeah i tryed updateing it again but it just keeps saying the same old stuff

**Comment by DxCx** [comment]
did you install it from 9Anime repo?
do you get version 0.0.41?

**Comment by dgaubatz313** [comment]
I had the same problem on my fire tv with updating. I was able to update by going to add-ons then i think it says latest updates or something on the top then i click on the 9anime repository click the options button and select check for updates and it updated.

**Comment by neir666** [comment]
yup i tryed but it want update it

**Comment by chrissyt29** [comment]
Have you tried uninstalling it and reinstalling it from the original plugin I got mine from the website

**Comment by neir666** [comment]
whats the website called if thats ok

**Comment by chrissyt29** [comment]
I just type in Google 9anime GitHub

**Comment by neir666** [comment]
how to you install it from the website to your xbox one

**Comment by neir666** [comment]
never tryed that et

**Comment by chrissyt29** [comment]
Can't help with that but I would say to download the zip from the standard installation

**Comment by neir666** [comment]
it fine you helped me alot so thank you  for everything

**Comment by neir666** [comment]
i got it to work thank you guys
