### ISSUE TITLE
v0.40

### ISSUE THREAD

**Issue by Spenson** [DxCx/plugin.video.9anime#282]
Fixed the "Couldn't find eligible sources" temporarily now the issue is back. I know it is an ongoing work in progress just wanted to give you an update.

**Comment by epicshot01** [comment]
[#281](https://github.com/DxCx/plugin.video.9anime/issues/281)

**Comment by Spenson** [comment]
Sorry didn't see that

**Comment by xSLOWWx** [comment]
What happened this time that it stopped working again?

**Comment by Spenson** [comment]
Was working for a few hours then when I tried to start a new episode it came up with "Couldn't find eligible sources"

**Comment by RedNinjaX** [comment]
So he is watching us after all

Alright I'm gonna hurry up with this API asap. I've had enough of this already

**Comment by xSLOWWx** [comment]
Who is watching us? 😰

**Comment by HatHeadNinja** [comment]
@xSLOWWx clearly, 9anime devs are monitoring this github, although users who are savvy enough to install and maintain Kodi also have browser plugin's to defeat 9anime's aggressive adverts. 9anime should instead introduce an IP pairing like Openload and at least generate some revenue (rather than none at all and having to spend time changing their code arm wrestling this Kodi plugin.)

**Comment by ruegnueg** [comment]
ya pairing would be nice. I wouldnt need to to that though im a rd User. but it would be great for them and the users. So I guess I use Web Video cast a little longer in the meantime.

**Comment by HackedGameMaker** [comment]
Saw it was updated then I went to the issues to make sure but then I saw the comments.

**Comment by chrissyt29** [comment]
😭

**Comment by Randomdude707** [comment]
I think there just jealous because the plugin is better lol

**Comment by Nastydog1093** [comment]
@ruegnueg which Video Caster do you use?

Thanks in advance.

**Comment by JustAguyWhoLikesAnime** [comment]
@RedNinjaX  hope once you guys finish it they do not figure out how to patch it

**Comment by Karma32** [comment]
@JustAguyWhoLikesAnime since this is an open source GitHub page everybody has access to the code which makes it very easy for the 9anime devs to patch anything that is released. And i feel like the 9anime devs are specifically targeting this add-on since in an attempt to shut it down.

**Comment by ghettowboy** [comment]
Well if RNX finishes his project 9a is going to have a hell of a time trying to figure it out.

**Comment by Randomdude707** [comment]
Is there any way to hide the code

**Comment by JustAguyWhoLikesAnime** [comment]
@ghettowboy  sadly no other anime addons like it

**Comment by Randomdude707** [comment]
Well @ghettowboy ive been using anYme

**Comment by JustAguyWhoLikesAnime** [comment]
@Randomdude707  ya I tried using that myself was not really that great for fire tv sadly lol

**Comment by Randomdude707** [comment]
Do you have mouse toggle

**Comment by jimboisit** [comment]
any one know any good dubbed anime addons while we wait for this one

**Comment by Karma32** [comment]
ive been using FireAnime there was a new update out for it. Works pretty well

**Comment by Randomdude707** [comment]
Wait they finally updated it

**Comment by Karma32** [comment]
yep temporary fix works decently it went live yesterdat

**Comment by Randomdude707** [comment]
Holy cow yes I've been waiting for the update on that on as well

**Comment by Randomdude707** [comment]
Thanks man for reminding me

**Comment by jimboisit** [comment]
i cant install FireAnime on my xbox because its not a kodi addon

**Comment by Karma32** [comment]
@jimboisit ahh that sucks

**Comment by jimboisit** [comment]
i have kodi on my pc and xbox but i dont own a firestick

**Comment by Randomdude707** [comment]
@Karma32 I tried installing it but it's not working how did you install it

**Comment by ghettowboy** [comment]
I only asked because @JustAguyWhoLikesAnime was talking about 9a specifically targeting this addon. Since this is the only one, it makes sense that they would be fighting us. Lol

Besides, I have other sources for Anime. Although I've never heard of FireAnime, and Anime sucks.

**Comment by ghettowboy** [comment]
Seems FireAnime is having the same issues

**Comment by ghettowboy** [comment]
@ruegnuge what has dubbed Anime?

**Comment by ruegnueg** [comment]
fireanime seems ok. but nothing compared to the addon here. quality select, login possibility damn I miss it. still I cast from the 9anime site in the meantime. that firetv stuff feels so uncomfortable and slow compared to a LibreELEC nuc.

**Comment by Karma32** [comment]
@ruegnueg yeah i know your pain i use this add-on for on my tablet works great and has so many features. i hate how the 9 anime developers are specifically targeting this add-on, every time we find a fix they patch it up again.

**Comment by chrissyt29** [comment]
So I'm trying to get FireAnime and I can't seem to get it on my android box

**Comment by ruegnueg** [comment]
fireanime says only for Android TV, and fire TV. not generic android.... but you could try any other anime android if you have mouse toggle.... but it's all a pain compared to a good kodi addon imho

**Comment by chrissyt29** [comment]
I'm currently using watchnixtoons and incursion add-ons on kodi to watch anime but they're not that good compared to 9anime and the new dragonball heroes starts this week already have it added to my favourites lol

**Comment by ruegnueg** [comment]
just saw fireanime high school dxd censored 😂 no way. stick with 9anime casting.

**Comment by roworit** [comment]
I think we can all agree on the fact that the reason this addon is being targeted is that they don't get to show us any ads, meaning no money for them, but doing this won't really get us to use their website. Someone suggested that they do pairing like openload which I don't really know how it works.
Anyway, I downloaded fireanime but it doesn't show up on my android box, I guess I have a generic android with a skin on top and not android TV.

**Comment by strongstyle** [comment]
@ruegnueg  dude I am watching this now, WTF is this  Lmao

**Comment by ruegnueg** [comment]
I don't see adds on their website too. adblock works fine. pairing would be much better for them and the users. and for us in Kodi.

**Comment by roworit** [comment]
So what's the reason for targeting this addon?

**Comment by ghettowboy** [comment]
I refuse to watch High school DXD censored!  What's the point really... lol

**Comment by ghettowboy** [comment]
No pairings, that is crap. Having to re-register every couple hours... No Thanks

**Comment by ruegnueg** [comment]
exactly.... pairing? Buy rd and no pairing needed or captcha. for other pairing last 4 hours way better than massive adds everybody blocks anyway.

**Comment by Karma32** [comment]
What anime is everybody currently watching?

I've started Boku no hero academia Season 3

**Comment by ruegnueg** [comment]
quite the whole spring season

**Comment by strongstyle** [comment]
Not sure what LN is.

**Comment by chrissyt29** [comment]
I have to catch up on one piece black clover seven deadly sins persona 5 and start my hero academia

**Comment by roworit** [comment]
Sorry, I've been chatting on a discord server and I started using their terminology, it means light novel.

**Comment by ruegnueg** [comment]
I hate to use so many different Devices. and my kodi never runs on Android or a fire TV. no 24p the aprox 5 GB, lol my thumbnail Cache is bigger than that 😂

**Comment by strongstyle** [comment]
Oh haha no need to apologize, just messing around. I have been getting into anime recently because of this Addon. 
 I need to step my game up

**Comment by epicshot01** [comment]
@strongstyle LN means light novels

**Comment by strongstyle** [comment]
What do you guys recommend for someone who is loving Dragon Ball Super? I have started watching fairytail but does it take long to get into?

**Comment by Blood420** [comment]
so whats the new plan then?

**Comment by chrissyt29** [comment]
Keep watching fairy tail it get so much better as it goes on

**Comment by Blood420** [comment]
this is true for that series

**Comment by Blood420** [comment]
hell i've been fallowing this addon for the past year or better it was my replacement for kissanime and dxcx's old addon even tho kodi is a dieing world i keep it just for this since i've not found any anime apks worth ne thing i'm open for ideas

**Comment by ruegnueg** [comment]
kodi is a dieing world? you use the wrong addons dude 😉

**Comment by Blood420** [comment]
their up and down all the time once a new one seems to come out ppl give it up after a month it seems like i do have RD so i'm not having that much trouble but keeping my build up and running for ppl is kinda hard as of latei guess i'm just getting tired of testing so many out every month to keep everyone happy i've been using kodi since it was xbmc on the 1st xbox then it was even harder

**Comment by strongstyle** [comment]
I like it.  I have a Sony TV the runs android, and Kodi seems to be the way to go. I can’t find any decent apk.

**Comment by Blood420** [comment]
but the anime side of kodi has always been slim pickings that and now i'm not sure where to look for good addons now adays

**Comment by Blood420** [comment]
i will say terrarium is a good apk but u do need real debrid for it to be worth a fk any more

**Comment by ruegnueg** [comment]
mhnhn I still use exodus with rd. tried covenant but stayed with exodus. still updated. haven't had a problem the last 1.5 years... xstream for German stuff, since they use openload and Co. no problems with rd in that way either. plus the comfort of kodi. blend out seen, a to z etc
... I use kodi since the first nodded Xbox. I ll use it till I die maybe 😉 fire TV and stuff is quite nice but as I said all the ui s are terrible. canceled Netflix because of that. stayed prime though.. shipping and stuff.

**Comment by strongstyle** [comment]
Agreed. Such a hassle

**Comment by JustAguyWhoLikesAnime** [comment]
@Blood420 it is good but not for anime if you are into dubs plus sometimes you may get episodes out of order

**Comment by strongstyle** [comment]
Speaking of Netflix, I was surprised to see animes like fairy tail on it. But I guess it is lacking some major stuff

**Comment by chrissyt29** [comment]
Netflix may have some animes but it literally only has about 50 episodes which is useless for an anime

**Comment by ruegnueg** [comment]
when I speak of kodi I never speak of kodi on Android though. it's just not a good match. maybe on a shield, but I selled it after a short time. fire TV for the whole legal streaming stuff. kodi for everything else. I guess that's my way 😂

**Comment by Blood420** [comment]
@JustAguyWhoLikesAnime yes ur right but as i've said i'm finding it harder and harder to find where to look for good addons or how to look for them

**Comment by Blood420** [comment]
android is just a newer version of lynx just with better gui is all its the easiest way to explain android to ppl

**Comment by strongstyle** [comment]
Man you guys are programming geniuses, I can’t even wrap my head around it. I’m just a user

**Comment by Blood420** [comment]
lol i can't code for shit any more i've not the time but as i stated earlier i've also been using kodi since the first xbox which was lynx and kodi was called xbmc

**Comment by strongstyle** [comment]
Yeah I also had XBMC. I thought I was the man when I modded the first xbox and loaded that on there lol

**Comment by ruegnueg** [comment]
don't get me wrong I love android. and kodi. but not kodi on Android 😂

**Comment by Randomdude707** [comment]
Does anyone have a estimated time when the addon will be fixed again

**Comment by Blood420** [comment]
lol i got ya

**Comment by strongstyle** [comment]
I have no choice, my TV runs android lol :D

**Comment by ruegnueg** [comment]
a TV with Android is something I never gonna buy 😉 but fireanime stated they also replaced the sources from 9anime. so 9anime makes trouble everywhere. just like kiss.

**Comment by RedNinjaX** [comment]
To everyone who's asking for an estimate on a fix relax please. We're developers 😉 We're already on it and should have it done soon ~~or 6 to 9 months~~

**Comment by Randomdude707** [comment]
Lol k

**Comment by d1arkstar** [comment]
@RedNinjaX  take your time if its anything like coding games or mods it will be a real pain so take your time '

**Comment by ruegnueg** [comment]
yeah take your time... many ways guide to anime in the meantime 😂 it's just good to know that ya guys working on it.

**Comment by Aguzy** [comment]
The add-on called dubbed anime is decent and parts of cartoon crazy still work( anime toon, animewow) if you still have it or can find an old zip for it. Another called masterani is decent for subbed anime. They aren't 9anime but may be able to get you a fix until it's up again.

**Comment by ruegnueg** [comment]
dubbed anime, no mather eng or ger or what ever sucks :-P masterani never worked for me at all. "dubbed anime" addon is blamo repo right? ill never ever install that repo again.

**Comment by Aguzy** [comment]
Yeah blamo repo, take you aren't a fan. Strange mastersani has always worked for me and someone updated the code a couple of months ago so .ore of the sources work now

**Comment by ghettowboy** [comment]
Masterani was updated? Where can one find the update

**Comment by Aguzy** [comment]
https://github.com/SirTakoyaki/Masterani

**Comment by ghettowboy** [comment]
Thanks

**Comment by ruegnueg** [comment]
the thing about the blamo repo is (maybe was) it automatically installed wraith and other shit I didn't want. and it's a pain to deinstall it again. masterani was fast and worked a couple of weeks for me. but it was just not good. at least for me 😉

**Comment by ghettowboy** [comment]
Not good? It's one of the better ones I've seen. Maybe I'm biased because I've never streamed on my PC, now I don't have one so it isn't even an option. But hey, everyone sees things differently I guess.

**Comment by islandtj** [comment]
Big thanks and mahalo to the community coders on your efforts, I appreciate you all keeping kodi relevant.

**Comment by romxuk** [comment]
A big update is due, hopefully it should resolve most issues for longer. It really is a push and pull with the site owners of 9anime as they really want to force people to use their almost unusable site and force those horrible invasive adverts and redirects to make money.

**Comment by bsmith456** [comment]
Hi,thanks to everyone who is working on this situation with 9Anime ,I did come across a pretty good anime source in a addon called DECEIT and they have alot of different anime to choose from so hope it helps out to anyone wanting anime now again thanks for all the work you guys are doing on this good luck

**Comment by jeremyjpj0916** [comment]
@bsmith456 thanks for the alternative! So far i dig it.

**Comment by JulGer** [comment]
It's there any help with deceit? It's not working on my box.

**Comment by Aguzy** [comment]
JulGer are you using http://www.onenation.info/repo source for deceit. It might just need updated

**Comment by Nastydog1093** [comment]
@JulGer make sure the Universal Scrapper has been enabled.

**Comment by RedNinjaX** [comment]
API is done. New update should be coming soon

**Comment by JulGer** [comment]
@aguzy
Did get it there. It says something about a duplicate mode. "The following mode already exists: main. Can't find anything about that with Google...

**Comment by ruegnueg** [comment]
kind of off topic but I just don't like apps. for everything I need an app that needs updates that notify me that I have to switch between them... etc.. it's fucking annoying. that's why I prefer libreelec. just plain kodi 😂

**Comment by colbyanon** [comment]
@julGer did you ever get the  following mode main problem worked out? I have the same issue

**Comment by ruegnueg** [comment]
damn, i dont see any adds, still fully functional :) istn firefox with some addons awesome :D

**Comment by d1arkstar** [comment]
@RedNinjaX  is there a way I can message you cause if your api work when way I think I do not wont dev to know what I am going to tell you

**Comment by DxCx** [comment]
@d1arkstar ping me on discord DxCx#5965

**Comment by Jimkongin** [comment]
So, I installed the repository (following instructions and all for the standard installation) but the repository doesn't have 9anime on it? It has some Russian news add-on and some other things on it. I have had 9anime previously installed so it's there, just no updates. Also I'm trying to update on my phone if that makes a difference, I'm still on .39

**Comment by xSLOWWx** [comment]
Are we expecting the new update today?

**Comment by d1arkstar** [comment]
that and I dont use discord that much

**Comment by DxCx** [comment]
No it doesnt :)

**Comment by DxCx** [comment]
Not today but soon, hopefuly this time it wont break that fast

**Comment by r3dxp** [comment]
love your add-on! get it working asap! <3

**Comment by hoppler** [comment]
current DD: 95ec8bcc

**Comment by ruegnueg** [comment]
it's there again?

**Comment by ghettowboy** [comment]
Worked fine this morning for me...

**Comment by DxCx** [comment]
Worked for me last hour

**Comment by chrissyt29** [comment]
Works for me just finished watching an episode of my hero academia

**Comment by ruegnueg** [comment]
yeah seemed it Was just that the ep was listed but no sources yet 😉
