### ISSUE TITLE
V0.0.41

### ISSUE THREAD

**Issue by HackedGameMaker** [DxCx/plugin.video.9anime#285]
I'm not sure if it's just on mine but it still says that it couldn't get the episodes? If 9anime fixed something to counter act the new update I think someone should look into that just in case.

**Comment by d1arkstar** [comment]
I was able to get esp and link just fine what where you looking at

**Comment by HackedGameMaker** [comment]
I just updated the plugin on my fire stick to V0.0.41 and it still couldn't fetch the sources, I'm not sure if I did something wrong on my end though I'll double check just in case, also someone should still look into it just in case.

**Comment by pjcanales** [comment]
Working great here on nvidia shield.

**Comment by HackedGameMaker** [comment]
Hmm I got to double check then because that's BS if it works for everyone else and not for me

**Comment by RedNinjaX** [comment]
Working for me too 👌

**Comment by HackedGameMaker** [comment]
It's still giving me the same error, if anyone else has a fire stick please double check for me. Also I tried Kodi on mine tablet to double check and even on my tablet the plugin doesn't want to work. So I'm not sure why it's only messing up on mine please help me resolve this issue.

**Comment by roworit** [comment]
It works for me too, I'm on an android box.

**Comment by HackedGameMaker** [comment]
Ok so now it's working on my fire stick but it's still not working on my tablet?

**Comment by Blackreaper17** [comment]
Works for me on firestick

**Comment by HackedGameMaker** [comment]
Alright I've figured it out I had to just uninstall and then reinstall kodi and then it fix the problem on both my devices, sorry if I troubled anyone. I'm just going to close this since I got my issue resolved.

**Comment by neir666** [comment]
how can u fix 9anime on xbox one on kodi
