### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by ghettowboy** [DxCx/plugin.video.9anime#294]
This isn't an issue but I wanted to say thanks, not only DxCx but to everyone that has contributed thoughts, ideas and solutions to this awesome addon. The recent updates were what it needed to push it over the top, I'm really digging the new search history and episode listing. They really make a major difference!

**Comment by DxCx** [comment]
I would also like to Thank the community back
For those who helped in code ofcourse but also for those who helped by reporting issues and suggesting changes thank you all
