### ISSUE TITLE
Kodi update error

### ISSUE THREAD

**Issue by HackedGameMaker** [DxCx/plugin.video.9anime#299]
Every time a new update comes out it won't update it on kodi unless I uninstall it and then reinstall it, I was hoping someone could give me a way to where I don't need to keep doing that every time a new update comes out.

**Comment by ghettowboy** [comment]
Do you have the repository?

**Comment by DxCx** [comment]
you should right click on repo itself (from addon settings, install a new..)
then you can check for updates..
preferly, reset kodi before doing this to avoid cacheing

**Comment by FireWolf74** [comment]
Hey Hacker,
Can you post a screenshot of your File Manager. 
If you can I might be able to give you a helping hand

**Comment by ghettowboy** [comment]
I usually go through system>addons>install from repository, select the 9a repo then check for updates.... and I have no issue

**Comment by FireWolf74** [comment]
ghettowboy,
If you have a build it is differently

**Comment by FireWolf74** [comment]
![screenshot from 2018-07-02 18-06-14](https://user-images.githubusercontent.com/33334258/42188537-49aab6ca-7e22-11e8-9feb-a83cb19ba251.png)
This is how my repos look ghettowboy

**Comment by RedNinjaX** [comment]
"**Chocolate Salty Balls**"

**Comment by ghettowboy** [comment]
@FireWolf74 that's your addon list, not your repo list. You want to go into the addon settings, then install from repository.

**Comment by FireWolf74** [comment]
DxCx,
can you send my a message outside of Github?

**Comment by MobileSuitSadBoi** [comment]
@RedNinjaX @DxCx everything seems to be working for me including rapid video🤷🏽‍♂️ all I did was stop Kodi, cleared cache, then checked for updates for both add-on and repo and everything is working🤷🏽‍♂️

**Comment by RedNinjaX** [comment]
@MobileSuitSadBoi yeah DxCx had just released an update around an hour ago that fixed the RapidVideo issue

**Comment by xSLOWWx** [comment]
This is gonna sound lame but would you guys know how to install this add on onto an iphone?

**Comment by HackedGameMaker** [comment]
Yeah I did the right click on repository and it took it's time to register it but it works all be it a very long time to register but hopefully next time it should work faster so I guess I'll be closing this for now.
