### ISSUE TITLE
Trakt scrobbler

### ISSUE THREAD

**Issue by konvar** [DxCx/plugin.video.9anime#3]
Hi! Great plugin! Can you make the plugin to work with Trakt.tv api?
Thanks!

**Comment by DxCx** [comment]
Hey @konvar, thanks for the feedback!

i didnt know trakt holds anime as well. Cool!

I know whats needs to be done to add trakt support, however there is much work to do, and im very busy does days..

Ill leave the ticket open as if someone wants to add it and open a PR ill accept it with pleasure

If noone takes it i might do in the future, but kodi tracking is enough for my needs at this point.. :)

**Comment by XxkingkrowxX** [comment]
Is there any way to use script from say covenant to make this work? And easier?
