### ISSUE TITLE
Rapidvideo again, "Can't find..."

### ISSUE THREAD

**Issue by dangitzin** [DxCx/plugin.video.9anime#302]
Edit title: not "Can't find..." but error check log and playback failed messages

I think rapidvideo maybe down through the add on again? streamango still works fine, but most of the streamango stuff is slow on my mi box. Oh well. Times like these I use kissanime (loads faster, less clunk on browser) from my iPad and stream it to my tv.

**Comment by JustAguyWhoLikesAnime** [comment]
I wonder if 9anime are trying to stop rapid video from working or are we just unlucky lol

**Comment by RedNinjaX** [comment]
It has nothing to do with 9anime but rather RapidVideo. They've made modifications back and forth to their code these last couple of days but nothing major. DxCx is already working on it.

**Comment by JustAguyWhoLikesAnime** [comment]
@RedNinjaX thank you for letting me know I was getting worried ha hopefully rapid stops making changes sooner or later
