### ISSUE TITLE
No Source

### ISSUE THREAD

**Issue by FireWolf74** [DxCx/plugin.video.9anime#307]
Hey I went to the website https://www7.9anime.is 
Went to click on Highschool DXD Hero episode 12 but got episode 11 and NO sources could be found.  
![screenshot from 2018-07-03 23-30-05](https://user-images.githubusercontent.com/33334258/42255374-63760bf2-7f19-11e8-93fb-e93aa9e14ad7.png)  

Could there still be some issues?

**Comment by RedNinjaX** [comment]
This...is not an issue with the plugin. This is 9anime related so this isn't really the place to be asking this.

Anyway simply just disable AdBlock for 9anime and it will work

**Comment by DxCx** [comment]
Plugin works over the site, if the site has issues there is nothing i can do
