### ISSUE TITLE
Login feature and watch list feature?

### ISSUE THREAD

**Issue by HackedGameMaker** [DxCx/plugin.video.9anime#308]
I'm curious about that if we're able to login to 9anime on the kodi version(I haven't tried it yet) also I'd like to know if we can login can we also access our watch list that we have saved on the website?

**Comment by DxCx** [comment]
Yes, check Settings. :)

**Comment by DxCx** [comment]
You can also right click in plugin and add to watchlist.. not only through website..
Anyway, did you find it? Can we resolve this?

**Comment by ghettowboy** [comment]
I think Swag has an update for the login features pending, looks that way anyhow.

**Comment by HackedGameMaker** [comment]
Sorry this wasn't really an issue but I was just curious, though it's good to know that they work so I'll just close this since I know now

**Comment by DxCx** [comment]
Yes ive seen this, waiting for the weekend to work on that properly :))
