### ISSUE TITLE
Help with Wiki

### ISSUE THREAD

**Issue by DxCx** [DxCx/plugin.video.9anime#310]
Hey everyone.. :)

@miasmaejuices used to run the wiki and maintain it, but it looks like he/she has moved on.. (and thats really ok), so first of all, i want to thank you very much if you see this message, i think you've done an amazing job!

secondly, is anyone want to take over the wiki?
there are some common issues that might need updating
and also latest features are not included there
any volunteers? :)

**Comment by miasmaejuices** [comment]
Kudos to you mate. I'm glad to see you're still working on the plugin. I'm sorry I've not been able to keep up with the wiki, but I still keep an eye on notifications and am watching the repository.

I've had to take on multiple jobs to pay bills, so only get a couple of hours per day for family things.

If I get some free time, I'd be happy to come back and give a helping hand.

Keep up the good work buddy! 😊

**Comment by DxCx** [comment]
No problem as at, i can totally understand no worries..

I was not planing to revoke access, so you are still free to help with whatever you like whenever you like :) and as i said above, thanks!

**Comment by HackedGameMaker** [comment]
I can give the wiki a try though I'll have to see if it's up my alley first, if you want you could give me the info and I'll see if I can do it.
