### ISSUE TITLE
eligible resources is back ! 

### ISSUE THREAD

**Issue by bsmith456** [DxCx/plugin.video.9anime#311]
went to watch a video this morning and getting (No eligible resources found) again that didn't last long

**Comment by DxCx** [comment]
Thanks for the report,
i cant really look into it right now but i'll do as soon as i can,
anyway, right now looks like the playback on website is broken as well... (at least here)
does anyone have the playback on website working but not on plugin?

**Comment by t12ung** [comment]
Playback on website is working for rapidvideo source (just checked)

**Comment by bsmith456** [comment]
looks like server down here online as well so might have something to do with it not sure will check later to see if working thanks DxCx

**Comment by sviet2k** [comment]
Site is working now.  There is new idt value =774

**Comment by RedNinjaX** [comment]
Yeah changes were made to 9anime for a second but were then reverted making playback on the site and the API we made work again. DxCx will update the plugin with the new value in a few days but for now the API will hold up

**Comment by bsmith456** [comment]
working here as well thank goodness lol

**Comment by DxCx** [comment]
Yeah website itself was broken, as soon as it came back it workee again
