### ISSUE TITLE
Is anyone else getting "Couldn't find eligible sources"

### ISSUE THREAD

**Issue by epicshot01** [DxCx/plugin.video.9anime#312]
Start getting this earlier today probably between 11:00 am - 1:00 pm (UTC+1), wondering if this is a plugin side issue or user side issue?

**Comment by Nastydog1093** [comment]
Was playing fine then Down.

**Comment by epicshot01** [comment]
@Nastydog1093 when this start happening for you?

**Comment by Nastydog1093** [comment]
About 5-10 minutes ago. Was just waiting it out then I saw your post.

**Comment by ghettowboy** [comment]
Nope.... either it's a site issue or they are playing with the code again and changed something.

**Comment by RedNinjaX** [comment]
Nothing changed with the code. The API server was having issues so I had to restart the server. I'll stabilize it once I get home from work.

**Comment by epicshot01** [comment]
@RedNinjaX Cheers red

**Comment by Nastydog1093** [comment]
@RedNinjaX Appreciate the assistance as always.

**Comment by MobileSuitSadBoi** [comment]
Thanks! @RedNinjaX let us know when it's up!

**Comment by bigjosepi** [comment]
Im getting that on and off but not to bad anyways thanks @RedNinjaX

**Comment by RedNinjaX** [comment]
Yeah like I said the issue is the API server is bugging out so I'll sort it out when I get home.
