### ISSUE TITLE
Watch list in Kodi slow to load

### ISSUE THREAD

**Issue by p213** [DxCx/plugin.video.9anime#313]
I tried to put the watching part from the watch list into kodi, but it takes too long to load on the home screen as a widget, making the rest of kodi not work correctly. How can I make it speed up?

**Comment by SwagOtaku** [comment]
By decreasing the display number of items in the list through the 9anime website ( https://imgur.com/R47PblU ) it loads up watchlist faster. The option is under profile, I set mine to 10 and it loads up pretty quick.

**Comment by p213** [comment]
Thank you. That worked. Do you happen to know how to make the backgrounds that come with it HD and not pixelated when its a kodi widget?

**Comment by SwagOtaku** [comment]
Glad that worked for you. Sorry I don't know about the pixelated issue, didn't even know kodi had widgets.
