### ISSUE TITLE
Xbox Install Kodi 18.0 Alpha 

### ISSUE THREAD

**Issue by xSLOWWx** [DxCx/plugin.video.9anime#314]
Can anybody help to explain how I can download this plugin to Kodi program on Xbox. Having a little issue figuring it out.

**Comment by prough21** [comment]
You can put the repository zip file on a flash drive or a NFS share on your home network. I just used a flash drive.

**Comment by Grazty** [comment]
just follow the instructions its them same thing just put the zip on flash drive and install from zip then you're done. kodi's ui on xbox is pretty buggy tho
