### ISSUE TITLE
Login function

### ISSUE THREAD

**Issue by MrDoAsILike** [DxCx/plugin.video.9anime#315]
Hello, I've recently been having an issue with the login function of the add-on. Yesterday I added my login info for the 9anime.is website to access my watchlist and what not. Worked fine. Today I changes to the diggz  Aurora build and now it's telling me that my login info is incorrect. I'm using Lodi on a laptop and my build change was done with a fresh install. Any help would be great.

**Comment by MrDoAsILike** [comment]
Thanks. I look forward to it.

**Comment by ruegnueg** [comment]
Yeah same issue on firetv. but it works fine in libreelec.

**Comment by ruegnueg** [comment]
any progress?

**Comment by DxCx** [comment]
released a fix =) (Thanks to @SwagOtaku )

**Comment by ruegnueg** [comment]
ah well its good enough. watch 9anime bout 99% via the addon 😉 just use the site to add stuff to the watchlist..

**Comment by MrDoAsILike** [comment]
So to get the fix would I need to update/reinstall it to my kodi?
