### ISSUE TITLE
Couldn't find eligible sources

### ISSUE THREAD

**Issue by epicshot01** [DxCx/plugin.video.9anime#316]
Started receiving this issue, is this because of 9animes' domain change?

**Comment by acidmanifesto** [comment]
Same issue. Just not happening to me as well.

**Comment by bashulsbosch** [comment]
Same issue

**Comment by RedNinjaX** [comment]
Nah the domain change has nothing to do with it. I just haven't gotten around to fixing the modifing the backend yet. I'll get to it soon

**Comment by RedNinjaX** [comment]
Until then it's going to randomly go up and down but I should have it stable by today

**Comment by epicshot01** [comment]
what is your current time?
