### ISSUE TITLE
Addon not working

### ISSUE THREAD

**Issue by epicshot01** [DxCx/plugin.video.9anime#317]
Is anyone else experiencing no anime show appearing or getting an error when trying to load the links?

**Comment by JustAguyWhoLikesAnime** [comment]
@epicshot01  it is because 9anime is down right now

**Comment by epicshot01** [comment]
I didn’t know about that, sorry

**Comment by JustAguyWhoLikesAnime** [comment]
@epicshot01  it happens I am sure it will come on again soon
