### ISSUE TITLE
Autoplay?

### ISSUE THREAD

**Issue by ValiantBlade** [DxCx/plugin.video.9anime#318]
I know feature requests are a pain to deal with, but I'd like to make a very small request.

Is autoplay a possibility? I only ask because I like to watched dubbed anime while I play a relaxing video game of some kind. The problem is that many games lack borderless windowed, and the solutions to get it working can be very iffy and finicky, so tabbing out is a pain in the ass sometimes. Plus as of the time of writing, I've been sick for a while and I've just finally got better, so I spent the last week watching TV shows and anime in a semi vegetative state, so this is something that's been on my mind for a bit.

**Comment by roworit** [comment]
I don't know if this will work, it might not I never tried it but try enabling the play automatically next episode option on kodi and automatically play first result in the addon's settings.

**Comment by ValiantBlade** [comment]
Well, I didn't know kodi has an option for that, well, this issue is pointless now.
