### ISSUE TITLE
stuck on loading circle

### ISSUE THREAD

**Issue by tinymovingparts** [DxCx/plugin.video.9anime#32]
when selecting any of the options: Latest, Newest, Genre, and Search I've been getting stuck on the loading circle. I also have episodes on my favorites same issue when trying to open them. the circle spins then stops than starts to spin again. Any idea whats going on?

**Comment by DxCx** [comment]
Sounds like no internet connection?
just did a small test here, everything looks functional..

**Comment by tinymovingparts** [comment]
internet was connected but still didn't work. Up and running find today must of been a glitch with the site or something. Thanks!

**Comment by DxCx** [comment]
cool! 👍
