### ISSUE TITLE
How to create a login

### ISSUE THREAD

**Issue by FireWolf74** [DxCx/plugin.video.9anime#321]
what is the website to create a login?

**Comment by MrDoAsILike** [comment]
https://www8.9anime.is 

This is the one I went to to create mine and it works with the kodi addon as well.  Hope this helps.

**Comment by FireWolf74** [comment]
Nope I went there but I can't find it.  Maybe I'm blind lol

**Comment by SwagOtaku** [comment]
It's there, most likely due to AdBlock you cant see it. The 9anime site says 
> Anyone facing with losing login button issue, please check your AdBlock again.
