### ISSUE TITLE
No rapid video links

### ISSUE THREAD

**Issue by Cayz181299** [DxCx/plugin.video.9anime#323]
I don't know if it's just me but in one piece I seem to only get streamango, openload and mycloud links all the rapid video links are not coming in, across all episodes I believe to think

**Comment by roworit** [comment]
Check out if the site has rapid video links.

**Comment by Cayz181299** [comment]
Just checked, it's saying object not found on rapid video links

**Comment by Cayz181299** [comment]
The site has a option for rapid video however they are not working, the mycloud links are also gone now, only streamango and openload, I had all sources yesterday

**Comment by roworit** [comment]
It seems that it's the site that has some issues, not the addon's fault. You'll have to wait a bit for new links to go online.

**Comment by Cayz181299** [comment]
I've just checked a different anime, same problem, only streamango openload and my cloud, no rapid video links

**Comment by Cayz181299** [comment]
Alright fair enough I'll be patient, this addon is the best anime addon on kodi by far!

**Comment by Cayz181299** [comment]
I'll keep this case open until the issue is resolved, time will tell

**Comment by icpryde** [comment]
Ah so that’s what’s going on, ya so many links are down and not working or if they even manage to load it’s suoer slow and laggy. Hopefully 9anime gets things back up and running.

**Comment by Cayz181299** [comment]
Excellent, I now have rapid video links, 9anime have sorted the issue

**Comment by Cayz181299** [comment]
Only got streamango and openload links atm, 9anime dodging again?

**Comment by Cayz181299** [comment]
Checked the website again, rapid video link is there but not loading up, as soon as I click on the streamango it's plays?

**Comment by JulGer** [comment]
That's nothing to do with the add-on though.

**Comment by RedNinjaX** [comment]
This is a 9anime related issue. Most likely a couple of RapidVideo videos were taken down due to DMCA issues again and they have to replace then later on. Not all series are experiencing this issue

**Comment by ghettowboy** [comment]
Rapidvideo links work fine.

**Comment by ruegnueg** [comment]
yep i have rapidvideo.

**Comment by Cayz181299** [comment]
I believe my rapid video is down again, checked the website, the rapid video link is working on the website, however not working on kodi addon, I believe watch nixtoons is dodging aswell

**Comment by ghettowboy** [comment]
Yeah... there seems to an issue right now, but yes, it works on the site.

**Comment by ruegnueg** [comment]
i had rapid links an today as always.

**Comment by z89x23** [comment]
It seems from today i dont have rapid video links

**Comment by DxCx** [comment]
dup of #333
