### ISSUE TITLE
Auto play next episode

### ISSUE THREAD

**Issue by Jkrise** [DxCx/plugin.video.9anime#325]
When the current video ends, instead of playing the next video in the series, the sources for the current video are rescaned and the same episode is re-played. Is there a way to instead load the next episode in the series and play that automatically?

Second, if I may, could we bind a key like n for next and p for previous to automatically skip to the next video or jump back to the previous video? 

I know it is not hard to stop the video move down to the next episode and start it, but I think it would be a great feature if some one could script that.

**Comment by DxCx** [comment]
are you using directory view on?
usually when this is turned off, the last directory showen is the one with the episodes
and autoplay just moves on to the next ep

**Comment by Jkrise** [comment]
I'll check and see, thank you for the heads up

**Comment by Jkrise** [comment]
Must be an issue with the skin I am using because it does not work using any combination of settings i can find

**Comment by Jkrise** [comment]
Since no one else appears to be having this issue,I am going to go ahead and close it out. Thanks for the Feed back
