### ISSUE TITLE
New cypher 9 anime update

### ISSUE THREAD

**Issue by ahardy10** [DxCx/plugin.video.9anime#331]
So I didn't have GitHub browser. I installed it on kkodi so I could get the new cypher 9 anime update so it will start working again. I searched up DxCx in the github search. and installed the 4 files that came up at which point my kodi restarted. My cypher 9 anime still isn't working can somebody help please? I'm kind of noob aha.

**Comment by tinymovingparts** [comment]
Cypher’s Addon is a rip off of DxCx and is not connected to this addon in anyway besides the code that they took. You should uninstall the cypher add on and follow the instructions found on this github

**Comment by ahardy10** [comment]
Could you leave a link please?

**Comment by tinymovingparts** [comment]
What are you using kodi on ? i.e PC, Firestick, or other

**Comment by ahardy10** [comment]
PC

**Comment by tinymovingparts** [comment]
https://github.com/DxCx/plugin.video.9anime/wiki/Standard-Installation
