### ISSUE TITLE
Anime listing

### ISSUE THREAD

**Issue by jtshinsou** [DxCx/plugin.video.9anime#332]
I have been using this add-on for quite some time but the only issue I have is that you guys don't have a listing of all the anime so it is extremely difficult to find a new anime or one that you no longer remember the name of.  Which forces me to go back to Incursion anime add-on.  Am I the only one with this issue

**Comment by HatHeadNinja** [comment]
I discover new anime via this plugin, by using the Most Recent menu items.  The plugin search now also remembers your searches, so you don't have to remember. You can also favorite seasons, which is how you do a watch list natively in Kodi.  Hope this helpful!.
