### ISSUE TITLE
No Rapidvideo links

### ISSUE THREAD

**Issue by ghettowboy** [DxCx/plugin.video.9anime#333]
It appears Rapidvideo links aren't showing up in the app. Links show and work on the site though. Any thoughts as to why this is happening?

**Comment by ghettowboy** [comment]
So the app is going to need updating for this then. When DxCx updated it last time he kinda indicated this might happen again. Lol.... *sigh

**Comment by RedNinjaX** [comment]
On the bright side, it's simple fix. Just needs to be updated

**Comment by ghettowboy** [comment]
Streamango links seems to have improved. Was able to watch shows using that instead  where as before they were extremely slow and stuttered to an unviewable state.

**Comment by ruegnueg** [comment]
fireanime skipped using 9anime sources though.

**Comment by Cayz181299** [comment]
Rapidvideo are gone again
