### ISSUE TITLE
No rapidvideo links

### ISSUE THREAD

**Issue by Cayz181299** [DxCx/plugin.video.9anime#339]
It's gone for me again, anyone else got issues?

**Comment by ruegnueg** [comment]
tried it right now works up to 1080p. maybe the Episode you wanna watch has no rapid yet. rapid links take a little longer to appear for New episodes.

**Comment by Cayz181299** [comment]
Maybe it's just what I'm watching, one piece has no rapidvideo at all, imma check another show and see

**Comment by mattyyy12** [comment]
I don’t seem to have rapidvideo for the app or on the website either for anything

**Comment by mattyyy12** [comment]
I guess it’s fine For your show but some shows don’t see to have it anymore

**Comment by ruegnueg** [comment]
ill always about 20 Shows at a time 😉 but you said it wont work at all.

**Comment by mattyyy12** [comment]
Yea I meant the shows I looked at like plastic memories and boruto

**Comment by DxCx** [comment]
Rapidvideo links are working.. just checked..
