### ISSUE TITLE
OSMC Nothing shows up

### ISSUE THREAD

**Issue by nerotix** [DxCx/plugin.video.9anime#34]
Just installed it on latest OSMC release when I open 9anime, and for example go to latest, nothing shows up.. all i see is "Next Page (2/246). That's all. Am I doing something wrong here? As I've changed nothing.

**Comment by DxCx** [comment]
hi @nerotix as far as i know OSMC runs Kodi 17 which means it should work,
can you provide more details? maybe kodi's log file?

**Comment by DxCx** [comment]
@nerotix any details please? is it working now using the latest version?

**Comment by nerotix** [comment]
@DxCx Sorry mate, been busy with college for the last couple of days. But I just downloaded the latest and installed it, works flawlessly! You have like the best anime plugin for Kodi/OSMC etc.. even the search functions works properly. Thank you so much dude!

**Comment by DxCx** [comment]
Thanks! Couldnt done it without the support of the community :)

**Comment by nerotix** [comment]
@DxCx it seems I was too quick to respond.. the problem I mentioned is solved indeed. However, everything that I try to play gives me an error "couldnt find eliable sources" or something like that.. also I sometimes get an error when trying to play something "9anime error check logs for more information". Would u like me to upload the logs?

**Comment by nerotix** [comment]
@DxCx Now I installed latest update again and that error is gone and I can pick a server.. however when i for example select I get a "Playback failed.. One or more items failed to play. Check the log for more information about this message." error. If you need logs or something, lemme know.

**Comment by DxCx** [comment]
@nerotix 9anime website has issues today
I'm waiting for them to get stable again to make sure everything is working..
