### ISSUE TITLE
No rapid video option even though the episode has rapid video on the site

### ISSUE THREAD

**Issue by JustAguyWhoLikesAnime** [DxCx/plugin.video.9anime#342]
ok so I do not know if this is a known problem or not but I see that rapid video is not showing up. and ik the episode has a working rapid video player as I went on the website to make sure of it.  I am also on latest version 0.0.48

**Comment by Jkrise** [comment]
Hmmn, I am getting rapidvideo links in mine. They are all 480 but,  I am also watching some older anime and there may not be anything higher quality. Have you cleared temp and/or restarted your device?

**Comment by MrDoAsILike** [comment]
Idk.. I get 1080, 720, 480 options on mine. Although they were gone up until a few days ago

**Comment by JustAguyWhoLikesAnime** [comment]
looks like it is working now very weird as I did close kodi and cleared kodi cache but looks like restarting the fire tv worked thank you :)
