### ISSUE TITLE
Repo down and Addon giving "No module named storageserverdummy"

### ISSUE THREAD

**Issue by woojoo666** [DxCx/plugin.video.9anime#343]
Not sure if these two are related issues, but I tried installing this 9anime addon today using Git browser, and after installing the repo, I tried doing `Install From Repository > 9Anime Kodi Repository` and it gave me `"Could not connect to repository."`

I then went back to git browser and installed the video addon (0.0.48) directly, but when I tried to open it, I got an error, and the log reads:

	03:19:22.996 T:510760867056   ERROR: GetDirectory - Error getting
	03:19:24.512 T:510183613680   ERROR: Previous line repeats 6 times.
	03:19:24.512 T:510183613680   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
	                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
	                                            Error Type: <type 'exceptions.ImportError'>
	                                            Error Contents: No module named storageserverdummy
	                                            Traceback (most recent call last):
	                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/DxCx-plugin.video.9anime-c359b5c/default.py", line 1, in <module>
	                                                from resources.lib.ui import control
	                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/DxCx-plugin.video.9anime-c359b5c/resources/lib/ui/control.py", line 13, in <module>
	                                                import storageserverdummy as StorageServer
	                                            ImportError: No module named storageserverdummy
	                                            -->End of Python script error report<--
	03:19:24.580 T:510819050736   ERROR: GetDirectory - Error getting plugin://plugin.video.9anime/
	03:19:24.581 T:510819050736   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.9anime/) failed

**Comment by Cayz181299** [comment]
Yeah the 9anime addon is not working it keeps saying "9anime error", I can't even go in right about now

**Comment by JustAguyWhoLikesAnime** [comment]
@Cayz181299  I think he fixed it are you on version 0.0.49

**Comment by RedNinjaX** [comment]
Honestly it should be working regardless if you updated or not. I fixed the API so those who haven't updated shouldn't be experiencing issues like those who have.

**Comment by dreamkenya** [comment]
No wonder mines ain't working.  I'm still on 0.0.47

**Comment by Cayz181299** [comment]
@JustAGuyWhoLikesAnime yeahh I updated it earlier, its working great now

**Comment by JustAguyWhoLikesAnime** [comment]
@RedNinjaX  was not working for me at all until I updated though and that was pretty much right before I posted my comment

**Comment by RedNinjaX** [comment]
Well that's odd. In any case are least it's working now

**Comment by JustAguyWhoLikesAnime** [comment]
@RedNinjaX  yup that is true only reason why I knew it had a update was cause I looked on the github lol :)
