### ISSUE TITLE
9anime addon not working 

### ISSUE THREAD

**Issue by Cayz181299** [DxCx/plugin.video.9anime#344]
Keep getting "9anime error", I can't even open the addon

**Comment by mattyyy12** [comment]
Same

**Comment by Cayz181299** [comment]
I've checked the website 9anime.to and everything is in working order

**Comment by Cayz181299** [comment]
Back to watchnixtoons for now I guess until it gets fixed

**Comment by Cayz181299** [comment]
Fireanime is that a kodi addon?

**Comment by DxCx** [comment]
fixed was released, enjoy.

**Comment by Cayz181299** [comment]
You guys are amazing, thanks so much for maintaining this addon

**Comment by ruegnueg** [comment]
nope fireanime is a firetv Android TV App 😂
