### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by defelber** [DxCx/plugin.video.9anime#347]
I wen't to update my video plugin update, and only have 0.0.48 available. Every time I go to update, it says update failed.

**Comment by tinymovingparts** [comment]
It’s a little tricky. Auto update typically updates it the next day for this addon. To manually update it you have to update the repository.

**Comment by defelber** [comment]
How do i update my repository?
I'm guessing i have to go back to a link and download it again?

**Comment by tinymovingparts** [comment]
Not necessarily here’s what I do.
1. Go to add ons on the left bar.
2. Go to the open package icon on the top left.
3. Install from repository.
4. Find the 9anime kodi repo, right click (3 bar button on firestick remote.) and check for updates. Give it a minute and it should update

**Comment by defelber** [comment]
I've gotten it updated, thank you.

**Comment by tinymovingparts** [comment]
No problem @DxCx can you close this issue?

**Comment by JustAguyWhoLikesAnime** [comment]
@defelber  @tinymovingparts  def can do it himself :)

**Comment by tinymovingparts** [comment]
Ok still a little unfamiliar with how to close issues and who can close them.
