### ISSUE TITLE
9anime addon down 

### ISSUE THREAD

**Issue by JustAguyWhoLikesAnime** [DxCx/plugin.video.9anime#348]
I get 9anime error when trying to select a tv show

**Comment by Grazty** [comment]
the site on 9anime isnt currently loading no episodes on pc it isnt the addon

**Comment by JustAguyWhoLikesAnime** [comment]
@Grazty ah guess I should have went on the site instead of using the is it down site

**Comment by JustAguyWhoLikesAnime** [comment]
@

**Comment by mattyyy12** [comment]
The website seems to be working though
