### ISSUE TITLE
Mp4upload Server added to website

### ISSUE THREAD

**Issue by HackedGameMaker** [DxCx/plugin.video.9anime#351]
Mp4upload server has been added to the website so when you guys get the plugin fixed please add this server as well to see how good it does on the plugin.

**Comment by Cayz181299** [comment]
This is a brilliant idea as mycloud is a terrible source for me, the more the merrier

**Comment by ruegnueg** [comment]
who cares if there is not a way to get rid of captchas or a fix for the addon i dont use 9anime anymore 😂

**Comment by Cayz181299** [comment]
True 😂😂

**Comment by Osoreru9281** [comment]
What addon you guys using now 9anime been trash lately and i tried fireanime but seems to not get past loading screen? Help pls im just tryin finsh Gansta :c

**Comment by ruegnueg** [comment]
fireanime works for me, but it's so buggy and slow and sometimes crashes. In kodi you could use watchnixtoons or masterani redux.

**Comment by JustAguyWhoLikesAnime** [comment]
@Osoreru9281 do you have a fire tv or maybe something like that?

**Comment by Cayz181299** [comment]
BTW if you guys are looking for anime, great addon called Masterani Redux in Wilson Magic github,

**Comment by Osoreru9281** [comment]
@justaguywholikesanime i only have firestick but if fire tv is better ill upgrade seems like they are the same tho?

**Comment by JustAguyWhoLikesAnime** [comment]
@Osoreru9281  ya it is the same get a app called tv cast fire tv and you will see a free app get it and the app is a browser but you can use it to stream videos right to the fire stick :)

**Comment by ruegnueg** [comment]
webvideocaster is better though. still thats an ugly way to consume Media 😂

**Comment by ruegnueg** [comment]
btw you know a lot Alternative addons for kodi were mentioned for you? and you seem to Have kodi on your firetv Stick because you wouldnt be here if not.

**Comment by JustAguyWhoLikesAnime** [comment]
@ruegnueg sadly no just what I told you it has been working great for me

**Comment by Osoreru9281** [comment]
@justaguywholikesanime ill try it ty!

**Comment by JustAguyWhoLikesAnime** [comment]
@Osoreru9281 np

**Comment by mattyyy12** [comment]
Any luck with addon fix? @DxCx

**Comment by DxCx** [comment]
This is not going to happen, the addon is deprecated.
