### ISSUE TITLE
Add on is working again!

### ISSUE THREAD

**Issue by ghettowboy** [DxCx/plugin.video.9anime#353]
I know the add on is discontinued but it appears 9anime has removed the captcha, just thought people might be interested.

**Comment by mattyyy12** [comment]
It was posted in the other thread so most are aware atleast

**Comment by Ichijoe2112** [comment]
Is it just me, or are the Streams in general just dropping out after about 3 to 4 minutes into a session?
I'm using Kodi v17.2 on the nVidia Shield Pro (2015).

**Comment by Ichijoe2112** [comment]
Nevermind I guess it must have been me. As after having rebooted both my Router, and Shield Devices. The Add-on is now working as expected again.

**Comment by FireWolf74** [comment]
Crazy thing is that I can't even get a stream to work
