### ISSUE TITLE
9Anime rabsberry 1b slow loading

### ISSUE THREAD

**Issue by XonarDG** [DxCx/plugin.video.9anime#359]
Ive tried to use this plugin for quite some time but what is stoping me from using this addon are the loading times. I mean it is like 1-2 minutes on every page which (as you might understand) is quite frustraiting. Im using it on rabsberry 1b as i said in the title. I have not problems like this on addons like Youtube.

**Comment by JulGer** [comment]
I'm using it on my android TV box without any such problems.

**Comment by XonarDG** [comment]
well that kind of device could use a quad core rabbsberry 1b is using a singlecore

**Comment by XonarDG** [comment]
but is still dont think that the addon is affected be the performance

**Comment by RedNinjaX** [comment]
This add-on is deprecated and will be replaced by a new much faster one in the near future
