### ISSUE TITLE
Anime 9

### ISSUE THREAD

**Issue by Skyblaze777** [DxCx/plugin.video.9anime#360]
It is no longer working for my Amazon fire t.v stick I have done everything I can think of uninstalling it reinstalling it reset Kodi ect. It acts like it wants to load and all I can get is the symbol of it trying to load. Please help thx

**Comment by mattyyy12** [comment]
Works fine for me

**Comment by bigjosepi** [comment]
Works for me, and unfortunately the addon was depreciated so you probably won't get help.

**Comment by Skyblaze777** [comment]
Is there anything I can do?

**Comment by mattyyy12** [comment]
Try fireanime if you can’t get it to work

**Comment by Skyblaze777** [comment]
Mattyy12 do you have a link for it for the firestick?

**Comment by Randomdude707** [comment]
https://github.com/XenTeckzX/FireAnime/raw/master/FireAnime1.9.8.apk there you go dude

**Comment by Skyblaze777** [comment]
Is there a available version of this for a Amazon fire stick?

**Comment by Randomdude707** [comment]
That is the version for the firestick

**Comment by Randomdude707** [comment]
Download it through the downloader on the amazon store or look up a install video on Youtube

**Comment by Skyblaze777** [comment]
Thanks man
