### ISSUE TITLE
Every 5th anime on each page (latest, dubbed, etc.) doesn't load it's cover poster.

### ISSUE THREAD

**Issue by Frogger3000** [DxCx/plugin.video.9anime#361]
I know this add-on isn't really being worked anymore but I thought I'd share my problem anyways.

Doesnt load on my widget as well.

Anyone else experiencing this? Using Kodi 17.6, LibreElec, RPi3, up to date add-on and official add on from this site.

**Comment by mattyyy12** [comment]
That’s so trivial lol why is that even an issue for you, as long as you can watch stuff you’ll be fine

**Comment by Frogger3000** [comment]
Regardless of it being trivial I'm sure it's not intended and I'm posting it in its appropriate place.

As to why it's an issue to me is because all my widgets have cover posters besides my anime one, which just has an ugly black spot in the middle. 

Like I said in my post, I know this add-on isn't really being worked on that much, but it should at least be reported.
