### ISSUE TITLE
No titles working

### ISSUE THREAD

**Issue by Peingod300** [DxCx/plugin.video.9anime#366]
I have tried opening multiple animes and continue to get a check log error message.  Not sure if they are fiddling on their end or I am missing something.  I am running the 0.51 version (newest released).

**Comment by Tatsichan** [comment]
Confirmed here. Happened suddenly. Was watching an episode and soon as it was over, the next one didn't work.

**Comment by dispersedmenis** [comment]
Yes I agree I just started getting the error message does anyone know when it back up

**Comment by RedNinjaX** [comment]
It's a 9anime related issue: 

https://www.reddit.com/r/9anime/comments/agptl3/error_503/ee816jd?utm_source=reddit-android

**Comment by d1arkstar** [comment]
Not sure what is up but I am suppressed that the add-on lasted this long .

**Comment by d1arkstar** [comment]
dis regard that its the website guys

**Comment by dispersedmenis** [comment]
And I was just getting into my series too and that happens lol

**Comment by dispersedmenis** [comment]
Does anyone know if it's up yet or not ?

**Comment by clutchylfg** [comment]
> Still down for me :(

Up and running now!

**Comment by dispersedmenis** [comment]
Okay thanks

**Comment by Shahav** [comment]
I'm  getting  error messages also. Man this sucks!

**Comment by Shahav** [comment]
On 9Anime I Am not able to pull up any titles or get any anime to play at all & was wondering if any one was having these issues also and if y'all are able to get it to work or not?   Man I can't  wait until the new anime add-on is really so we don't  have to deal with this kinda crap any more after it's  ready.

**Comment by roworit** [comment]
https://blog.wonderfulsubs.com/2019/01/wonderfulsubs-for-kodi-add-on-beta-sign.html
They are releasing the beta of the new one through emails for now

**Comment by Shahav** [comment]
So, is there any way to add the beta test add-on to kodi & Is there a zip file that we can download  so it can be added to kodi directly?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by roworit** [comment]
Go to that page, register for the beta and you'll receive an email with a link for the addon.

**Comment by DxCx** [comment]
The new addon is now available via both repo and under its own guthub.
Please refer to
https://github.com/DxCx/plugin.video.wonderfulsubs
