### ISSUE TITLE
New Add-on Beta Sign Up Page

### ISSUE THREAD

**Issue by RedNinjaX** [DxCx/plugin.video.9anime#367]
Hello everyone!

We are releasing the new anime add-on through a Beta testing program via sign up. DxCx, SwagOtaku and the team worked extremely hard on this for the past few months so I hope you all enjoy! All that I ask is that you share and spread the word as much as you can.

**You can sign up here:**
[**WonderfulSubs for Kodi Add-on BETA Sign Up**](https://blog.wonderfulsubs.com/2019/01/wonderfulsubs-for-kodi-add-on-beta-sign.html)
![kodi-promo-wide](https://user-images.githubusercontent.com/34778154/51937350-68d1d180-23d8-11e9-9d04-5ff5d8ff1470.png)

**Comment by RedNinjaX** [comment]
To submit further feedback and issues on the add-on please refer to the kodi_beta_feedback channel on our Discord server. I will begin to limit my time on this repo as responding to multiple requests in different places (GitHub, Discord, email) has grown tiresome, and it would also make it easier for the add-on developers to further assist you.

You can join here: https://discord.gg/y8Hggpc

Thank you

**Comment by d1arkstar** [comment]
@RedNinjaX  where do we  report bugs ?

**Comment by RedNinjaX** [comment]
The same place

**Comment by d1arkstar** [comment]
you mean right hear ?

**Comment by RedNinjaX** [comment]
In the WonderfulSubs **Discord Server** in the **#kodi_beta_feedback** channel linked above

Again, here in the link to join: [https://discord.gg/y8Hggpc](https://discord.gg/y8Hggpc)

**Comment by d1arkstar** [comment]
ya I found it got lost in the mass messages

**Comment by d1arkstar** [comment]
post there if you need more info let me know

**Comment by jerryjones95** [comment]
I just sign up for beta when will receive the email and keep up the good work

**Comment by icpryde** [comment]
awesome testing now

**Comment by dgaubatz313** [comment]
We can use this on a nvidia shield right? I try downloading it from downloader and it downloads a bin file that isn't recognized instead of the zip file. I downloaded the file on my computer to see if it worked and it does download the zip file on my computer. I don't know what is going on. Is anyone else getting a bin file when they download instead of the zip file?

**Comment by DxCx** [comment]
The new addon is now available via both repo and under its own guthub.
Please refer to
https://github.com/DxCx/plugin.video.wonderfulsubs
