### ISSUE TITLE
9anime error

### ISSUE THREAD

**Issue by beigelad** [DxCx/plugin.video.9anime#4]
Hey there, trying to use 9anime today but when ever I click on any of the series it just says 9anime error and doesn't let me proceed to the episodes :( other people have also reported this on reddit

**Comment by DxCx** [comment]
Hey @beigelad!
Can you like people from the reddit to this issue?
Anyway, im not home atm, but will check it as soon as i can.. i used the plugin last night and it was just fine.
Thanks for the report :)

**Comment by beigelad** [comment]
Thank you I will :D

**Comment by beigelad** [comment]
Hi some users reported the issue maybe because they have changed their domain from 
.to to .is? That could be an issue with it? :)

**Comment by xanergy** [comment]
👍  many people are having the same problems we are having would be great if you could check it out :D

**Comment by IceFireDude** [comment]
can report no errors for me but everything is blank

**Comment by blunttedsmurf** [comment]
Ok figured it out. I looked at Fiddler to see what was happening. When you pull up your add-on the response for the pages say HTTP/1.1 302 Moved Temporarily. It says it has moved from HTTPS to HTTP. So I took your add-on apart changed the 8 instances you had https://9anime to http://9anime, then zipped it backup using Windows "Send to> Compressed Folder" and boom everything is running again. 

Even though they changed from 9anime.tv to 9anime.is, the  9anime.to still works. Which is your base url in your script.

Love your work. Keep it up I'm here to enjoy the Anime.

**Comment by IceFireDude** [comment]
@blunttedsmurf  I would make a pull request if you can

**Comment by blunttedsmurf** [comment]
Oh forgot to mention I took the https out of this line "http://%s/ajax/episode/info?id=%s&update=0" as well. It also said 302 Moved temporarily. If you don't do this the Open Load window that loads the videos sources just sits there.

@IceFireDude sorry I don't know what a pull request is.

**Comment by beigelad** [comment]
Great stuff @blunttedsmurf! Hope @DxCx can make the adjustments soon :D!

**Comment by IceFireDude** [comment]
@blunttedsmurf  lol ya np i am new to github as well here is a link on what it is https://help.github.com/articles/about-pull-requests/

**Comment by IceFireDude** [comment]
@beigelad ya :)

**Comment by Ichijoe2112** [comment]
@beigelad  @DxCx I was able to resolve the issue (as described by Beigelad), by simply renaming Three instances of https for http.

The First One is located on Line 8 of: plugin.video.9anime-maste\resources\lib\NineAnimeBrowser.py

The other Two were inside plugin.video.9anime-master\resources\lib\ui\embed_extractor.py on Line 191

**Comment by DxCx** [comment]
oh wow sorry didn't know there is so much attraction over that :)
anyway, I'll look at the shortly had a crazy couple of days

**Comment by beigelad** [comment]
Thank you! ^-^

**Comment by DxCx** [comment]
im not sure, from what i can see 9anime (website) is not reachable atm,
getting 502 via cloudflare.. :(
am i the only one?

**Comment by beigelad** [comment]
@DxCx have you tried 9anime.is ? That one is working for me!

**Comment by DxCx** [comment]
yep, had some tests, for me at least, all https:// is just dead,
and over http only .is is working..
expect a fix soon ;)
thanks for all the pointers everyone

**Comment by IceFireDude** [comment]
@DxCx yay can not wait for a fix :)

**Comment by beigelad** [comment]
@DxCx thanks for fix will let ppl at reddit know :3

**Comment by DxCx** [comment]
Ok, so domain issue is resolved. please download master .zip and try it
let me know how it goes ;)

P.S

I've found that OpenLoad probably did some change on thier site,
so OpenLoad sources are not supported ATM, on that i'll look tomorrow

**Comment by IceFireDude** [comment]
@DxCx  confirm it is not blank anymore. although trying to watch anything it is just stuck processing openload. ik you said that does not work but the shows I am testing has other servers with it. so not sure what is happening

**Comment by DxCx** [comment]
stuck on overload? it just fails and skip it here.
maybe the specific thing you are trying to watch has wiired openload links?
anyway, openload is for tomorrow

**Comment by IceFireDude** [comment]
@DxCx ya it will not skip it its just stuck at fetching sources processing openload then errors out when I click cancel. and alright I will be looking forward to it :)

**Comment by DxCx** [comment]
@IceFireDude try after this patch now ;)

**Comment by DxCx** [comment]
their http endpoint is on and off which confuesed me,
anyway, openload is disabled now so it should just skip

**Comment by IceFireDude** [comment]
@DxCx you are going to be annoyed but now it will not install on kodi lol

**Comment by DxCx** [comment]
@IceFireDude uninstall and reinstall? :O
why wouldn't it be installed?

**Comment by beigelad** [comment]
@DxCx @icefiredude mine is working fine! :) uninstalled previous one and installed new one :D works like a charm!

**Comment by IceFireDude** [comment]
@beigelad it is working with the newest update? cause when I download the new zip amd try to install it on kodi I get a error

**Comment by beigelad** [comment]
@icefiredude yeah dude same update as 34 mins ago! Try restart your kodi and delete any other instances of downloaded zip files of previous ones etc :)

**Comment by IceFireDude** [comment]
@beigelad ya I will delete it and restart kodi and my fire tv ill brb

**Comment by IceFireDude** [comment]
@beigelad ok now it left me install it lol thanks never had that problem before darn it kodi :-P  and looks like it is going fast now that openload is disabled :)

**Comment by beigelad** [comment]
@icefiredude let the Anime binge begin :p! Thanks again @dxcx

**Comment by IceFireDude** [comment]
@beigelad ya! and ya @DxCx you the man

**Comment by DxCx** [comment]
Cool happy to hear that :) then i'm closing this as domain issues are resolved
and i've opened new ticket for OpenLoad issue only.

thanks for the feedback guys! 👍

**Comment by DxCx** [comment]
@IceFireDude @beigelad version 0.0.2 is now released with OpenLoad fix as well 👍
