### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by bokkoman** [DxCx/plugin.video.9anime#40]
I'm on spmc (kodi 16). Installed this addon, but just gives errors when everything anything.

**Comment by bokkoman** [comment]
When entering anything

**Comment by hoppler** [comment]
only works with kodi 17 or later as 9anime needs ssl which is not available in kodi 16

@DxCx How about a requirement on the plugin itself and a big readme update for kodi 17 or above (dunno how to do it)

**Comment by DxCx** [comment]
yeah, thanks @hoppler can you open such a PR? :)

**Comment by hoppler** [comment]
done #43

**Comment by DxCx** [comment]
Thanks @hoppler
