### ISSUE TITLE
Episodes not Working

### ISSUE THREAD

**Issue by LukiasSenpai** [DxCx/plugin.video.9anime#41]
All recently added videos in the latest update dont seem to be working properly. I get to chose my video to watch then it gives me the playback failes error message

Thanks for all the great work though

**Comment by githubus11** [comment]
It seems that F1 server is unstable right now. as the current version crashes if a video is offline, you wont see sources and get an error message. already made a pullrequest to fix this. you could make a specific example (name and epsiode) of a stream that wont work, so i can test it with my patched version.
