### ISSUE TITLE
Repository for plugin

### ISSUE THREAD

**Issue by hoppler** [DxCx/plugin.video.9anime#44]
Hi,

i have a repo mostly ready for this plugin. please create a new release so i can link to it and update all files in the repo. 
after i updated it ill create a branch for you which you can than fork and maintain as you only have to upload the new release.zip into a folder and update a version number. (its pretty easy)

**Comment by hoppler** [comment]
Created a branch for you. fork the https://github.com/hoppler/repo.plugin.video.9anime/tree/dxcx-repo branch and that should be it. i used the master of the plugin as version 0.0.3

**Comment by DxCx** [comment]
oh wow thanks,
yeah i wanted to release a version once i see all the open reports are closed and verify.

i think that eventually we should add a travis to build a versioned number and push to this repo =)

**Comment by DxCx** [comment]
hey @hoppler, i have another anime plugin at https://github.com/DxCx/plugin.video.animeram
we can also add it to the repository.. :)

**Comment by hoppler** [comment]
@DxCx if the plugin is working i can add it before youre weekend fork. so please test it^^ you could possibly take some time for yourself and refactor the 9anime plugin to support both: 9anime and animeram as i think the codebase of those two is the same expect the embeded_extractor

if you do so, please add the possibility to display messages to the user in case of any failure. if i would implement it, it would result in a complete refactor of this lib which i would not want at this time

**Comment by DxCx** [comment]
hey @hoppler how do i use this repository in kodi? ^_^

**Comment by DxCx** [comment]
Also, what should be the steps for update?
1. Create a new versioned zip
2. Upload the zip to plugin's directory
3. update addons.xml with the newest version
4. update addons.xml.md5
is that correct?

**Comment by hoppler** [comment]
@DxCx the repo contains a "how-to-update.md" for your question
every plugin including the repo-plugin itself has its own folder. so to install the repo, get the zip in repo.plugin.vido.9anime and install it in kodi.

**Comment by DxCx** [comment]
yeah i got my list after reading the how to update just want to make sure with you i got it right since im going to make a script out of it

**Comment by hoppler** [comment]
as a script the order is correct. also make sure to have the version in the addons.xml of the repo in sync with the addon.xml of the actual addon

**Comment by DxCx** [comment]
hi @hoppler please make me collaborator at the repository so i can update version 0.0.7 👍

**Comment by hoppler** [comment]
@DxCx as i sad earlier. please fork the repo and make it your own. ill delete mine afterwards

**Comment by DxCx** [comment]
cool thanks 👍

**Comment by DxCx** [comment]
Alright @hoppler 
Done and it looks good =)
can you sync yours with my fork, this way everybody who is already installed yours will get mine as version 0.0.3?
Also, next step is to update how to install instructions.
i think that pointing to:
https://github.com/DxCx/repo.plugin.video.9anime/raw/master/repo.plugin.video.9anime/repo.plugin.video.9anime-0.0.3.zip
is abit long, and also is version specific..
we can use some service to make download url shorter but we are still going to set it at specific version..
any idea?

**Comment by hoppler** [comment]
@DxCx done it and forked yours .tested it in my end and it updated automatically to 0.0.3 and the plugin to 0.0.7 from your repo. so other will migrate the next days

**Comment by DxCx** [comment]
nice thanks @hoppler 👍 👍 
do you have any suggestion about the zip?

**Comment by hoppler** [comment]
well. the only reason to update the repo is, if youre moving it to another location which, thus chaning the repos url. And Like other plugins, just add a link to the Readme of this addon with a good name and nobody will blame if its long or not^^
remember: you dont have to update the repos zip at all if youre releasing a new update for any addon. the "addons.xml" is a different one, than the "addon.xml" in the repo.plugin.... folder

**Comment by DxCx** [comment]
thanks @hoppler 
i created a short link for the repo zip: https://goo.gl/p9Lde0
i don't have time now but i'll update README later on and close this issue 👍
