### ISSUE TITLE
Broken with Leia

### ISSUE THREAD

**Issue by cerinthus** [DxCx/plugin.video.9anime#46]
Current source has bumped xbmc.gui abi to 5.13.0

**Comment by hoppler** [comment]
@cerinthus so you tried installing it but it didnt want to? if so, we have to change the <import in addon.xml from xmbc.gui to xbmc.python 2.25.0

**Comment by DxCx** [comment]
pardon me, but what is Leia?

**Comment by hoppler** [comment]
@DxCx Codename for Kodi v18 -> Leia 18.x

**Comment by DxCx** [comment]
Oh cool, thanks, first time i hear about kodi 18 :)

**Comment by hoppler** [comment]
@cerinthus @DxCx tested cmbx.python 2.25.0 and it blocks installation on kodi 16 which is good. someone please test it for kodi 18. updated the repository to have the version 0.0.6 which includes the xbmc.python 2.25.0 fix. also added scripts.module.requests so a fresh install of kodi only requires installation of the repository and all requirements get installed. now its up to 9anime to get stable again

**Comment by nOneALOne** [comment]
tested the xbmc.python 2.25.0 fix it installed on kodi 18

**Comment by hoppler** [comment]
@nOneALOne thx for reporting^^

**Comment by cerinthus** [comment]
That fixes it.  

Is it only there to prevent installation on Kodi < 17? 

Removing the dependency, or setting the optional attribute causes it to install and work without issue as well. 

Closed.

**Comment by hoppler** [comment]
> Is it only there to prevent installation on Kodi < 17?

yes
