### ISSUE TITLE
Suggestion: Openload

### ISSUE THREAD

**Issue by justin89h** [DxCx/plugin.video.9anime#50]
Love that you managed to get openload sources working, especially with 9anime having issues at the moment.

Could I suggest though, for the plugin not to attempt accessing openload until after it is selected in the sources list? Having to pair it with openload every single time, even when using F1 or F2 servers is a bit annoying.

On a somewhat unrelated note, you may or may not know that dat1guy54 had a 9anime plugin out a while ago that worked extremely well (not sure how, but it was a lot faster). He since gave up on it because of a DCMA notice about his use of fanart. He seems to have disappeared from the scene now though so it's no longer available. I'm not sure under what he had it licensed, but if you're ok with it I have the zip file and all dependencies so you could potentially get some ideas from it.

**Comment by tugkan98** [comment]
I was going to ask this too.

**Comment by DxCx** [comment]
Hmm wired, when i tested it, it asked only once, so i was ok with that..
Ill check it again probably tomorrow, but i agree that its annoying..
Anyone else seeing this issue? Or i am the only one who had to pair only once?

**Comment by hoppler** [comment]
@DxCx  hes not using openload, therefore hes not pairing it therefore always sees the "pair me" dialog.

**Comment by justin89h** [comment]
Even if you do pair it openload requires pairing every 4 hours I think. So if you watch an anime episode a couple times a day, you need to pair twice a day, **even if you're not using openload servers**. Openload should probably be a last resort for people to try if other servers aren't available, rather then forcing the process when it isn't needed.

**Comment by justin89h** [comment]
@hoppler is the multiple requests due to attempting to access multiple sources in order to get a list of what's available? 

Another suggestion if this is the case (I know this would be harder to implement) would be to have a setting in the add-on for maximum resolution. Example 720p: The plugin could then attempt to play F1 720p, if not available, move to F2 720p, if not available, check for 480p, if not available, **then** access openload. That way in the vast majority of cases only one request needs to be sent when loading an anime episode.

I believe this may be how many other plugins do it.

**Comment by DxCx** [comment]
Well yeah justin ill make openload lazy loaded which means that only after selected it will require a pair..

**Comment by justin89h** [comment]
Sounds good to me, thanks
