### ISSUE TITLE
Installation Failed: Dependency

### ISSUE THREAD

**Issue by nbfalls** [DxCx/plugin.video.9anime#52]
I'm very new to this, but when I try to install from zip file on my firestick through kodi, I get an error message saying failed to install add on, the dependency on script.module.urlresolver version. Any help on how to solve this?

**Comment by DxCx** [comment]
hi @nbfalls,
we are in the process of moving into repostory rather then just download the zip,
the repostory has the missing dependancy, you can install the reposetory (and then obtain the plugin through it) by installing this zip:
https://github.com/hoppler/repo.plugin.video.9anime/raw/master/repo.plugin.video.9anime/repo.plugin.video.9anime-0.0.2.zip

**Comment by hoppler** [comment]
@DxCx update the link above and delete the older 0.0.1 an 0.0.2 zips from the git-repo^^

**Comment by DxCx** [comment]
hey @nbfalls is installing through the repository helped?

**Comment by DxCx** [comment]
Going to close this because of inactivity
