### ISSUE TITLE
Failed playback error

### ISSUE THREAD

**Issue by dandreis** [DxCx/plugin.video.9anime#55]
Every time I try and load a video I get either a 9anime error or failed playback error. Here's the log : https://logs.tvaddons.ag/pixinltmw

**Comment by DxCx** [comment]
hey @dandreis are you using latest version?

**Comment by dandreis** [comment]
Yes, I'm running it on an Android TV box with Kodi v17.3

**Comment by hoppler** [comment]
@dandreis youre not using the latest plugin version

**Comment by zenakuadevent** [comment]
i am having the same issue as well. i am update to date with kodi 17.3 with the fire-stick and i update to the lates plugin 0.7 if i now mistaken. and even follow the step to the read me repository, and i still get the error

**Comment by justin89h** [comment]
I had this issue a day or two ago and 9anime.is was down for a while at the time, 9anime.to was still working. When 9anime.is came back up the plugin started working again.

May or may not be related

**Comment by dandreis** [comment]
Yeah turns out I didn't update the add on like I thought I did.
