### ISSUE TITLE
9anime failing to install

### ISSUE THREAD

**Issue by SwuidwardBarrett** [DxCx/plugin.video.9anime#68]
Hi

I'm running SPMC 16.7.0 on an Nvidia Shield (2017). I'm trying to install both the 9anime repo and addon using the zip files through the normal method. I've managed to install the repo but there is nothing in the Video Addons section. So then I try to install the add-on directly using it's zip file, however I then get an error message stating it's failed to install because "The dependency on xbmc.python version 2.25.0 could not be found". However, SPMC has Python 2.7 if I'm not mistaken.

Any ideas what might be causing this?

**Comment by DxCx** [comment]
hey @SwuidwardBarrett as written in main README.md, the plugin requires Kodi 17+
looks like your Kodi version is lower then that.

**Comment by SwuidwardBarrett** [comment]
Ah right, I did read that but I didn't think that mattered as SPMC 16.7 has implemented most of the main features of Kodi 17 (such as updated Python and compatibility with HTTPS), and other add-ons that state they require Kodi 17+ also work on my SPMC. No worries though

**Comment by hoppler** [comment]
@SwuidwardBarrett if you have the kodi fork with ssl enabled for python you can change the xbmc.python version to 2.1.0 and install that modified version

**Comment by DxCx** [comment]
@SwuidwardBarrett Can you confirm it helped or not? Might help more people in the future

**Comment by gaining** [comment]
@SwuidwardBarrett you should use FTMC: https://kod1help.com/ftmc-kodi-jarvis-fork-for-all-android-and-fire-devices

**Comment by DxCx** [comment]
closing due lack of activity..
