### ISSUE TITLE
Add more sections

### ISSUE THREAD

**Issue by icpryde** [DxCx/plugin.video.9anime#69]
Hello, I'm loving this add on and thank you for all the work you are doing. I was hoping you could add more sections from 9anime like "Popular" or "Most Watched" to make it easer to find shows you want to watch.

**Comment by tinymovingparts** [comment]
I agree great addon! While its not a necessity, would it be possible to add a "Recently updated Dub" section to the menu? I know the sites has it in a tab on the home page. Not sure if it would be hard to add it into this plug in or not. If possible it would be a huge convenience, but as mentioned not necessary if its to much trouble.

**Comment by DxCx** [comment]
hey @icpryde @tinymovingparts the plugin is written in such way that adding new pages like this is very very easy.
just give me title in menu + links in website and i'll add them

**Comment by tinymovingparts** [comment]
@DxCx awesome!
the title would be "Latest Dubbed"
and the link would be 
https://9anime.is/filter?sort=episode_last_added_at%3Adesc&language=dubbed

**Comment by hoppler** [comment]
@DxCx
another one:
New&Hot (subbed) [the ones on the homepage if you select "recently updated sub"]
https://9anime.is/filter?status%5B%5D=airing&sort=episode_last_added_at%3Adesc&language=subbed

I guess thats the one people looking for "newest subbed" want. so we could add "newest dubbed" and "newest subbed" or "new&hot subbed"...

**Comment by DxCx** [comment]
Just release 0.0.10 with both subbed and dubbed. enjoy 👍

**Comment by icpryde** [comment]
Would you be able to add the section "Most Watched". The link is https://9anime.to/most-watched

**Comment by icpryde** [comment]
@DxDc would you be able to add "Most Watched" the link is https://9anime.to/most-watched

**Comment by icpryde** [comment]
@dxcx would you be able to add "most watched" section? The link is https://9anime.to/most-watched

**Comment by DxCx** [comment]
can you please open another issue for that?
