### ISSUE TITLE
Trying to install

### ISSUE THREAD

**Issue by melavious** [DxCx/plugin.video.9anime#70]
I'm trying to install 9anime on my kodi android box. I'm running version 17.3. I can't seem to get the repository added to install the addon

**Comment by tinymovingparts** [comment]
@melavious have you already download the repository zip file onto your box?

**Comment by melavious** [comment]
No I haven't been able to get it to download

**Comment by tinymovingparts** [comment]
Not to familiar with the android box set up is there an app on the box for downloading links?

**Comment by melavious** [comment]
no have to add it with file manager. I haven't been able to get a working link to the zip file

**Comment by tinymovingparts** [comment]
If you have acess to the google play store you can download es file explorer that is basically the same as downloader and follow the same general steps for firestick once you have downloaded the actual zip

**Comment by tinymovingparts** [comment]
@melavious if you still need help or are confused i can give you step by step instructions assuming your able to get "ES file explorer" from the google play store. You need download the repository's zip file to install it .so using file manager in kodi will not work.

**Comment by melavious** [comment]
So once I have this es file explorer how do I go about getting the zip file

**Comment by tinymovingparts** [comment]
@melavious sorry for the late reply just got off of work and had to test everything out. safe to say following these steps everything will be successful!

starting with Es file explorer
1. on side tool bar click where it says favorites to drop down the different options and click (ADD)
2. there will be to spaces that need to be filled out Path & Name
Path: https://github.com/dxcx/plugin.video.9anime
Name:dxcx
after that is filled in hit ok.
3. on the side tool bar scroll down to the newly added dxcx and click it.
this will now open up the github page where you will click the "here" link under the Installing from repository heading.
4. after it downloads exit out of ex file ex file explorer and open Kodi.

IN Kodi

1. click on addons
2. click the icon that looks like an open package on the top left (assuming you havnt dressed up kodi with a skin)
3. click install from zip
4. click external storage folder
5. click download folder
6. click repo.plugin.video.9anime-0.0.3 zip file

The repo is now installed

7. click install from repo
8. click 9 anime kodi repository
9. click video addons
10. click 9 anime
and it will install his addon with the current (0.0.9 version) this also has auto updates so it will update if he updates it. You now have the wonderfull addon made by DxCx and contributers

this method was tested using a nexus tablet running an android os. and the repo file was downloaded in this path way:
/storage/emulated/0/download/

**Comment by tinymovingparts** [comment]
@melavious Please comment on how everything goes it should all work if you follow the steps.
@DxCx not sure how many people use the android box but if you want you could add these steps into the readme as to prevent any confusion or further open issues for installing onto android box.

**Comment by melavious** [comment]
Works well the app was a big help ty

**Comment by DxCx** [comment]
wow @tinymovingparts that's make me very happy to see people helping out just like that 👍 ,
go ahead open a PR i'll merge it gladly :)
