### ISSUE TITLE
Kodi 17.1 - Failed to Install a Dependency

### ISSUE THREAD

**Issue by Sol-Illadan** [DxCx/plugin.video.9anime#82]
I am using OSMC which has Kodi 17.1. I had downloaded the repo zip, installed it & tried to install the 9Anime plugin, But it gives a message - 
> Failed to install a Dependency

Please suggest as to what dependency i should install to enable the plugin to be installed.

**Comment by Sol-Illadan** [comment]
I looked at the addon.xml & found that it needs urlresolver v3.0.31. But the latest one for Krypton is 2.10.0

**Comment by DxCx** [comment]
hey @Sol-Illadan please refere to the readme.md file,
there are instructions there on how to install it via the repository.
the repository has the missing dependency as well. 👍

**Comment by DxCx** [comment]
Im Guessing that it just helped..
