### ISSUE TITLE
MyCloud links crash Kodi (Krypton 17.3) 

### ISSUE THREAD

**Issue by noisymints** [DxCx/plugin.video.9anime#83]
Not sure if it's something on my end, but when I click on MyCloud links kodi crashes. All the other links  work fine. 
On the site I've noticed some kind of advertisement block/box on 9anime player (only in MyCloud links).
Debug log: https://pastebin.com/NyB18BtZ

**Comment by p1wookie** [comment]
MyCloud has worked perfectly fine for me. Using it now with Dragon Ball Super

**Comment by hoppler** [comment]
@noisymints i guess your system doesnt support the filetype provided by mycloud see:

`
19:09:27.275 T:1424   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 104 for 1.
19:09:27.275 T:1424   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 105 for 1.
`

**Comment by DxCx** [comment]
thanks @hoppler 
MyCloud requires m4u playlist support, as hoppler stated it's probably not supported by your version of kodi. are you using offical build? or?

**Comment by noisymints** [comment]
Official build. Kodi 17.3 Krypton on Windows 7 PC. Same thing happens on my laptop by the way. Uninstalled - reinstalled etc.

**Comment by DxCx** [comment]
hmm, 
i did try it out of the box on windows 10 and it works (I am working on mac usually)
maybe windows 7 is missing something because i did find addon which tries to add support for that.
can you try and install 
https://superrepo.org/kodi/addon/script.module.m3u8/

and report back?

**Comment by noisymints** [comment]
It was already installed because it updated. Unfortunately, same thing happens. Kodi crashes and exits. 
log: https://pastebin.com/fc7UhbGm

**Comment by DxCx** [comment]
hmm.. this is interesting..
i'll try to dig further into this issue using my old laptop (Windows 7 as well)

**Comment by noisymints** [comment]
Thank you, DxCx and everyone.

**Comment by DxCx** [comment]
I've tried to play with it abit more, m3u just works for me out of the box..
is there anyone else who's experiancing this issue?
or someone can shade abit light on this one?

**Comment by noisymints** [comment]
Update: I upgraded my laptop to Win10, and with a clean install of Kodi everything works fine. Looks like something was wrong with my previous setup, so I wouldn't worry much for this error anymore. 
DxCx, thank you very much for trying to resolve this.

**Comment by DxCx** [comment]
Cool! Im happy to see that you are able to enjoy it now :)
