### ISSUE TITLE
Add additional metadata to animes

### ISSUE THREAD

**Issue by DxCx** [DxCx/plugin.video.9anime#84]
using kodi api:
http://mirrors.kodi.tv/docs/python-docs/13.0-gotham/xbmcgui.html#ListItem-setInfo

**Comment by silvatyrant** [comment]
@DxCx which source are you looking at using for this? MAL or something?

**Comment by DxCx** [comment]
I think that most of the info exists in the exisiting 9anime website..
I just want to set xbmc item with additional information..
If We will need to add extra call for more api then it not worth it, maybe addig the posabilty to add to library so people can set a different scrapper will be a better solution

**Comment by SwagOtaku** [comment]
@DxCx I've coded into 9anime, which now displays the plot of the anime extracted directly from 9anime. Where should I upload the lines I added so you can review them?

**Comment by ypawar159** [comment]
@DxCx ,
We can add this info as you mentioned.
But in your code your are using regular expressions to find the required tags from html repsonse. I am familiar with beautiful soup4 for this kind of stuff.
And then setting info about Anime, you are using control.draw_items to display anime list and as well as for the list of sources for selected episodes. So even if we capture the anime info 9anime website how to set it is also another concern.
If I get clear understanding of what to modify where I could give it a try.
Also if possible use of installed scrappers to fetch the info.

**Comment by DxCx** [comment]
Ive already explored the possibilty of using existinf scrappers
This will work only if we are able to export a selected show locally (means you create a link file for each episode, and be able to create one for each one that releases later on)
That was tons of work when i saw it.

Also, if we get back to options 1, once show is selected you can always send one more API request to get more info and fill up the item better..

**Comment by ypawar159** [comment]
Any plans to work on this?

**Comment by SwagOtaku** [comment]
@DxCx @ypawar159 @silvatyrant  I think I've found a solution. I wrote some code that puts the plot on the episode page of the respected anime. Here's what it looks like https://imgur.com/a/w50Gh .

**Comment by pjcanales** [comment]
Any update on this. Would like how swagotag did it if possible

**Comment by SwagOtaku** [comment]
@pjcanales The update is already on the latest zip for 9anime :)

**Comment by pjcanales** [comment]
I'm on 0.0.34 right now. I wanted to know when or how to get it to show each episode information like how you did it. So I can know which episode of dragon ball i left off on. Like how you did here https://imgur.com/a/w50Gh.

**Comment by pjcanales** [comment]
I'm referring to the plot of each episode say for dragon ball super

**Comment by SwagOtaku** [comment]
9anime site doesn't have summary for each individual episode. The plot that is on the episode page is the plot of the anime series in general. 
I will try to see if I can get the plot of each episode, but as DxCx stated above, an extra call for api might not be worth it or it would be hard to do so.

**Comment by lp214** [comment]
Is there a way to add fanart as a background to the anime like how incursion does for its tv/anime, using metadata?

**Comment by ypawar159** [comment]
@Ip214,
It's possible using built-in kodi libraries.

**Comment by RedNinjaX** [comment]
If you guys are still interested in getting an episode by episode description I could create a custom API endpoint on my server that can do all the heavy work for you. I've already got most of the episode metadata of many series on hand

**Comment by RedNinjaX** [comment]
My site handles it well 
![screenshot_20180622-045431](https://user-images.githubusercontent.com/34778154/41767832-a7609480-75d8-11e8-8d48-4b1098603361.jpg)

**Comment by Jkrise** [comment]
RedNinjaX, if you could do that, it would be awesome!
