### ISSUE TITLE
[REQ] autoplay next using first server available

### ISSUE THREAD

**Issue by greatwroth** [DxCx/plugin.video.9anime#87]
Add an option to essentially mimic the site; autoplay next episode in the series using selected or highest quality on the first server available.

**Comment by DxCx** [comment]
hey @greatwroth 
do you have an example of a plugin that does that?
this is more kodi logic then plugin logic..

**Comment by greatwroth** [comment]
The only other video plugin I use is the YouTube plugin, it has autoplay next but uses YouTube's api so likely not useful.

**Comment by Jai-Brown** [comment]
This is essentially already in the addon, just requires a few tweaks.
Go into the 9anime settings, change "Episode order" to "Ascending", change sort by Resolution "Best", select "Automatically play first result". Then simply find the episode you want to start from, right click it and select Play from here.

If I understand it correctly, this only uses the MyCloud server but I've had no issues with it so far. I've been using this method since I first got the addon.

**Comment by DxCx** [comment]
This will only auto start without the need to select source, if i got it correctly what he wants is the ability to play one after another

**Comment by greatwroth** [comment]
The dev is right, I've already tried that setup and there is no "play from here" option when using this addon anyway. I normally watch anime 2 or 3 episodes at a time, hence the request.

**Comment by Jai-Brown** [comment]
I'm sorry, but there is a "Play from here" option on my Kodi. Maybe we're running different versions. I'm running the latest stable Krypton build. With everything mentioned in my comment above, I can start a season from episode one and have it play through every episode until I stop it or I've watched everything in the list, so long as there is no error thrown while watching an episode.

![](http://i.imgur.com/EOC3rZj.png)

Regardless, the plugin has broken for me anyway and I can no longer watch any anime, so I'll have to open another issue for that.

**Comment by greatwroth** [comment]
Hmm, that's odd, I am also running latest stable (even double checked on github), but I have it set to play next video automatically (meaning selecting a video acts the same as play from here in most cases) and if I revert it I get that option... but I cannot test it as the addon has inexplicably stopped working for me as well. Once I can test it the real issue might be adding compatibility for that option or not removing "play from here" when that option is enabled which is how the youtube addon works.

**Comment by DxCx** [comment]
Play from here is not something the addon is adding but this is basic feature of Kodi.
as i don't do auto play i never noticed it but i do have it as well =)

**Comment by DxCx** [comment]
Closing this as it is already implemented and working.
