### ISSUE TITLE
9anime addon not working

### ISSUE THREAD

**Issue by xanergy** [DxCx/plugin.video.9anime#88]
First I want to say Im very thankful for this add-on. The 9anime kodi addon has been working fine for me and suddenly when I search for episodes it just says 9anime had an error. Im using the newest version 0.0.9. Thanks in advance.

**Comment by hoppler** [comment]
Hi,

reason is: 9anime.is is off. You have to change the _BASE_URL_ to 9anime.to in resources/lib/NineAnimeBrowser.py

A settingsentry in the settings to select the domain could be handy for something like this

**Comment by DxCx** [comment]
just released version 0.0.14 with the .to domain.
should auto update (if using the repo)
enjoy!

**Comment by gooksta** [comment]
How do i changed the base_URL?

**Comment by DxCx** [comment]
Even after restarting and then right click on repo and check for updates?

**Comment by gooksta** [comment]
@dxcx yes, I restarted it twice now and tried updating it but still doesn't update
