### ISSUE TITLE
Adding / syncing favourites list

### ISSUE THREAD

**Issue by icpryde** [DxCx/plugin.video.9anime#92]
I was wondering if anyone has some suggestions, I know we can save shows/movies to the build in "favourites" section on Kodi which is working well. Though what I wanted to do was also have a way to sync those favourites so I can have the same lists on all my kodi devices and was wondering what some suggestions would be?

I was thinking of trying Emby but I don't think that works the way I'm describing above....any suggestions?'

Ideally simply using 9anime favourites section and being able to log in from the device would work well.

**Comment by DxCx** [comment]
Hey @icpryde
There is also a feature request for login support (see #23) i guess this is what you are looking for..

**Comment by DxCx** [comment]
Closing duplicate
