### ISSUE TITLE
Kodi add on not working 

### ISSUE THREAD

**Issue by xanergy** [DxCx/plugin.video.9anime#93]
Whenever I search up an anime it says there is a problem. Everything else works

**Comment by DxCx** [comment]
hey @xanergy i've just confirmed that search works for me.
are you using latest version (0.0.14)?

**Comment by xanergy** [comment]
It says 0.0.9 do I have to reinstall it?

**Comment by xanergy** [comment]
It was working up to two days ago. And when I try and update it says there are no updates available

**Comment by DxCx** [comment]
The latest version from repository is 0.0.14,
You can try reinstall the repo and the plugin using instructions on README.md

**Comment by xanergy** [comment]
Ok I installed it. Looks like I have to reinstall it every time you update to a diff version. Im using fire tv. Thanks for the help and the awesome app
