### ISSUE TITLE
Addon stopped working all of a sudden.

### ISSUE THREAD

**Issue by Jai-Brown** [DxCx/plugin.video.9anime#94]
The plugin was working fine yesterday, but now anytime I open it, I get stuck in the Watched menu, No action taken makes a single difference. I've tried forcing an update. reinstallation and many restarts.

I'm unsure what more information I can give to help with this issue.

[Video Demonstration](https://www.youtube.com/watch?v=RuWPJYs-JGI)
[Kodi Log](https://gist.github.com/Jai-Brown/9a800e93e648d0b27b149cfc6ad3f86e)

**Comment by Jai-Brown** [comment]
Randomly showed up again so closing. Sorry for wasting your time :S

**Comment by DxCx** [comment]
@Jai-Brown no problem at at all :) i've seen it only now... hehe
