### ISSUE TITLE
addon incompatible due to unmet dependencies

### ISSUE THREAD

**Issue by ebby84** [DxCx/plugin.video.9anime#95]
hi..iwas trying to install 9anime aon my android box but addon is incompatible.is this is only for kodi krypton??

**Comment by DxCx** [comment]
Hey,
this is for Kodi 17+
did you install from repostory as explained on readme.md?

**Comment by ebby84** [comment]
thanks for reply bro...my bad..you did mention it for kodi 17..guest have to upgrade the box or use kodi fork..

**Comment by DxCx** [comment]
Cool 👍 hope you can sort it out soon ;)
