### ISSUE TITLE
Couldn't find reliable sources.

### ISSUE THREAD

**Issue by Jai-Brown** [DxCx/plugin.video.9anime#96]
[Log File](https://gist.github.com/Jai-Brown/8c2708eb24cb057850ae21c9c3fd61c9)

I'm not sure what happened. One minute I'm finishing the last episode of Nanbaka and everything is fine, next minute I'm unable to load a single video. I've tried fresh addon installs, fresh Kodi installs (Both from the Windows Store and the 32-bit installer from their website) and nothing seems to help.

I can confirm it has broken on both my PC and Tablet, so it can't just be a one off thing.

It appears to have something to do with the way the video is loaded, as seen in the attached log file, it has something to do with:
`12:05:13.144 T:14592 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.9anime/play/fateapocrypha.03j5/1`.
Every google search comes up with a different solution so that's of little help.

Screenshots.
![](http://i.imgur.com/EOC3rZj.png)

![](http://i.imgur.com/2SzuEWg.jpg)

**Comment by blunttedsmurf** [comment]
Same here. It was just working. I'm on version 14.

**Comment by TheWhiteHunter** [comment]
Also having this problem on version 14.

**Comment by grabberboy** [comment]
@hoppler  
hoppler can fix this easily

**Comment by Hannover2k** [comment]
Same error here using 17.4RC1

![image](https://user-images.githubusercontent.com/30209308/28245996-2fdab288-69c7-11e7-9401-3d4470390649.png)
![image](https://user-images.githubusercontent.com/30209308/28246003-4f9dd906-69c7-11e7-9567-ac0590fb155c.png)

**Comment by DxCx** [comment]
Thanks,
yes there seem to be an issue, i dont have time to debug it now but i was able to see i have it as well.
well debug this and update in a couple of hours when i get home

**Comment by lap00zza** [comment]
@DxCx if this helps at all, on the token `_` do `-30` so `token - 30`

**Comment by Alphafighter09** [comment]
Yea I also get this. Anyone know when its gonna get fixed

**Comment by NE03N** [comment]
I think 9Anime changed something in their website making the plugin unable to play any content... all we can do is wait for a fix which will hopefully come soon since this is literally the only descent plugin for anime out there...

**Comment by owlsharpton** [comment]
Having the same issue. :(

**Comment by icpryde** [comment]
I also can't seem to be getting any episodes to work it wont pull up any of the sources.

**Comment by DxCx** [comment]
alright so finally got home,
i was able to verify what @lap00zza said, you saved me some time, thanks!
expect an hotfix soon =)

**Comment by DxCx** [comment]
Just released version 0.0.15, update and enjoy 🎉

**Comment by hoppler** [comment]
@DxCx the real fix is to change 

in NineAnimeUrlExtender.py
```python
    @classmethod
    def _s(cls, t):
        i = 0
        for (e, c) in enumerate(t):
            i += ord(c) * e + e
        return i
```

to

```python
    @classmethod
    def _s(cls, t):
        i = 0
        for (e, c) in enumerate(t):
            i += ord(c) * e
        return i
```
(Remove the +e)

As they dont seem to use the token anymore you can change line 100 in embed_extractor from

```python
set_request = NineAnimeTokenDecoder.set_request("%s/token?v1" % url_base, http.send_request)
```
to

```python
set_request = None
```

and change the time.sleep from 1 second to about 0.2 seconds

**Comment by DxCx** [comment]
Thanks @hoppler i was planing to dig more into that but i wanted to first let the people have thier anime fix as soon as possible :)
