### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by AtsuiPanda** [DxCx/plugin.video.9anime#99]
I am a little new to kodi and such, I tried to update from the plugin and no god and tried to download again with downloader like it says in guide but it's still .14

**Comment by djrajir** [comment]
Also the repo needs to be updated. I use a Android TV device so I don't have access to a browser that can download the repo is very important for me.

**Comment by AtsuiPanda** [comment]
I got it , I just had to make my own little link for it to download. So yeah I couldn't find a short link is all lol but it seems to be working now , thank you to the guy who's updating it

**Comment by DxCx** [comment]
glad it works :)
